/* File:       shr-phoneuimessages.h
 *
 * GType name: PhoneuiMessages
 * D-Bus name: org.shr.phoneui.Messages
 *
 * Generated by GDBus Binding Tool 0.1. DO NOT EDIT.
 */

#ifndef __SHR_PHONEUI_MESSAGES_H__
#define __SHR_PHONEUI_MESSAGES_H__

#include <gio/gio.h>
#include <gdbusinterface.h>
#include <gdbusobjectproxy.h>
#include <gdbusproxymanager.h>
#include <gdbusobject.h>
#include <gdbusobjectmanager.h>
#include <gdbuscodegen-enumtypes.h>
#include <string.h>
#include <shr-types.h>

G_BEGIN_DECLS

#define TYPE_PHONEUI_MESSAGES         (phoneui_messages_get_gtype ())
#define PHONEUI_MESSAGES(o)           (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_PHONEUI_MESSAGES, PhoneuiMessages))
#define IS_PHONEUI_MESSAGES(o)        (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_PHONEUI_MESSAGES))
#define PHONEUI_MESSAGES_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE((o), TYPE_PHONEUI_MESSAGES, PhoneuiMessagesIface))

/**
 * PhoneuiMessages:
 *
 * Opaque type representing a proxy or an exported object.
 */
typedef struct _PhoneuiMessages PhoneuiMessages; /* Dummy typedef */
/**
 * PhoneuiMessagesIface:
 * @parent_iface: The parent interface.
 * @handle_display_list: Handler for the #PhoneuiMessages::handle-display-list signal.
 * @handle_display_message: Handler for the #PhoneuiMessages::handle-display-message signal.
 * @handle_create_message: Handler for the #PhoneuiMessages::handle-create-message signal.
 *
 * Virtual table.
 */
typedef struct _PhoneuiMessagesIface PhoneuiMessagesIface;

GType phoneui_messages_get_gtype (void) G_GNUC_CONST;
GDBusInterfaceInfo *phoneui_messages_interface_info (void);

/**
 * GET_PHONEUI_MESSAGES:
 * @object_proxy: A #GDBusObjectProxy.
 *
 * Convenience macro to get a #PhoneuiMessages interface proxy from @object_proxy.
 *
 * Returns: A #GDBusProxy object implementing the #PhoneuiMessages interface or %NULL if @object_proxy
 * does not implement the <literal>org.shr.phoneui.Messages</literal> D-Bus interface.
 * The returned reference must be released with g_object_unref().
 */
#define GET_PHONEUI_MESSAGES(object_proxy) (g_dbus_object_proxy_lookup_with_typecheck (object_proxy, "org.shr.phoneui.Messages", TYPE_PHONEUI_MESSAGES))

/**
 * PEEK_PHONEUI_MESSAGES:
 * @object_proxy: A #GDBusObjectProxy.
 *
 * Like GET_PHONEUI_MESSAGES() but doesn't increase the reference count on the returned object.
 *
 * <note><para>This macro is not safe to use outside the thread where the #GDBusProxyManager for @object_proxy was constructed in.</para></note>
 *
 * Returns: A #GDBusProxy object implementing the #PhoneuiMessages interface or %NULL if @object_proxy
 * does not implement the <literal>org.shr.phoneui.Messages</literal> D-Bus interface.
 * Do not free the returned object, it is owned by @object_proxy..
 */
#define PEEK_PHONEUI_MESSAGES(object_proxy) (g_dbus_object_proxy_peek_with_typecheck (object_proxy, "org.shr.phoneui.Messages", TYPE_PHONEUI_MESSAGES))


/* ---------------------------------------------------------------------- */

typedef struct _PhoneuiMessagesProxy PhoneuiMessagesProxy;
typedef struct _PhoneuiMessagesProxyClass PhoneuiMessagesProxyClass;

/**
 * PhoneuiMessagesProxyPrivate:
 *
 * The #PhoneuiMessagesProxyPrivate structure contains only private data.
 */
typedef struct _PhoneuiMessagesProxyPrivate PhoneuiMessagesProxyPrivate;

/**
 * PhoneuiMessagesProxy:
 *
 * The #PhoneuiMessagesProxy structure contains only private data and
 * should only be accessed using the provided API.
 */
struct _PhoneuiMessagesProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  PhoneuiMessagesProxyPrivate *priv;
};

/**
 * PhoneuiMessagesProxyClass:
 *
 * Class structure for #PhoneuiMessagesProxy.
 */
struct _PhoneuiMessagesProxyClass
{
  /*< private >*/
  GDBusProxyClass parent_class;
};

#define TYPE_PHONEUI_MESSAGES_PROXY (phoneui_messages_proxy_get_type ())
GType phoneui_messages_proxy_get_type (void) G_GNUC_CONST;

void phoneui_messages_proxy_new (GDBusConnection     *connection,
                   GDBusProxyFlags      flags,
                   const gchar         *name,
                   const gchar         *object_path,
                   GCancellable        *cancellable,
                   GAsyncReadyCallback  callback,
                   gpointer             user_data);
PhoneuiMessages *phoneui_messages_proxy_new_finish (GAsyncResult  *res,
                        GError       **error);
PhoneuiMessages *phoneui_messages_proxy_new_sync (GDBusConnection     *connection,
                       GDBusProxyFlags      flags,
                       const gchar         *name,
                       const gchar         *object_path,
                       GCancellable        *cancellable,
                       GError             **error);

void phoneui_messages_proxy_new_for_bus (GBusType             bus_type,
                           GDBusProxyFlags      flags,
                           const gchar         *name,
                           const gchar         *object_path,
                           GCancellable        *cancellable,
                           GAsyncReadyCallback  callback,
                           gpointer             user_data);
PhoneuiMessages *phoneui_messages_proxy_new_for_bus_finish (GAsyncResult  *res,
                                 GError       **error);
PhoneuiMessages *phoneui_messages_proxy_new_for_bus_sync (GBusType             bus_type,
                               GDBusProxyFlags      flags,
                               const gchar         *name,
                               const gchar         *object_path,
                               GCancellable        *cancellable,
                               GError             **error);

/* ---------------------------------------------------------------------- */

typedef struct _PhoneuiMessagesStub PhoneuiMessagesStub;
typedef struct _PhoneuiMessagesStubClass PhoneuiMessagesStubClass;

/**
 * PhoneuiMessagesStubPrivate:
 *
 * The #PhoneuiMessagesStubPrivate structure contains only private data.
 */
typedef struct _PhoneuiMessagesStubPrivate PhoneuiMessagesStubPrivate;

/**
 * PhoneuiMessagesStub:
 *
 * The #PhoneuiMessagesStub structure contains only private data and
 * should only be accessed using the provided API.
 */
struct _PhoneuiMessagesStub
{
  /*< private >*/
  GObject parent_instance;
  PhoneuiMessagesStubPrivate *priv;
};

/**
 * PhoneuiMessagesStubClass:
 *
 * Class structure for #PhoneuiMessagesStub.
 */
struct _PhoneuiMessagesStubClass
{
  /*< private >*/
  GObjectClass parent_class;
};

#define TYPE_PHONEUI_MESSAGES_STUB (phoneui_messages_stub_get_type ())
GType phoneui_messages_stub_get_type (void) G_GNUC_CONST;

PhoneuiMessages *phoneui_messages_stub_new (void);


struct _PhoneuiMessagesIface
{
  GTypeInterface parent_iface;

  /* Signal handlers for handling D-Bus method calls: */
  gboolean (*handle_display_list) (
        PhoneuiMessages *object,
        GDBusMethodInvocation *invocation,
        GVariant *filter);
  gboolean (*handle_display_message) (
        PhoneuiMessages *object,
        GDBusMethodInvocation *invocation,
        const gchar *path);
  gboolean (*handle_create_message) (
        PhoneuiMessages *object,
        GDBusMethodInvocation *invocation,
        GVariant *values);
};

/* C Bindings for properties */


/* D-Bus Methods */
void phoneui_messages_call_display_list (
        PhoneuiMessages *proxy,
        GVariant *filter,
        GCancellable *cancellable,
        GAsyncReadyCallback callback,
        gpointer user_data);

gboolean phoneui_messages_call_display_list_finish (
        PhoneuiMessages *proxy,
        GAsyncResult *res,
        GError **error);

gboolean phoneui_messages_call_display_list_sync (
        PhoneuiMessages *proxy,
        GVariant *filter,
        GCancellable *cancellable,
        GError **error);


void phoneui_messages_call_display_message (
        PhoneuiMessages *proxy,
        const gchar *path,
        GCancellable *cancellable,
        GAsyncReadyCallback callback,
        gpointer user_data);

gboolean phoneui_messages_call_display_message_finish (
        PhoneuiMessages *proxy,
        GAsyncResult *res,
        GError **error);

gboolean phoneui_messages_call_display_message_sync (
        PhoneuiMessages *proxy,
        const gchar *path,
        GCancellable *cancellable,
        GError **error);


void phoneui_messages_call_create_message (
        PhoneuiMessages *proxy,
        GVariant *values,
        GCancellable *cancellable,
        GAsyncReadyCallback callback,
        gpointer user_data);

gboolean phoneui_messages_call_create_message_finish (
        PhoneuiMessages *proxy,
        GAsyncResult *res,
        GError **error);

gboolean phoneui_messages_call_create_message_sync (
        PhoneuiMessages *proxy,
        GVariant *values,
        GCancellable *cancellable,
        GError **error);



/* D-Bus Methods Completion Helpers */
void phoneui_messages_complete_display_list (
        PhoneuiMessages *object,
        GDBusMethodInvocation *invocation);


void phoneui_messages_complete_display_message (
        PhoneuiMessages *object,
        GDBusMethodInvocation *invocation);


void phoneui_messages_complete_create_message (
        PhoneuiMessages *object,
        GDBusMethodInvocation *invocation);



/* D-Bus Signal Emission Helpers */

G_END_DECLS

#endif /* __SHR_PHONEUI_MESSAGES_H__ */
