/* File:       shr-phoneuidialer.h
 *
 * GType name: PhoneuiDialer
 * D-Bus name: org.shr.phoneui.Dialer
 *
 * Generated by GDBus Binding Tool 0.1. DO NOT EDIT.
 */

#ifndef __SHR_PHONEUI_DIALER_H__
#define __SHR_PHONEUI_DIALER_H__

#include <gio/gio.h>
#include <gdbusinterface.h>
#include <gdbusobjectproxy.h>
#include <gdbusproxymanager.h>
#include <gdbusobject.h>
#include <gdbusobjectmanager.h>
#include <gdbuscodegen-enumtypes.h>
#include <string.h>
#include <shr-types.h>

G_BEGIN_DECLS

#define TYPE_PHONEUI_DIALER         (phoneui_dialer_get_gtype ())
#define PHONEUI_DIALER(o)           (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_PHONEUI_DIALER, PhoneuiDialer))
#define IS_PHONEUI_DIALER(o)        (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_PHONEUI_DIALER))
#define PHONEUI_DIALER_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE((o), TYPE_PHONEUI_DIALER, PhoneuiDialerIface))

/**
 * PhoneuiDialer:
 *
 * Opaque type representing a proxy or an exported object.
 */
typedef struct _PhoneuiDialer PhoneuiDialer; /* Dummy typedef */
/**
 * PhoneuiDialerIface:
 * @parent_iface: The parent interface.
 * @handle_display: Handler for the #PhoneuiDialer::handle-display signal.
 *
 * Virtual table.
 */
typedef struct _PhoneuiDialerIface PhoneuiDialerIface;

GType phoneui_dialer_get_gtype (void) G_GNUC_CONST;
GDBusInterfaceInfo *phoneui_dialer_interface_info (void);

/**
 * GET_PHONEUI_DIALER:
 * @object_proxy: A #GDBusObjectProxy.
 *
 * Convenience macro to get a #PhoneuiDialer interface proxy from @object_proxy.
 *
 * Returns: A #GDBusProxy object implementing the #PhoneuiDialer interface or %NULL if @object_proxy
 * does not implement the <literal>org.shr.phoneui.Dialer</literal> D-Bus interface.
 * The returned reference must be released with g_object_unref().
 */
#define GET_PHONEUI_DIALER(object_proxy) (g_dbus_object_proxy_lookup_with_typecheck (object_proxy, "org.shr.phoneui.Dialer", TYPE_PHONEUI_DIALER))

/**
 * PEEK_PHONEUI_DIALER:
 * @object_proxy: A #GDBusObjectProxy.
 *
 * Like GET_PHONEUI_DIALER() but doesn't increase the reference count on the returned object.
 *
 * <note><para>This macro is not safe to use outside the thread where the #GDBusProxyManager for @object_proxy was constructed in.</para></note>
 *
 * Returns: A #GDBusProxy object implementing the #PhoneuiDialer interface or %NULL if @object_proxy
 * does not implement the <literal>org.shr.phoneui.Dialer</literal> D-Bus interface.
 * Do not free the returned object, it is owned by @object_proxy..
 */
#define PEEK_PHONEUI_DIALER(object_proxy) (g_dbus_object_proxy_peek_with_typecheck (object_proxy, "org.shr.phoneui.Dialer", TYPE_PHONEUI_DIALER))


/* ---------------------------------------------------------------------- */

typedef struct _PhoneuiDialerProxy PhoneuiDialerProxy;
typedef struct _PhoneuiDialerProxyClass PhoneuiDialerProxyClass;

/**
 * PhoneuiDialerProxyPrivate:
 *
 * The #PhoneuiDialerProxyPrivate structure contains only private data.
 */
typedef struct _PhoneuiDialerProxyPrivate PhoneuiDialerProxyPrivate;

/**
 * PhoneuiDialerProxy:
 *
 * The #PhoneuiDialerProxy structure contains only private data and
 * should only be accessed using the provided API.
 */
struct _PhoneuiDialerProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  PhoneuiDialerProxyPrivate *priv;
};

/**
 * PhoneuiDialerProxyClass:
 *
 * Class structure for #PhoneuiDialerProxy.
 */
struct _PhoneuiDialerProxyClass
{
  /*< private >*/
  GDBusProxyClass parent_class;
};

#define TYPE_PHONEUI_DIALER_PROXY (phoneui_dialer_proxy_get_type ())
GType phoneui_dialer_proxy_get_type (void) G_GNUC_CONST;

void phoneui_dialer_proxy_new (GDBusConnection     *connection,
                   GDBusProxyFlags      flags,
                   const gchar         *name,
                   const gchar         *object_path,
                   GCancellable        *cancellable,
                   GAsyncReadyCallback  callback,
                   gpointer             user_data);
PhoneuiDialer *phoneui_dialer_proxy_new_finish (GAsyncResult  *res,
                        GError       **error);
PhoneuiDialer *phoneui_dialer_proxy_new_sync (GDBusConnection     *connection,
                       GDBusProxyFlags      flags,
                       const gchar         *name,
                       const gchar         *object_path,
                       GCancellable        *cancellable,
                       GError             **error);

void phoneui_dialer_proxy_new_for_bus (GBusType             bus_type,
                           GDBusProxyFlags      flags,
                           const gchar         *name,
                           const gchar         *object_path,
                           GCancellable        *cancellable,
                           GAsyncReadyCallback  callback,
                           gpointer             user_data);
PhoneuiDialer *phoneui_dialer_proxy_new_for_bus_finish (GAsyncResult  *res,
                                 GError       **error);
PhoneuiDialer *phoneui_dialer_proxy_new_for_bus_sync (GBusType             bus_type,
                               GDBusProxyFlags      flags,
                               const gchar         *name,
                               const gchar         *object_path,
                               GCancellable        *cancellable,
                               GError             **error);

/* ---------------------------------------------------------------------- */

typedef struct _PhoneuiDialerStub PhoneuiDialerStub;
typedef struct _PhoneuiDialerStubClass PhoneuiDialerStubClass;

/**
 * PhoneuiDialerStubPrivate:
 *
 * The #PhoneuiDialerStubPrivate structure contains only private data.
 */
typedef struct _PhoneuiDialerStubPrivate PhoneuiDialerStubPrivate;

/**
 * PhoneuiDialerStub:
 *
 * The #PhoneuiDialerStub structure contains only private data and
 * should only be accessed using the provided API.
 */
struct _PhoneuiDialerStub
{
  /*< private >*/
  GObject parent_instance;
  PhoneuiDialerStubPrivate *priv;
};

/**
 * PhoneuiDialerStubClass:
 *
 * Class structure for #PhoneuiDialerStub.
 */
struct _PhoneuiDialerStubClass
{
  /*< private >*/
  GObjectClass parent_class;
};

#define TYPE_PHONEUI_DIALER_STUB (phoneui_dialer_stub_get_type ())
GType phoneui_dialer_stub_get_type (void) G_GNUC_CONST;

PhoneuiDialer *phoneui_dialer_stub_new (void);


struct _PhoneuiDialerIface
{
  GTypeInterface parent_iface;

  /* Signal handlers for handling D-Bus method calls: */
  gboolean (*handle_display) (
        PhoneuiDialer *object,
        GDBusMethodInvocation *invocation,
        GVariant *values);
};

/* C Bindings for properties */


/* D-Bus Methods */
void phoneui_dialer_call_display (
        PhoneuiDialer *proxy,
        GVariant *values,
        GCancellable *cancellable,
        GAsyncReadyCallback callback,
        gpointer user_data);

gboolean phoneui_dialer_call_display_finish (
        PhoneuiDialer *proxy,
        GAsyncResult *res,
        GError **error);

gboolean phoneui_dialer_call_display_sync (
        PhoneuiDialer *proxy,
        GVariant *values,
        GCancellable *cancellable,
        GError **error);



/* D-Bus Methods Completion Helpers */
void phoneui_dialer_complete_display (
        PhoneuiDialer *object,
        GDBusMethodInvocation *invocation);



/* D-Bus Signal Emission Helpers */

G_END_DECLS

#endif /* __SHR_PHONEUI_DIALER_H__ */
