/* File:       shr-phoneuidialer.c
 *
 * GType name: PhoneuiDialer
 * D-Bus name: org.shr.phoneui.Dialer
 *
 * Generated by GDBus Binding Tool 0.1. DO NOT EDIT.
 */

/**
 * SECTION:shr-phoneuidialer
 * @title: PhoneuiDialer
 * @short_description: Wraps the org.shr.phoneui.Dialer D-Bus interface
 * @include: gio/gio.h
 *
 * The abstract #PhoneuiDialer interface type wraps the <literal>org.shr.phoneui.Dialer</literal> D-Bus interface. Two concrete implementations exists: #PhoneuiDialerProxy (for client-side usage) and #PhoneuiDialerStub (for service-side usage).
 *
 * This code was generated from the following D-Bus introspection XML:
 * <programlisting><![CDATA[
 * <interface name="org.shr.phoneui.Dialer">
 *   <method name="Display">
 *     <annotation name="org.freedesktop.DBus.GLib.Async" value="true">
 *     </annotation>
 *     <arg type="a{sv}" name="values" direction="in">
 *     </arg>
 *   </method>
 * </interface>
 * ]]></programlisting>
 *
 */

#include <shr-phoneuidialer.h>
#include <shr-types.h>
#include <shr-bindingsprivate.h>
#include <shr-marshallers.h>

static guint phoneui_dialer_register_object (GDBusInterface *object,
                    GDBusConnection *connection,
                    const gchar *object_path,
                    GError **error);
static void phoneui_dialer_flush (GDBusInterface *object);
static GVariant *phoneui_dialer_get_properties (GDBusInterface *object);
static GDBusInterfaceInfo *phoneui_dialer_g_dbus_interface_interface_info (GDBusInterface *object);
static GDBusObject *phoneui_dialer_g_dbus_interface_get_object (GDBusInterface *interface);
static void phoneui_dialer_g_dbus_interface_set_object (GDBusInterface *interface, GDBusObject *object);
static GDBusInterfaceFlags phoneui_dialer_g_dbus_interface_get_flags (GDBusInterface *interface);
static void phoneui_dialer_g_dbus_interface_set_flags (GDBusInterface *interface, GDBusInterfaceFlags flags);

typedef PhoneuiDialerIface PhoneuiDialerInterface;
#define phoneui_dialer_get_type phoneui_dialer_get_gtype
G_DEFINE_INTERFACE (PhoneuiDialer, phoneui_dialer, G_TYPE_OBJECT);
#undef phoneui_dialer_get_type


enum
{
  _0_SIGNAL,
  __DISPLAY_METHOD,
  __LAST_SIGNAL
};

static guint signals[__LAST_SIGNAL] = {0};


enum
{
  PROP_0,
};

/* ------------------------------------------------------------------------- */

/* Various lookup tables */

static GHashTable *_method_name_to_id = NULL;
static GHashTable *_signal_name_to_id = NULL;
static GHashTable *_property_name_to_id = NULL;
static GHashTable *_property_gname_to_name = NULL;
static GHashTable *_property_name_to_gname = NULL;


static guint
lookup_method_id_from_method_name (const gchar *method_name)
{
  return GPOINTER_TO_UINT (g_hash_table_lookup (_method_name_to_id, method_name));
}

static guint
lookup_signal_id_from_signal_name (const gchar *signal_name)
{
  return GPOINTER_TO_UINT (g_hash_table_lookup (_signal_name_to_id, signal_name));
}

static guint
lookup_property_id_from_property_name (const gchar *property_name)
{
  return GPOINTER_TO_UINT (g_hash_table_lookup (_property_name_to_id, property_name));
}

static const gchar *
lookup_property_name_from_property_gname (const gchar *property_gname)
{
  return g_hash_table_lookup (_property_gname_to_name, property_gname);
}

static const gchar *
lookup_property_gname_from_property_name (const gchar *property_name)
{
  return g_hash_table_lookup (_property_name_to_gname, property_name);
}

/* ------------------------------------------------------------------------- */
static void dbus_iface_init (GDBusInterfaceIface *iface)
{
  iface->get_info = phoneui_dialer_g_dbus_interface_interface_info;
  iface->get_properties = phoneui_dialer_get_properties;
  iface->flush = phoneui_dialer_flush;
  iface->register_object = phoneui_dialer_register_object;
  iface->set_object = phoneui_dialer_g_dbus_interface_set_object;
  iface->get_object = phoneui_dialer_g_dbus_interface_get_object;
  iface->set_flags = phoneui_dialer_g_dbus_interface_set_flags;
  iface->get_flags = phoneui_dialer_g_dbus_interface_get_flags;
}

static void
phoneui_dialer_default_init (PhoneuiDialerIface *iface)
{

  /* Build lookup structures */
  _method_name_to_id = g_hash_table_new (g_str_hash, g_str_equal);
  _signal_name_to_id = g_hash_table_new (g_str_hash, g_str_equal);
  _property_name_to_id = g_hash_table_new (g_str_hash, g_str_equal);
  _property_gname_to_name = g_hash_table_new (g_str_hash, g_str_equal);
  _property_name_to_gname = g_hash_table_new (g_str_hash, g_str_equal);
  g_hash_table_insert (_method_name_to_id, "Display", GUINT_TO_POINTER (__DISPLAY_METHOD));

  /* GObject signals definitions for D-Bus signals: */

  /* GObject signals definitions for D-Bus methods: */
  /**
   * PhoneuiDialer::handle-display:
   * @object: The exported object emitting the signal.
   * @invocation: A #GDBusMethodInvocation object that can be used to return a value or error.
   * @values: Parameter.
   *
   * On exported objects, this signal is emitted when a remote process (identified by @invocation) invokes the <literal>org.shr.phoneui.Dialer.Display()</literal> D-Bus method on @object. Use phoneui_dialer_complete_display() to return a value or g_dbus_method_invocation_return_error() to return an error.
   *
   * The signal is emitted in the
   * <link linkend="g-main-context-push-thread-default">thread-default main loop</link>
   * of the thread that @object was registered in.
   *
   * On proxies, this signal is never emitted.
   *
   * Returns: %TRUE if you want to handle the method call (will stop further handlers from being called), %FALSE otherwise.
   */
  signals[__DISPLAY_METHOD] =
    g_signal_new ("handle-display",
                  G_TYPE_FROM_INTERFACE (iface),
                  G_SIGNAL_RUN_LAST,
                  G_STRUCT_OFFSET (PhoneuiDialerIface, handle_display),
                  g_signal_accumulator_true_handled,
                  NULL,
                  _shr_gdbus_cclosure_marshaller_BOOLEAN__OBJECT_VARIANT,
                  G_TYPE_BOOLEAN,
                  2,
                  G_TYPE_DBUS_METHOD_INVOCATION,
                  G_TYPE_VARIANT);

  /* GObject property definitions for D-Bus properties: */
}


/* C Bindings for properties */

/**
 * phoneui_dialer_call_display:
 * @proxy: A #PhoneuiDialer.
 * @values: Method parameter.
 * @cancellable: A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL if you don't care about the result of the method invocation.
 * @user_data: Data to pass to @callback.
 *
 * Invokes the <literal>org.shr.phoneui.Dialer.Display()</literal>
 * D-Bus method on the remote object represented by @proxy.
 *
 * This is an asynchronous method. When the operation is finished,
 * callback will be invoked in the
 * <link linkend="g-main-context-push-thread-default">thread-default main loop</link>
 * of the thread you are calling this method from. You can then call
 * phoneui_dialer_call_display_finish() to get the result of the operation.
 * See phoneui_dialer_call_display_sync() for the synchronous version of this method.
 */
void phoneui_dialer_call_display (
        PhoneuiDialer *proxy,
        GVariant *values,
        GCancellable *cancellable,
        GAsyncReadyCallback callback,
        gpointer user_data)
{
  GVariant *_params;
  _params = g_variant_new ("(*)",
                           values);
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
                     "Display",
                     _params,
                     G_DBUS_CALL_FLAGS_NONE,
                     -1,
                     cancellable,
                     callback,
                     user_data);
}

/**
 * phoneui_dialer_call_display_finish:
 * @proxy: A #PhoneuiDialer.
 * @res: A #GAsyncResult obtained from the #GAsyncReadyCallback passed to phoneui_dialer_call_display().
 * @error: Return location for error or %NULL.
 *
 * Finishes invoking the <literal>org.shr.phoneui.Dialer.Display()</literal>
 * D-Bus method on the remote object represented by @proxy.
 *
 * Returns: %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean phoneui_dialer_call_display_finish (
        PhoneuiDialer *proxy,
        GAsyncResult *res,
        GError **error)
{
  gboolean _ret = FALSE;
  GVariant *_result;
  _result = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_result == NULL)
    goto _out;
  g_variant_unref (_result);
  _ret = TRUE;
_out:
  return _ret;
}

/**
 * phoneui_dialer_call_display_sync:
 * @proxy: A #PhoneuiDialer.
 * @values: Method parameter.
 * @cancellable: A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <literal>org.shr.phoneui.Dialer.Display()</literal>
 * D-Bus method on the remote object represented by @proxy.
 * The calling thread is blocked until a reply is received. See
 * phoneui_dialer_call_display() for the asynchronous version of this method.
 *
 * Returns: %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean phoneui_dialer_call_display_sync (
        PhoneuiDialer *proxy,
        GVariant *values,
        GCancellable *cancellable,
        GError **error)
{
  gboolean _ret = FALSE;
  GVariant *_params;
  GVariant *_result;
  _params = g_variant_new ("(*)",
                           values);
  _result = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
                                   "Display",
                                   _params,
                                   G_DBUS_CALL_FLAGS_NONE,
                                   -1,
                                   cancellable,
                                   error);
  if (_result == NULL)
    goto _out;
  g_variant_unref (_result);
  _ret = TRUE;
_out:
  return _ret;
}


/**
 * phoneui_dialer_complete_display:
 * @object: A #PhoneuiDialer.
 * @invocation: A #GDBusMethodInvocation.
 *
 * Completes handling the <literal>org.shr.phoneui.Dialer.Display()</literal>
 * D-Bus method invocation by returning a value.
 *
 * If you want to return an error, use g_dbus_method_invocation_return_error()
 * or similar instead.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void phoneui_dialer_complete_display (
        PhoneuiDialer *object,
        GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation, NULL);
}


static const GDBusArgInfo phoneui_dialer_method_in_Display_values =
{
  -1,
  "values",
  "a{sv}",
  (GDBusAnnotationInfo **) NULL
};
static const GDBusArgInfo * const phoneui_dialer_method_in_Display_arg_pointers[] =
{
  &phoneui_dialer_method_in_Display_values,
  NULL
};

static const GDBusAnnotationInfo Display_method_annotations_annotation_0 = {
  -1,
  "org.freedesktop.DBus.GLib.Async",
  "true",
};

static const GDBusAnnotationInfo *Display_method_annotations[] = {
  &Display_method_annotations_annotation_0,
  NULL
};

static const GDBusMethodInfo phoneui_dialer_method_Display =
{
  -1,
  "Display",
  (GDBusArgInfo **) &phoneui_dialer_method_in_Display_arg_pointers,
  (GDBusArgInfo **) NULL,
  (GDBusAnnotationInfo **) Display_method_annotations,
};

static const GDBusMethodInfo * const phoneui_dialer_method_info_pointers[] =
{
  &phoneui_dialer_method_Display,
  NULL
};

static const GDBusInterfaceInfo _phoneui_dialer_interface_info =
{
  -1,
  "org.shr.phoneui.Dialer",
  (GDBusMethodInfo **) &phoneui_dialer_method_info_pointers,
  (GDBusSignalInfo **) NULL,
  (GDBusPropertyInfo **) NULL,
  (GDBusAnnotationInfo **) NULL
};

static void
handle_method_call_real (GDBusConnection       *connection,
                         const gchar           *sender,
                         const gchar           *object_path,
                         const gchar           *interface_name,
                         const gchar           *method_name,
                         GVariant              *parameters,
                         GDBusMethodInvocation *invocation,
                         gpointer               user_data)
{
  guint method_id;
  method_id = lookup_method_id_from_method_name (method_name);
  switch (method_id)
    {
    case __DISPLAY_METHOD:
      {
        PhoneuiDialer *object = PHONEUI_DIALER (user_data);
        gboolean handled;
        GVariant *arg_values;
        g_variant_get (parameters,
                       "(*)",
                       &arg_values);
        g_signal_emit (object,
                       signals[method_id],
                       0, invocation, arg_values, &handled);
        g_variant_unref ((gpointer) arg_values);
        if (!handled)
          goto not_implemented;
      }
      break;

    default:
not_implemented:
      g_dbus_method_invocation_return_error (invocation,
                                             G_DBUS_ERROR,
                                             G_DBUS_ERROR_NOT_SUPPORTED,
                                             "Method `%s' is not implemented",
                                             method_name);
      break;
    }
};

typedef struct
{
  GDBusMethodInvocation *invocation;
  gpointer               user_data;
} HandleMethodInThreadData;

static gboolean
handle_method_call_in_thread_func (GIOSchedulerJob *job,
                                   GCancellable    *cancellable,
                                   gpointer         user_data)
{
  HandleMethodInThreadData *data = user_data;

  handle_method_call_real (g_dbus_method_invocation_get_connection (data->invocation),
                           g_dbus_method_invocation_get_sender (data->invocation),
                           g_dbus_method_invocation_get_object_path (data->invocation),
                           g_dbus_method_invocation_get_interface_name (data->invocation),
                           g_dbus_method_invocation_get_method_name (data->invocation),
                           g_dbus_method_invocation_get_parameters (data->invocation),
                           data->invocation,
                           data->user_data);
  return FALSE; /* job is complete */
}

static void
handle_method_call (GDBusConnection       *connection,
                    const gchar           *sender,
                    const gchar           *object_path,
                    const gchar           *interface_name,
                    const gchar           *method_name,
                    GVariant              *parameters,
                    GDBusMethodInvocation *invocation,
                    gpointer               user_data)
{
  GDBusInterface *interface = G_DBUS_INTERFACE (user_data);
  GDBusInterfaceFlags flags;

  flags = g_dbus_interface_get_flags (interface);
  if (flags & G_DBUS_INTERFACE_FLAGS_RUN_IN_THREAD)
    {
      HandleMethodInThreadData *data;
      data = g_new0 (HandleMethodInThreadData, 1);
      data->invocation = invocation;
      data->user_data = user_data;
      g_io_scheduler_push_job (handle_method_call_in_thread_func,
                               data,
                               g_free, /* since we don't need refs on objects */
                               G_PRIORITY_DEFAULT,
                               NULL); /* GCancellable* */
    }
  else
    {
      handle_method_call_real (connection,
                               sender,
                               object_path,
                               interface_name,
                               method_name,
                               parameters,
                               invocation,
                               user_data);
    }
}

static GVariant *
get_property (GDBusConnection  *connection,
              const gchar      *sender,
              const gchar      *object_path,
              const gchar      *interface_name,
              const gchar      *property_name,
              GError          **error,
              gpointer          user_data)
{
  GVariant *ret;
  guint prop_id;
  prop_id = lookup_property_id_from_property_name (property_name);
  ret = NULL;
  switch (prop_id)
    {
    default:
      g_assert_not_reached ();
      break;
    }

  if (ret == NULL)
    {
      GVariant *untrusted_empty;
      GDBusPropertyInfo *property_info;
      const GVariantType *type;
      property_info = g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_phoneui_dialer_interface_info, property_name);
      type = G_VARIANT_TYPE (property_info->signature);
      untrusted_empty = g_variant_new_from_data (type, NULL, 0, FALSE, NULL, NULL);
      ret = g_variant_get_normal_form (untrusted_empty);
      g_variant_unref (untrusted_empty);
    }

  return ret;
};

static gboolean
set_property (GDBusConnection  *connection,
              const gchar      *sender,
              const gchar      *object_path,
              const gchar      *interface_name,
              const gchar      *property_name,
              GVariant         *value,
              GError          **error,
              gpointer          user_data)
{
  gboolean ret;
  guint prop_id;
  prop_id = lookup_property_id_from_property_name (property_name);
  ret = TRUE;
  switch (prop_id)
    {
    default:
      g_set_error (error,
                   G_DBUS_ERROR,
                   G_DBUS_ERROR_NOT_SUPPORTED,
                   "This implementation does not support property `%s'",
                   property_name);
      ret = FALSE;
      break;
    }

  return ret;
};

static const GDBusInterfaceVTable phoneui_dialer_interface_vtable =
{
  handle_method_call,
  get_property,
  set_property,
};

/* ---------------------------------------------------------------------- */

typedef struct {
  gpointer data;
  gsize size;
} _VariantBlob;

static void
_variant_blob_free (_VariantBlob *blob)
{
  g_free (blob->data);
  g_free (blob);
}

static _VariantBlob *
_variant_blob_new (GVariant *value)
{
  _VariantBlob *blob;
  blob = g_new0 (_VariantBlob, 1);
  blob->size = g_variant_get_size (value);
  blob->data = g_malloc (blob->size);
  g_variant_store (value, blob->data);
  return blob;
}

static gboolean
_variant_blob_equal (_VariantBlob *a,
                    _VariantBlob *b)
{
  return (a->size == b->size) && (memcmp (a->data, b->data, a->size) == 0);
}
/* ---------------------------------------------------------------------- */

static gboolean
emit_notifications_in_idle (gpointer user_data)
{
  GObject *object = G_OBJECT (user_data);
  GDBusConnection *connection;
  const gchar *path;
  GHashTable *notification_queue;
  GHashTableIter iter;
  const gchar *property_name;
  GVariant *value;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  GHashTable *pvc;
  gboolean has_changes;

  notification_queue = g_object_get_data (object, "gdbus-codegen-notification-queue");
  path = g_object_get_data (object, "gdbus-codegen-path");
  connection = g_object_get_data (object, "gdbus-codegen-connection");
  pvc = g_object_get_data (object, "gdbus-codegen-pvc");
  g_assert (notification_queue != NULL && path != NULL && connection != NULL && pvc != NULL);

  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  g_hash_table_iter_init (&iter, notification_queue);
  has_changes = FALSE;
  while (g_hash_table_iter_next (&iter, (gpointer) &property_name, (gpointer) &value))
    {
      _VariantBlob *cached_blob;
      _VariantBlob *blob;
      cached_blob = g_hash_table_lookup (pvc, property_name);
      blob = _variant_blob_new (value);
      if (cached_blob == NULL || !_variant_blob_equal (cached_blob, blob))
        {
          g_hash_table_insert (pvc, (gpointer) property_name, blob);
          g_variant_builder_add (&builder, "{sv}", property_name, value);
          has_changes = TRUE;
        }
      else
        {
          _variant_blob_free (blob);
        }
    }

  if (has_changes)
    {
      g_dbus_connection_emit_signal (connection,
                                     NULL,
                                     path,
                                     "org.freedesktop.DBus.Properties",
                                     "PropertiesChanged",
                                     g_variant_new ("(sa{sv}as)",
                                                    "org.shr.phoneui.Dialer",
                                                    &builder,
                                                    &invalidated_builder),
                                     NULL);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }

  g_hash_table_remove_all (notification_queue);
  g_object_set_data (object, "gdbus-codegen-notification-idle-source", NULL);
  return FALSE;
}

static void
queue_notification (GObject     *object,
                    const gchar *property_name,
                    GVariant    *value)
{
  GHashTable *notification_queue;
  GSource *idle_source;
  notification_queue = g_object_get_data (object, "gdbus-codegen-notification-queue");
  if (notification_queue == NULL)
    {
      notification_queue = g_hash_table_new_full (g_str_hash, g_str_equal, NULL, (GDestroyNotify) g_variant_unref);
      g_object_set_data_full (object, "gdbus-codegen-notification-queue", notification_queue, (GDestroyNotify) g_hash_table_unref);
    }
  g_hash_table_insert (notification_queue, (gpointer) property_name, (gpointer) value); /* adopts value */
  idle_source = g_object_get_data (object, "gdbus-codegen-notification-idle-source");
  if (idle_source == NULL)
    {
      idle_source = g_idle_source_new ();
      g_source_set_priority (idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (idle_source,
                             emit_notifications_in_idle,
                             g_object_ref (object),
                             (GDestroyNotify) g_object_unref);
      g_source_attach (idle_source, g_main_context_get_thread_default ());
      g_source_unref (idle_source);
      g_object_set_data (object, "gdbus-codegen-notification-idle-source", idle_source);
    }
}

static void
phoneui_dialer_flush (GDBusInterface *_object)
{
  PhoneuiDialer *object = PHONEUI_DIALER (_object);
  GSource *idle_source;
  idle_source = g_object_get_data (G_OBJECT (object), "gdbus-codegen-notification-idle-source");
  if (idle_source != NULL)
    {
      emit_notifications_in_idle (object);
      g_source_destroy (idle_source);
    }
}

static void
on_notify (GObject    *object,
           GParamSpec *pspec,
           gpointer    user_data)
{
  GDBusConnection *connection;
  const gchar *path;
  GVariant *value;
  const gchar *property_name;

  path = g_object_get_data (object, "gdbus-codegen-path");
  connection = g_object_get_data (object, "gdbus-codegen-connection");
  if (connection == NULL || path == NULL)
    goto out;
  property_name = lookup_property_name_from_property_gname (pspec->name);
  if (property_name == NULL)
    goto out;

  value = get_property (connection, NULL, path, "org.shr.phoneui.Dialer", property_name, NULL, object);
  if (value != NULL)
    {
      if (g_variant_is_floating (value))
        g_variant_ref_sink (value);
      queue_notification (object, property_name, value);
    }
out:
  ;
}

static void
on_object_unregistered (GObject *object)
{
  GSource *idle_source;
  idle_source = g_object_get_data (G_OBJECT (object), "gdbus-codegen-notification-idle-source");
  if (idle_source != NULL)
    g_source_destroy (idle_source);
  g_object_set_data (G_OBJECT (object), "gdbus-codegen-notification-idle-source", NULL);
  g_object_set_data (G_OBJECT (object), "gdbus-codegen-path", NULL);
  g_object_set_data (G_OBJECT (object), "gdbus-codegen-connection", NULL);
  g_signal_handlers_disconnect_by_func (object, on_notify, NULL);
}

static guint
phoneui_dialer_register_object (GDBusInterface *_object,
           GDBusConnection *connection,
           const gchar *object_path,
           GError **error)
{
  PhoneuiDialer *object = PHONEUI_DIALER (_object);
  GHashTable *pvc;
  guint n;

  pvc = g_hash_table_new_full (g_str_hash, g_str_equal, NULL, (GDestroyNotify) _variant_blob_free);
  if (_phoneui_dialer_interface_info.properties != NULL)
    {
      for (n = 0; _phoneui_dialer_interface_info.properties[n] != NULL; n++)
        {
          GDBusPropertyInfo *prop_info = _phoneui_dialer_interface_info.properties[n];
          if (prop_info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
            {
              GVariant *value;
              value = get_property (connection, NULL, object_path, "org.shr.phoneui.Dialer", prop_info->name, NULL, object);
              if (value != NULL)
                {
                  if (g_variant_is_floating (value))
                    g_variant_ref_sink (value);
                  g_hash_table_insert (pvc, prop_info->name, _variant_blob_new (value));
                  g_variant_unref (value);
                }
            }
        }
    }

  g_object_set_data_full (G_OBJECT (object), "gdbus-codegen-path", (gpointer) g_strdup (object_path), g_free);
  g_object_set_data (G_OBJECT (object), "gdbus-codegen-connection", (gpointer) connection);
  g_object_set_data_full (G_OBJECT (object), "gdbus-codegen-pvc", (gpointer) pvc, (GDestroyNotify) g_hash_table_unref);
  g_signal_connect (object, "notify", G_CALLBACK (on_notify), NULL);
  return g_dbus_connection_register_object (connection,
          object_path,
          (GDBusInterfaceInfo *) &_phoneui_dialer_interface_info,
          &phoneui_dialer_interface_vtable,
          object,
          (GDestroyNotify) on_object_unregistered,
          error);
}

/**
 * phoneui_dialer_interface_info:
 *
 * Gets interface description for the <literal>org.shr.phoneui.Dialer</literal> D-Bus interface.
 *
 * Returns: A #GDBusInterfaceInfo. Do not free, the object is statically allocated.
 */
GDBusInterfaceInfo *
phoneui_dialer_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_phoneui_dialer_interface_info;
}

static GDBusInterfaceInfo *
phoneui_dialer_g_dbus_interface_interface_info (GDBusInterface *object)
{
  return phoneui_dialer_interface_info ();
}

static GVariant *
phoneui_dialer_get_properties (GDBusInterface *object)
{
  GDBusConnection *connection;
  const gchar *object_path;
  GVariantBuilder builder;
  guint n;

  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));

  if (_phoneui_dialer_interface_info.properties == NULL)
    goto out;

  connection = g_object_get_data (G_OBJECT (object), "gdbus-codegen-connection");
  object_path = g_object_get_data (G_OBJECT (object), "gdbus-codegen-path");

  for (n = 0; _phoneui_dialer_interface_info.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *prop_info = _phoneui_dialer_interface_info.properties[n];
      if (prop_info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = get_property (connection, NULL, object_path, "org.shr.phoneui.Dialer", prop_info->name, NULL, object);
          if (value != NULL)
            {
              if (g_variant_is_floating (value))
                g_variant_ref_sink (value);
              g_variant_builder_add (&builder, "{sv}", prop_info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}


/* ---------------------------------------------------------------------- */

static void proxy_iface_init (PhoneuiDialerIface *iface);

G_DEFINE_TYPE_WITH_CODE (PhoneuiDialerProxy, phoneui_dialer_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_PHONEUI_DIALER, proxy_iface_init));

static void
phoneui_dialer_proxy_init (PhoneuiDialerProxy *proxy)
{
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy),
                                   (GDBusInterfaceInfo *) &_phoneui_dialer_interface_info);
}

static void
g_signal (GDBusProxy  *proxy,
          const gchar *sender_name,
          const gchar *signal_name,
          GVariant    *parameters)
{
  guint signal_id;
  signal_id = lookup_signal_id_from_signal_name (signal_name);
  switch (signal_id)
    {
    }
}

static void
phoneui_dialer_proxy_get_property (GObject      *object,
                       guint         prop_id,
                       GValue       *value,
                       GParamSpec   *pspec)
{
  G_GNUC_UNUSED GVariant *cached;
  switch (prop_id)
    {

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, prop_id, pspec);
      break;
    }
}

static void
property_set_cb (GDBusProxy   *proxy,
                 GAsyncResult *res,
                 gpointer      user_data)
{
  const gchar *property_name = user_data;
  GError *error;
  GVariant *result;

  error = NULL;
  result = g_dbus_proxy_call_finish (proxy, res, &error);
  if (result == NULL)
    {
      g_warning ("Error setting property `%s': %s", property_name, error->message);
      g_error_free (error);
    }
  else
    {
      g_variant_unref (result);
    }
}

static void
phoneui_dialer_proxy_set_property (GObject      *object,
                       guint         prop_id,
                       const GValue *value,
                       GParamSpec   *pspec)
{
  GVariant *new_value;
  const gchar *property_name;
  new_value = NULL;
  property_name = NULL;
  switch (prop_id)
    {

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, prop_id, pspec);
      break;
    }

  if (new_value != NULL)
    {
      g_variant_ref_sink (new_value);
      g_dbus_proxy_call (G_DBUS_PROXY (object),
                         "org.freedesktop.DBus.Properties.Set",
                         g_variant_new ("(ssv)",
                                        "org.shr.phoneui.Dialer",
                                        property_name,
                                        new_value),
                         G_DBUS_CALL_FLAGS_NONE,
                         -1,
                         NULL,
                         (GAsyncReadyCallback) property_set_cb,
                         (gpointer) property_name);
      g_variant_unref (new_value);
    }

}

static void
g_properties_changed (GDBusProxy         *proxy,
                      GVariant           *changed_properties,
                      const gchar* const *invalidated_properties)
{
  guint n;
  const gchar *key;
  GVariantIter *iter;
  const gchar *gname;

  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      gname = lookup_property_gname_from_property_name (key);
      if (gname != NULL)
        g_object_notify (G_OBJECT (proxy), gname);
    }

  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      gname = lookup_property_gname_from_property_name (invalidated_properties[n]);
      if (gname != NULL)
        g_object_notify (G_OBJECT (proxy), gname);
    }

}

static void
phoneui_dialer_proxy_class_init (PhoneuiDialerProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->get_property = phoneui_dialer_proxy_get_property;
  gobject_class->set_property = phoneui_dialer_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = g_signal;
  proxy_class->g_properties_changed = g_properties_changed;

}

static void
proxy_iface_init (PhoneuiDialerIface *iface)
{
}


/**
 * phoneui_dialer_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags used when constructing the proxy.
 * @name: A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: A #GCancellable or %NULL.
 * @callback: Callback function to invoke when the proxy is ready.
 * @user_data: User data to pass to @callback.
 *
 * Like g_dbus_proxy_new() but returns a #PhoneuiDialerProxy.
 *
 * This is a failable asynchronous constructor - when the proxy is ready, callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this function from. You can then call phoneui_dialer_proxy_new_finish() to get the result. See phoneui_dialer_proxy_new_sync() for the synchronous version.
 */
void phoneui_dialer_proxy_new (GDBusConnection     *connection,
                   GDBusProxyFlags      flags,
                   const gchar         *name,
                   const gchar         *object_path,
                   GCancellable        *cancellable,
                   GAsyncReadyCallback  callback,
                   gpointer             user_data)
{
  g_async_initable_new_async (TYPE_PHONEUI_DIALER_PROXY,
                              G_PRIORITY_DEFAULT,
                              cancellable,
                              callback,
                              user_data,
                              "g-flags", flags,
                              "g-name", name,
                              "g-connection", connection,
                              "g-object-path", object_path,
                              "g-interface-name", "org.shr.phoneui.Dialer",
                              NULL);
}

/**
 * phoneui_dialer_proxy_new_finish:
 * @res: A #GAsyncResult obtained from the #GAsyncReadyCallback function passed to phoneui_dialer_proxy_new().
 * @error: Return location for error or %NULL.
 *
 * Finishes creating a #PhoneuiDialerProxy.
 *
 * Returns: A #PhoneuiDialerProxy or %NULL if @error is set. Free with g_object_unref().
 */
PhoneuiDialer *phoneui_dialer_proxy_new_finish (GAsyncResult  *res,
                        GError       **error)
{
  GObject *object;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  g_assert (source_object != NULL);
  object = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object),
                                        res,
                                        error);
  g_object_unref (source_object);
  if (object != NULL)
    return PHONEUI_DIALER (object);
  else
    return NULL;
}

/**
 * phoneui_dialer_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags used when constructing the proxy.
 * @name: A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Like g_dbus_proxy_new_sync() but returns a #PhoneuiDialerProxy.
 *
 * This is a synchronous failable constructor - the calling thread is blocked until the object is ready. See phoneui_dialer_proxy_new() for the asynchronous version.
 *
 * Returns: A #PhoneuiDialerProxy or %NULL if error is set. Free with g_object_unref().
 */
PhoneuiDialer *phoneui_dialer_proxy_new_sync (GDBusConnection     *connection,
                       GDBusProxyFlags      flags,
                       const gchar         *name,
                       const gchar         *object_path,
                       GCancellable        *cancellable,
                       GError             **error)
{
  GInitable *initable;
  initable = g_initable_new (TYPE_PHONEUI_DIALER_PROXY,
                             cancellable,
                             error,
                             "g-flags", flags,
                             "g-name", name,
                             "g-connection", connection,
                             "g-object-path", object_path,
                             "g-interface-name", "org.shr.phoneui.Dialer",
                             NULL);
  if (initable != NULL)
    return PHONEUI_DIALER (initable);
  else
    return NULL;
}


/**
 * phoneui_dialer_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags used when constructing the proxy.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: A #GCancellable or %NULL.
 * @callback: Callback function to invoke when the proxy is ready.
 * @user_data: User data to pass to @callback.
 *
 * Like g_dbus_proxy_new_for_bus() but returns a #PhoneuiDialerProxy.
 *
 * This is a failable asynchronous constructor - when the proxy is ready, callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this function from. You can then call phoneui_dialer_proxy_new_for_bus_finish() to get the result. See phoneui_dialer_proxy_new_for_bus_sync() for the synchronous version.
 */
void phoneui_dialer_proxy_new_for_bus (GBusType             bus_type,
                           GDBusProxyFlags      flags,
                           const gchar         *name,
                           const gchar         *object_path,
                           GCancellable        *cancellable,
                           GAsyncReadyCallback  callback,
                           gpointer             user_data)
{
  g_async_initable_new_async (TYPE_PHONEUI_DIALER_PROXY,
                              G_PRIORITY_DEFAULT,
                              cancellable,
                              callback,
                              user_data,
                              "g-flags", flags,
                              "g-name", name,
                              "g-bus-type", bus_type,
                              "g-object-path", object_path,
                              "g-interface-name", "org.shr.phoneui.Dialer",
                              NULL);
}

/**
 * phoneui_dialer_proxy_new_for_bus_finish:
 * @res: A #GAsyncResult obtained from the #GAsyncReadyCallback function passed to phoneui_dialer_proxy_new_for_bus().
 * @error: Return location for error or %NULL.
 *
 * Finishes creating a #PhoneuiDialerProxy.
 *
 * Returns: A #PhoneuiDialerProxy or %NULL if @error is set. Free with g_object_unref().
 */
PhoneuiDialer *phoneui_dialer_proxy_new_for_bus_finish (GAsyncResult  *res,
                                GError       **error)
{
  GObject *object;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  g_assert (source_object != NULL);
  object = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object),
                                        res,
                                        error);
  g_object_unref (source_object);
  if (object != NULL)
    return PHONEUI_DIALER (object);
  else
    return NULL;
}

/**
 * phoneui_dialer_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags used when constructing the proxy.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Like g_dbus_proxy_new_for_bus_sync() but returns a #PhoneuiDialerProxy.
 *
 * This is a synchronous failable constructor - the calling thread is blocked until the object is ready. See phoneui_dialer_proxy_new_for_bus() for the asynchronous version.
 *
 * Returns: A #PhoneuiDialerProxy or %NULL if error is set. Free with g_object_unref().
 */
PhoneuiDialer *phoneui_dialer_proxy_new_for_bus_sync (GBusType             bus_type,
                               GDBusProxyFlags      flags,
                               const gchar         *name,
                               const gchar         *object_path,
                               GCancellable        *cancellable,
                               GError             **error)
{
  GInitable *initable;
  initable = g_initable_new (TYPE_PHONEUI_DIALER_PROXY,
                             cancellable,
                             error,
                             "g-flags", flags,
                             "g-name", name,
                             "g-bus-type", bus_type,
                             "g-object-path", object_path,
                             "g-interface-name", "org.shr.phoneui.Dialer",
                             NULL);
  if (initable != NULL)
    return PHONEUI_DIALER (initable);
  else
    return NULL;
}


/* ---------------------------------------------------------------------- */

struct _PhoneuiDialerStubPrivate
{
  GDBusObject *enclosing_object;
  GDBusInterfaceFlags flags;
};

static void stub_iface_init (PhoneuiDialerIface *iface);

G_DEFINE_TYPE_WITH_CODE (PhoneuiDialerStub, phoneui_dialer_stub, G_TYPE_OBJECT,
                         G_IMPLEMENT_INTERFACE (G_TYPE_DBUS_INTERFACE, dbus_iface_init)
                         G_IMPLEMENT_INTERFACE (TYPE_PHONEUI_DIALER, stub_iface_init));

static void
phoneui_dialer_stub_finalize (GObject *object)
{
  G_GNUC_UNUSED PhoneuiDialerStub *stub = (PhoneuiDialerStub *) object;

  if (G_OBJECT_CLASS (phoneui_dialer_stub_parent_class)->finalize != NULL)
    G_OBJECT_CLASS (phoneui_dialer_stub_parent_class)->finalize (object);
}

static void
phoneui_dialer_stub_get_property (GObject      *object,
                      guint         prop_id,
                      GValue       *value,
                      GParamSpec   *pspec)
{
  G_GNUC_UNUSED PhoneuiDialerStub *stub = (PhoneuiDialerStub *) object;
  switch (prop_id)
    {

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, prop_id, pspec);
      break;
    }
}

static void
phoneui_dialer_stub_set_property (GObject      *object,
                      guint         prop_id,
                      const GValue *value,
                      GParamSpec   *pspec)
{
  G_GNUC_UNUSED PhoneuiDialerStub *stub = (PhoneuiDialerStub *) object;
  switch (prop_id)
    {

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, prop_id, pspec);
      break;
    }
}

static void
phoneui_dialer_stub_init (PhoneuiDialerStub *stub)
{
  stub->priv = G_TYPE_INSTANCE_GET_PRIVATE (stub, TYPE_PHONEUI_DIALER_STUB, PhoneuiDialerStubPrivate);
}

static void
phoneui_dialer_stub_class_init (PhoneuiDialerStubClass *klass)
{
  GObjectClass *gobject_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = phoneui_dialer_stub_finalize;
  gobject_class->get_property = phoneui_dialer_stub_get_property;
  gobject_class->set_property = phoneui_dialer_stub_set_property;
  g_type_class_add_private (klass, sizeof (PhoneuiDialerStubPrivate));
}

static void
stub_iface_init (PhoneuiDialerIface *iface)
{
}

/**
 * phoneui_dialer_stub_new:
 *
 * Creates a new stub object that can be exported via g_dbus_interface_register_object().
 *
 * Returns: A #PhoneuiDialerStub instance. Free with g_object_unref().
 */
PhoneuiDialer *
phoneui_dialer_stub_new (void)
{
  return PHONEUI_DIALER (g_object_new (TYPE_PHONEUI_DIALER_STUB, NULL));
}

static GDBusObject *
phoneui_dialer_g_dbus_interface_get_object (GDBusInterface *interface)
{
  PhoneuiDialerStub *stub = G_TYPE_CHECK_INSTANCE_CAST (interface, TYPE_PHONEUI_DIALER_STUB, PhoneuiDialerStub);
  if (stub->priv->enclosing_object != NULL)
    return g_object_ref (stub->priv->enclosing_object);
  else
    return NULL;
}

static void
phoneui_dialer_g_dbus_interface_set_object (GDBusInterface *interface,
                                GDBusObject    *object)
{
  PhoneuiDialerStub *stub = G_TYPE_CHECK_INSTANCE_CAST (interface, TYPE_PHONEUI_DIALER_STUB, PhoneuiDialerStub);
  stub->priv->enclosing_object = object;
}

static GDBusInterfaceFlags
phoneui_dialer_g_dbus_interface_get_flags (GDBusInterface *interface)
{
  PhoneuiDialerStub *stub = G_TYPE_CHECK_INSTANCE_CAST (interface, TYPE_PHONEUI_DIALER_STUB, PhoneuiDialerStub);
  return stub->priv->flags;
}

static void
phoneui_dialer_g_dbus_interface_set_flags (GDBusInterface      *interface,
                               GDBusInterfaceFlags  flags)
{
  PhoneuiDialerStub *stub = G_TYPE_CHECK_INSTANCE_CAST (interface, TYPE_PHONEUI_DIALER_STUB, PhoneuiDialerStub);
  stub->priv->flags = flags;
}

