/*
 * Generated by gdbus-codegen 2.29.3. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __SHR_PHONEUISETTINGS_H__
#define __SHR_PHONEUISETTINGS_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.shr.phoneui.Settings */

#define TYPE_PHONEUI_SETTINGS (phoneui_settings_get_type ())
#define PHONEUI_SETTINGS(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_PHONEUI_SETTINGS, PhoneuiSettings))
#define IS_PHONEUI_SETTINGS(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_PHONEUI_SETTINGS))
#define PHONEUI_SETTINGS_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_PHONEUI_SETTINGS, PhoneuiSettings))

struct _PhoneuiSettings;
typedef struct _PhoneuiSettings PhoneuiSettings;
typedef struct _PhoneuiSettingsIface PhoneuiSettingsIface;

struct _PhoneuiSettingsIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_display_quick_settings) (
    PhoneuiSettings *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_display_sim_manager) (
    PhoneuiSettings *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_message_receipt) (
    PhoneuiSettings *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_set_message_receipt) (
    PhoneuiSettings *object,
    GDBusMethodInvocation *invocation,
    gboolean message_receipt);

};

GType phoneui_settings_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *phoneui_settings_interface_info (void);


/* D-Bus method call completion functions: */
void phoneui_settings_complete_display_quick_settings (
    PhoneuiSettings *object,
    GDBusMethodInvocation *invocation);

void phoneui_settings_complete_display_sim_manager (
    PhoneuiSettings *object,
    GDBusMethodInvocation *invocation);

void phoneui_settings_complete_set_message_receipt (
    PhoneuiSettings *object,
    GDBusMethodInvocation *invocation);

void phoneui_settings_complete_get_message_receipt (
    PhoneuiSettings *object,
    GDBusMethodInvocation *invocation,
    gboolean message_receipt);



/* D-Bus method calls: */
void phoneui_settings_call_display_quick_settings (
    PhoneuiSettings *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean phoneui_settings_call_display_quick_settings_finish (
    PhoneuiSettings *proxy,
    GAsyncResult *res,
    GError **error);

gboolean phoneui_settings_call_display_quick_settings_sync (
    PhoneuiSettings *proxy,
    GCancellable *cancellable,
    GError **error);

void phoneui_settings_call_display_sim_manager (
    PhoneuiSettings *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean phoneui_settings_call_display_sim_manager_finish (
    PhoneuiSettings *proxy,
    GAsyncResult *res,
    GError **error);

gboolean phoneui_settings_call_display_sim_manager_sync (
    PhoneuiSettings *proxy,
    GCancellable *cancellable,
    GError **error);

void phoneui_settings_call_set_message_receipt (
    PhoneuiSettings *proxy,
    gboolean message_receipt,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean phoneui_settings_call_set_message_receipt_finish (
    PhoneuiSettings *proxy,
    GAsyncResult *res,
    GError **error);

gboolean phoneui_settings_call_set_message_receipt_sync (
    PhoneuiSettings *proxy,
    gboolean message_receipt,
    GCancellable *cancellable,
    GError **error);

void phoneui_settings_call_get_message_receipt (
    PhoneuiSettings *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean phoneui_settings_call_get_message_receipt_finish (
    PhoneuiSettings *proxy,
    gboolean *out_message_receipt,
    GAsyncResult *res,
    GError **error);

gboolean phoneui_settings_call_get_message_receipt_sync (
    PhoneuiSettings *proxy,
    gboolean *out_message_receipt,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_PHONEUI_SETTINGS_PROXY (phoneui_settings_proxy_get_type ())
#define PHONEUI_SETTINGS_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_PHONEUI_SETTINGS_PROXY, PhoneuiSettingsProxy))
#define PHONEUI_SETTINGS_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_PHONEUI_SETTINGS_PROXY, PhoneuiSettingsProxyClass))
#define PHONEUI_SETTINGS_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_PHONEUI_SETTINGS_PROXY, PhoneuiSettingsProxyClass))
#define IS_PHONEUI_SETTINGS_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_PHONEUI_SETTINGS_PROXY))
#define IS_PHONEUI_SETTINGS_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_PHONEUI_SETTINGS_PROXY))

typedef struct _PhoneuiSettingsProxy PhoneuiSettingsProxy;
typedef struct _PhoneuiSettingsProxyClass PhoneuiSettingsProxyClass;
typedef struct _PhoneuiSettingsProxyPrivate PhoneuiSettingsProxyPrivate;

struct _PhoneuiSettingsProxy
{
  GDBusProxy parent_instance;
  PhoneuiSettingsProxyPrivate *priv;
};

struct _PhoneuiSettingsProxyClass
{
  GDBusProxyClass parent_class;
};

GType phoneui_settings_proxy_get_type (void) G_GNUC_CONST;

void phoneui_settings_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
PhoneuiSettings *phoneui_settings_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
PhoneuiSettings *phoneui_settings_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void phoneui_settings_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
PhoneuiSettings *phoneui_settings_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
PhoneuiSettings *phoneui_settings_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_PHONEUI_SETTINGS_SKELETON (phoneui_settings_skeleton_get_type ())
#define PHONEUI_SETTINGS_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_PHONEUI_SETTINGS_SKELETON, PhoneuiSettingsSkeleton))
#define PHONEUI_SETTINGS_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_PHONEUI_SETTINGS_SKELETON, PhoneuiSettingsSkeletonClass))
#define PHONEUI_SETTINGS_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_PHONEUI_SETTINGS_SKELETON, PhoneuiSettingsSkeletonClass))
#define IS_PHONEUI_SETTINGS_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_PHONEUI_SETTINGS_SKELETON))
#define IS_PHONEUI_SETTINGS_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_PHONEUI_SETTINGS_SKELETON))

typedef struct _PhoneuiSettingsSkeleton PhoneuiSettingsSkeleton;
typedef struct _PhoneuiSettingsSkeletonClass PhoneuiSettingsSkeletonClass;
typedef struct _PhoneuiSettingsSkeletonPrivate PhoneuiSettingsSkeletonPrivate;

struct _PhoneuiSettingsSkeleton
{
  GDBusInterfaceSkeleton parent_instance;
  PhoneuiSettingsSkeletonPrivate *priv;
};

struct _PhoneuiSettingsSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType phoneui_settings_skeleton_get_type (void) G_GNUC_CONST;

PhoneuiSettings *phoneui_settings_skeleton_new (void);


G_END_DECLS

#endif /* __SHR_PHONEUISETTINGS_H__ */
