/*
 * Generated by gdbus-codegen 2.30.0. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __SHR_PHONEUICONTACTS_H__
#define __SHR_PHONEUICONTACTS_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.shr.phoneui.Contacts */

#define TYPE_PHONEUI_CONTACTS (phoneui_contacts_get_type ())
#define PHONEUI_CONTACTS(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_PHONEUI_CONTACTS, PhoneuiContacts))
#define IS_PHONEUI_CONTACTS(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_PHONEUI_CONTACTS))
#define PHONEUI_CONTACTS_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_PHONEUI_CONTACTS, PhoneuiContactsIface))

struct _PhoneuiContacts;
typedef struct _PhoneuiContacts PhoneuiContacts;
typedef struct _PhoneuiContactsIface PhoneuiContactsIface;

struct _PhoneuiContactsIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_create_contact) (
    PhoneuiContacts *object,
    GDBusMethodInvocation *invocation,
    GVariant *arg_values);

  gboolean (*handle_display_contact) (
    PhoneuiContacts *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_path);

  gboolean (*handle_display_list) (
    PhoneuiContacts *object,
    GDBusMethodInvocation *invocation,
    GVariant *arg_filter);

  gboolean (*handle_edit_contact) (
    PhoneuiContacts *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_path);

};

GType phoneui_contacts_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *phoneui_contacts_interface_info (void);
guint phoneui_contacts_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void phoneui_contacts_complete_display_list (
    PhoneuiContacts *object,
    GDBusMethodInvocation *invocation);

void phoneui_contacts_complete_display_contact (
    PhoneuiContacts *object,
    GDBusMethodInvocation *invocation);

void phoneui_contacts_complete_create_contact (
    PhoneuiContacts *object,
    GDBusMethodInvocation *invocation,
    const gchar *path);

void phoneui_contacts_complete_edit_contact (
    PhoneuiContacts *object,
    GDBusMethodInvocation *invocation);



/* D-Bus method calls: */
void phoneui_contacts_call_display_list (
    PhoneuiContacts *proxy,
    GVariant *arg_filter,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean phoneui_contacts_call_display_list_finish (
    PhoneuiContacts *proxy,
    GAsyncResult *res,
    GError **error);

gboolean phoneui_contacts_call_display_list_sync (
    PhoneuiContacts *proxy,
    GVariant *arg_filter,
    GCancellable *cancellable,
    GError **error);

void phoneui_contacts_call_display_contact (
    PhoneuiContacts *proxy,
    const gchar *arg_path,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean phoneui_contacts_call_display_contact_finish (
    PhoneuiContacts *proxy,
    GAsyncResult *res,
    GError **error);

gboolean phoneui_contacts_call_display_contact_sync (
    PhoneuiContacts *proxy,
    const gchar *arg_path,
    GCancellable *cancellable,
    GError **error);

void phoneui_contacts_call_create_contact (
    PhoneuiContacts *proxy,
    GVariant *arg_values,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean phoneui_contacts_call_create_contact_finish (
    PhoneuiContacts *proxy,
    gchar **out_path,
    GAsyncResult *res,
    GError **error);

gboolean phoneui_contacts_call_create_contact_sync (
    PhoneuiContacts *proxy,
    GVariant *arg_values,
    gchar **out_path,
    GCancellable *cancellable,
    GError **error);

void phoneui_contacts_call_edit_contact (
    PhoneuiContacts *proxy,
    const gchar *arg_path,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean phoneui_contacts_call_edit_contact_finish (
    PhoneuiContacts *proxy,
    GAsyncResult *res,
    GError **error);

gboolean phoneui_contacts_call_edit_contact_sync (
    PhoneuiContacts *proxy,
    const gchar *arg_path,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_PHONEUI_CONTACTS_PROXY (phoneui_contacts_proxy_get_type ())
#define PHONEUI_CONTACTS_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_PHONEUI_CONTACTS_PROXY, PhoneuiContactsProxy))
#define PHONEUI_CONTACTS_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_PHONEUI_CONTACTS_PROXY, PhoneuiContactsProxyClass))
#define PHONEUI_CONTACTS_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_PHONEUI_CONTACTS_PROXY, PhoneuiContactsProxyClass))
#define IS_PHONEUI_CONTACTS_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_PHONEUI_CONTACTS_PROXY))
#define IS_PHONEUI_CONTACTS_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_PHONEUI_CONTACTS_PROXY))

typedef struct _PhoneuiContactsProxy PhoneuiContactsProxy;
typedef struct _PhoneuiContactsProxyClass PhoneuiContactsProxyClass;
typedef struct _PhoneuiContactsProxyPrivate PhoneuiContactsProxyPrivate;

struct _PhoneuiContactsProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  PhoneuiContactsProxyPrivate *priv;
};

struct _PhoneuiContactsProxyClass
{
  GDBusProxyClass parent_class;
};

GType phoneui_contacts_proxy_get_type (void) G_GNUC_CONST;

void phoneui_contacts_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
PhoneuiContacts *phoneui_contacts_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
PhoneuiContacts *phoneui_contacts_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void phoneui_contacts_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
PhoneuiContacts *phoneui_contacts_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
PhoneuiContacts *phoneui_contacts_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_PHONEUI_CONTACTS_SKELETON (phoneui_contacts_skeleton_get_type ())
#define PHONEUI_CONTACTS_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_PHONEUI_CONTACTS_SKELETON, PhoneuiContactsSkeleton))
#define PHONEUI_CONTACTS_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_PHONEUI_CONTACTS_SKELETON, PhoneuiContactsSkeletonClass))
#define PHONEUI_CONTACTS_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_PHONEUI_CONTACTS_SKELETON, PhoneuiContactsSkeletonClass))
#define IS_PHONEUI_CONTACTS_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_PHONEUI_CONTACTS_SKELETON))
#define IS_PHONEUI_CONTACTS_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_PHONEUI_CONTACTS_SKELETON))

typedef struct _PhoneuiContactsSkeleton PhoneuiContactsSkeleton;
typedef struct _PhoneuiContactsSkeletonClass PhoneuiContactsSkeletonClass;
typedef struct _PhoneuiContactsSkeletonPrivate PhoneuiContactsSkeletonPrivate;

struct _PhoneuiContactsSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  PhoneuiContactsSkeletonPrivate *priv;
};

struct _PhoneuiContactsSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType phoneui_contacts_skeleton_get_type (void) G_GNUC_CONST;

PhoneuiContacts *phoneui_contacts_skeleton_new (void);


G_END_DECLS

#endif /* __SHR_PHONEUICONTACTS_H__ */
