/*
 * Generated by gdbus-codegen 2.30.0. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "shr-phoneuimessages.h"

#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        ret = (g_value_get_double (a) == g_value_get_double (b));
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.shr.phoneui.Messages
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:PhoneuiMessages
 * @title: PhoneuiMessages
 * @short_description: Generated C code for the org.shr.phoneui.Messages D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-shr-phoneui-Messages.top_of_page">org.shr.phoneui.Messages</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.shr.phoneui.Messages ---- */

static const _ExtendedGDBusArgInfo _phoneui_messages_method_info_display_list_IN_ARG_filter =
{
  {
    -1,
    "filter",
    "a{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _phoneui_messages_method_info_display_list_IN_ARG_pointers[] =
{
  &_phoneui_messages_method_info_display_list_IN_ARG_filter,
  NULL
};

static const GDBusAnnotationInfo _phoneui_messages_method_display_list_annotation_info_0 =
{
  -1,
  "org.freedesktop.DBus.GLib.Async",
  "true",
  NULL
};

static const GDBusAnnotationInfo * const _phoneui_messages_method_display_list_annotation_info_pointers[] =
{
  &_phoneui_messages_method_display_list_annotation_info_0,
  NULL
};

static const _ExtendedGDBusMethodInfo _phoneui_messages_method_info_display_list =
{
  {
    -1,
    "DisplayList",
    (GDBusArgInfo **) &_phoneui_messages_method_info_display_list_IN_ARG_pointers,
    NULL,
    (GDBusAnnotationInfo **) &_phoneui_messages_method_display_list_annotation_info_pointers
  },
  "handle-display-list",
  FALSE
};

static const _ExtendedGDBusArgInfo _phoneui_messages_method_info_display_message_IN_ARG_path =
{
  {
    -1,
    "path",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _phoneui_messages_method_info_display_message_IN_ARG_pointers[] =
{
  &_phoneui_messages_method_info_display_message_IN_ARG_path,
  NULL
};

static const GDBusAnnotationInfo _phoneui_messages_method_display_message_annotation_info_0 =
{
  -1,
  "org.freedesktop.DBus.GLib.Async",
  "true",
  NULL
};

static const GDBusAnnotationInfo * const _phoneui_messages_method_display_message_annotation_info_pointers[] =
{
  &_phoneui_messages_method_display_message_annotation_info_0,
  NULL
};

static const _ExtendedGDBusMethodInfo _phoneui_messages_method_info_display_message =
{
  {
    -1,
    "DisplayMessage",
    (GDBusArgInfo **) &_phoneui_messages_method_info_display_message_IN_ARG_pointers,
    NULL,
    (GDBusAnnotationInfo **) &_phoneui_messages_method_display_message_annotation_info_pointers
  },
  "handle-display-message",
  FALSE
};

static const _ExtendedGDBusArgInfo _phoneui_messages_method_info_create_message_IN_ARG_values =
{
  {
    -1,
    "values",
    "a{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _phoneui_messages_method_info_create_message_IN_ARG_pointers[] =
{
  &_phoneui_messages_method_info_create_message_IN_ARG_values,
  NULL
};

static const GDBusAnnotationInfo _phoneui_messages_method_create_message_annotation_info_0 =
{
  -1,
  "org.freedesktop.DBus.GLib.Async",
  "true",
  NULL
};

static const GDBusAnnotationInfo * const _phoneui_messages_method_create_message_annotation_info_pointers[] =
{
  &_phoneui_messages_method_create_message_annotation_info_0,
  NULL
};

static const _ExtendedGDBusMethodInfo _phoneui_messages_method_info_create_message =
{
  {
    -1,
    "CreateMessage",
    (GDBusArgInfo **) &_phoneui_messages_method_info_create_message_IN_ARG_pointers,
    NULL,
    (GDBusAnnotationInfo **) &_phoneui_messages_method_create_message_annotation_info_pointers
  },
  "handle-create-message",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _phoneui_messages_method_info_pointers[] =
{
  &_phoneui_messages_method_info_display_list,
  &_phoneui_messages_method_info_display_message,
  &_phoneui_messages_method_info_create_message,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _phoneui_messages_interface_info =
{
  {
    -1,
    "org.shr.phoneui.Messages",
    (GDBusMethodInfo **) &_phoneui_messages_method_info_pointers,
    NULL,
    NULL,
    NULL
  },
  "phoneui-messages",
};


/**
 * phoneui_messages_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-shr-phoneui-Messages.top_of_page">org.shr.phoneui.Messages</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
phoneui_messages_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_phoneui_messages_interface_info;
}

/**
 * phoneui_messages_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #PhoneuiMessages interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
phoneui_messages_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * PhoneuiMessages:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-shr-phoneui-Messages.top_of_page">org.shr.phoneui.Messages</link>.
 */

/**
 * PhoneuiMessagesIface:
 * @parent_iface: The parent interface.
 * @handle_create_message: Handler for the #PhoneuiMessages::handle-create-message signal.
 * @handle_display_list: Handler for the #PhoneuiMessages::handle-display-list signal.
 * @handle_display_message: Handler for the #PhoneuiMessages::handle-display-message signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-shr-phoneui-Messages.top_of_page">org.shr.phoneui.Messages</link>.
 */

static void
phoneui_messages_default_init (PhoneuiMessagesIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * PhoneuiMessages::handle-display-list:
   * @object: A #PhoneuiMessages.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_filter: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-shr-phoneui-Messages.DisplayList">DisplayList()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call phoneui_messages_complete_display_list() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-display-list",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (PhoneuiMessagesIface, handle_display_list),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_VARIANT);

  /**
   * PhoneuiMessages::handle-display-message:
   * @object: A #PhoneuiMessages.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_path: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-shr-phoneui-Messages.DisplayMessage">DisplayMessage()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call phoneui_messages_complete_display_message() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-display-message",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (PhoneuiMessagesIface, handle_display_message),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * PhoneuiMessages::handle-create-message:
   * @object: A #PhoneuiMessages.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_values: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-shr-phoneui-Messages.CreateMessage">CreateMessage()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call phoneui_messages_complete_create_message() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-create-message",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (PhoneuiMessagesIface, handle_create_message),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_VARIANT);

}

typedef PhoneuiMessagesIface PhoneuiMessagesInterface;
G_DEFINE_INTERFACE (PhoneuiMessages, phoneui_messages, G_TYPE_OBJECT);

/**
 * phoneui_messages_call_display_list:
 * @proxy: A #PhoneuiMessagesProxy.
 * @arg_filter: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-shr-phoneui-Messages.DisplayList">DisplayList()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call phoneui_messages_call_display_list_finish() to get the result of the operation.
 *
 * See phoneui_messages_call_display_list_sync() for the synchronous, blocking version of this method.
 */
void
phoneui_messages_call_display_list (
    PhoneuiMessages *proxy,
    GVariant *arg_filter,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "DisplayList",
    g_variant_new ("(@a{sv})",
                   arg_filter),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * phoneui_messages_call_display_list_finish:
 * @proxy: A #PhoneuiMessagesProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to phoneui_messages_call_display_list().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with phoneui_messages_call_display_list().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
phoneui_messages_call_display_list_finish (
    PhoneuiMessages *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * phoneui_messages_call_display_list_sync:
 * @proxy: A #PhoneuiMessagesProxy.
 * @arg_filter: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-shr-phoneui-Messages.DisplayList">DisplayList()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See phoneui_messages_call_display_list() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
phoneui_messages_call_display_list_sync (
    PhoneuiMessages *proxy,
    GVariant *arg_filter,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "DisplayList",
    g_variant_new ("(@a{sv})",
                   arg_filter),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * phoneui_messages_call_display_message:
 * @proxy: A #PhoneuiMessagesProxy.
 * @arg_path: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-shr-phoneui-Messages.DisplayMessage">DisplayMessage()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call phoneui_messages_call_display_message_finish() to get the result of the operation.
 *
 * See phoneui_messages_call_display_message_sync() for the synchronous, blocking version of this method.
 */
void
phoneui_messages_call_display_message (
    PhoneuiMessages *proxy,
    const gchar *arg_path,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "DisplayMessage",
    g_variant_new ("(s)",
                   arg_path),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * phoneui_messages_call_display_message_finish:
 * @proxy: A #PhoneuiMessagesProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to phoneui_messages_call_display_message().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with phoneui_messages_call_display_message().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
phoneui_messages_call_display_message_finish (
    PhoneuiMessages *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * phoneui_messages_call_display_message_sync:
 * @proxy: A #PhoneuiMessagesProxy.
 * @arg_path: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-shr-phoneui-Messages.DisplayMessage">DisplayMessage()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See phoneui_messages_call_display_message() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
phoneui_messages_call_display_message_sync (
    PhoneuiMessages *proxy,
    const gchar *arg_path,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "DisplayMessage",
    g_variant_new ("(s)",
                   arg_path),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * phoneui_messages_call_create_message:
 * @proxy: A #PhoneuiMessagesProxy.
 * @arg_values: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-shr-phoneui-Messages.CreateMessage">CreateMessage()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call phoneui_messages_call_create_message_finish() to get the result of the operation.
 *
 * See phoneui_messages_call_create_message_sync() for the synchronous, blocking version of this method.
 */
void
phoneui_messages_call_create_message (
    PhoneuiMessages *proxy,
    GVariant *arg_values,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "CreateMessage",
    g_variant_new ("(@a{sv})",
                   arg_values),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * phoneui_messages_call_create_message_finish:
 * @proxy: A #PhoneuiMessagesProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to phoneui_messages_call_create_message().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with phoneui_messages_call_create_message().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
phoneui_messages_call_create_message_finish (
    PhoneuiMessages *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * phoneui_messages_call_create_message_sync:
 * @proxy: A #PhoneuiMessagesProxy.
 * @arg_values: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-shr-phoneui-Messages.CreateMessage">CreateMessage()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See phoneui_messages_call_create_message() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
phoneui_messages_call_create_message_sync (
    PhoneuiMessages *proxy,
    GVariant *arg_values,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "CreateMessage",
    g_variant_new ("(@a{sv})",
                   arg_values),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * phoneui_messages_complete_display_list:
 * @object: A #PhoneuiMessages.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-shr-phoneui-Messages.DisplayList">DisplayList()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
phoneui_messages_complete_display_list (
    PhoneuiMessages *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * phoneui_messages_complete_display_message:
 * @object: A #PhoneuiMessages.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-shr-phoneui-Messages.DisplayMessage">DisplayMessage()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
phoneui_messages_complete_display_message (
    PhoneuiMessages *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * phoneui_messages_complete_create_message:
 * @object: A #PhoneuiMessages.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-shr-phoneui-Messages.CreateMessage">CreateMessage()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
phoneui_messages_complete_create_message (
    PhoneuiMessages *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * PhoneuiMessagesProxy:
 *
 * The #PhoneuiMessagesProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * PhoneuiMessagesProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #PhoneuiMessagesProxy.
 */

struct _PhoneuiMessagesProxyPrivate
{
  GData *qdata;
};

static void phoneui_messages_proxy_iface_init (PhoneuiMessagesIface *iface);

G_DEFINE_TYPE_WITH_CODE (PhoneuiMessagesProxy, phoneui_messages_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_PHONEUI_MESSAGES, phoneui_messages_proxy_iface_init));

static void
phoneui_messages_proxy_finalize (GObject *object)
{
  PhoneuiMessagesProxy *proxy = PHONEUI_MESSAGES_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (phoneui_messages_proxy_parent_class)->finalize (object);
}

static void
phoneui_messages_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
}

static void
phoneui_messages_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
}

static void
phoneui_messages_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_phoneui_messages_interface_info, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TYPE_PHONEUI_MESSAGES);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_PHONEUI_MESSAGES);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
phoneui_messages_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  PhoneuiMessagesProxy *proxy = PHONEUI_MESSAGES_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_phoneui_messages_interface_info, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_phoneui_messages_interface_info, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
phoneui_messages_proxy_init (PhoneuiMessagesProxy *proxy)
{
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, TYPE_PHONEUI_MESSAGES_PROXY, PhoneuiMessagesProxyPrivate);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), phoneui_messages_interface_info ());
}

static void
phoneui_messages_proxy_class_init (PhoneuiMessagesProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  g_type_class_add_private (klass, sizeof (PhoneuiMessagesProxyPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = phoneui_messages_proxy_finalize;
  gobject_class->get_property = phoneui_messages_proxy_get_property;
  gobject_class->set_property = phoneui_messages_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = phoneui_messages_proxy_g_signal;
  proxy_class->g_properties_changed = phoneui_messages_proxy_g_properties_changed;

}

static void
phoneui_messages_proxy_iface_init (PhoneuiMessagesIface *iface)
{
}

/**
 * phoneui_messages_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-shr-phoneui-Messages.top_of_page">org.shr.phoneui.Messages</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call phoneui_messages_proxy_new_finish() to get the result of the operation.
 *
 * See phoneui_messages_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
phoneui_messages_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_PHONEUI_MESSAGES_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.shr.phoneui.Messages", NULL);
}

/**
 * phoneui_messages_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to phoneui_messages_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with phoneui_messages_proxy_new().
 *
 * Returns: (transfer full) (type PhoneuiMessagesProxy): The constructed proxy object or %NULL if @error is set.
 */
PhoneuiMessages *
phoneui_messages_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return PHONEUI_MESSAGES (ret);
  else
    return NULL;
}

/**
 * phoneui_messages_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-shr-phoneui-Messages.top_of_page">org.shr.phoneui.Messages</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See phoneui_messages_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type PhoneuiMessagesProxy): The constructed proxy object or %NULL if @error is set.
 */
PhoneuiMessages *
phoneui_messages_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_PHONEUI_MESSAGES_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.shr.phoneui.Messages", NULL);
  if (ret != NULL)
    return PHONEUI_MESSAGES (ret);
  else
    return NULL;
}


/**
 * phoneui_messages_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like phoneui_messages_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call phoneui_messages_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See phoneui_messages_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
phoneui_messages_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_PHONEUI_MESSAGES_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.shr.phoneui.Messages", NULL);
}

/**
 * phoneui_messages_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to phoneui_messages_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with phoneui_messages_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type PhoneuiMessagesProxy): The constructed proxy object or %NULL if @error is set.
 */
PhoneuiMessages *
phoneui_messages_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return PHONEUI_MESSAGES (ret);
  else
    return NULL;
}

/**
 * phoneui_messages_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like phoneui_messages_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See phoneui_messages_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type PhoneuiMessagesProxy): The constructed proxy object or %NULL if @error is set.
 */
PhoneuiMessages *
phoneui_messages_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_PHONEUI_MESSAGES_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.shr.phoneui.Messages", NULL);
  if (ret != NULL)
    return PHONEUI_MESSAGES (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * PhoneuiMessagesSkeleton:
 *
 * The #PhoneuiMessagesSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * PhoneuiMessagesSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #PhoneuiMessagesSkeleton.
 */

struct _PhoneuiMessagesSkeletonPrivate
{
  GValueArray *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex *lock;
};

static void
_phoneui_messages_skeleton_handle_method_call (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  PhoneuiMessagesSkeleton *skeleton = PHONEUI_MESSAGES_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = {0};
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TYPE_PHONEUI_MESSAGES);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_PHONEUI_MESSAGES);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_phoneui_messages_skeleton_handle_get_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  PhoneuiMessagesSkeleton *skeleton = PHONEUI_MESSAGES_SKELETON (user_data);
  GValue value = {0};
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_phoneui_messages_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_phoneui_messages_skeleton_handle_set_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  PhoneuiMessagesSkeleton *skeleton = PHONEUI_MESSAGES_SKELETON (user_data);
  GValue value = {0};
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_phoneui_messages_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _phoneui_messages_skeleton_vtable =
{
  _phoneui_messages_skeleton_handle_method_call,
  _phoneui_messages_skeleton_handle_get_property,
  _phoneui_messages_skeleton_handle_set_property
};

static GDBusInterfaceInfo *
phoneui_messages_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton)
{
  return phoneui_messages_interface_info ();
}

static GDBusInterfaceVTable *
phoneui_messages_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton)
{
  return (GDBusInterfaceVTable *) &_phoneui_messages_skeleton_vtable;
}

static GVariant *
phoneui_messages_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  PhoneuiMessagesSkeleton *skeleton = PHONEUI_MESSAGES_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_phoneui_messages_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _phoneui_messages_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _phoneui_messages_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _phoneui_messages_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.shr.phoneui.Messages", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
phoneui_messages_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void phoneui_messages_skeleton_iface_init (PhoneuiMessagesIface *iface);
G_DEFINE_TYPE_WITH_CODE (PhoneuiMessagesSkeleton, phoneui_messages_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TYPE_PHONEUI_MESSAGES, phoneui_messages_skeleton_iface_init));

static void
phoneui_messages_skeleton_finalize (GObject *object)
{
  PhoneuiMessagesSkeleton *skeleton = PHONEUI_MESSAGES_SKELETON (object);
  g_list_foreach (skeleton->priv->changed_properties, (GFunc) _changed_property_free, NULL);
  g_list_free (skeleton->priv->changed_properties);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  if (skeleton->priv->context != NULL)
    g_main_context_unref (skeleton->priv->context);
  g_mutex_free (skeleton->priv->lock);
  G_OBJECT_CLASS (phoneui_messages_skeleton_parent_class)->finalize (object);
}

static void
phoneui_messages_skeleton_init (PhoneuiMessagesSkeleton *skeleton)
{
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TYPE_PHONEUI_MESSAGES_SKELETON, PhoneuiMessagesSkeletonPrivate);
  skeleton->priv->lock = g_mutex_new ();
  skeleton->priv->context = g_main_context_get_thread_default ();
  if (skeleton->priv->context != NULL)
    g_main_context_ref (skeleton->priv->context);
}

static void
phoneui_messages_skeleton_class_init (PhoneuiMessagesSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  g_type_class_add_private (klass, sizeof (PhoneuiMessagesSkeletonPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = phoneui_messages_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = phoneui_messages_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = phoneui_messages_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = phoneui_messages_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = phoneui_messages_skeleton_dbus_interface_get_vtable;
}

static void
phoneui_messages_skeleton_iface_init (PhoneuiMessagesIface *iface)
{
}

/**
 * phoneui_messages_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-shr-phoneui-Messages.top_of_page">org.shr.phoneui.Messages</link>.
 *
 * Returns: (transfer full) (type PhoneuiMessagesSkeleton): The skeleton object.
 */
PhoneuiMessages *
phoneui_messages_skeleton_new (void)
{
  return PHONEUI_MESSAGES (g_object_new (TYPE_PHONEUI_MESSAGES_SKELETON, NULL));
}

