/*
 * Generated by gdbus-codegen 2.29.3. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __SHR_PHONEUICALLMANAGEMENT_H__
#define __SHR_PHONEUICALLMANAGEMENT_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.shr.phoneui.CallManagement */

#define TYPE_PHONEUI_CALL_MANAGEMENT (phoneui_call_management_get_type ())
#define PHONEUI_CALL_MANAGEMENT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_PHONEUI_CALL_MANAGEMENT, PhoneuiCallManagement))
#define IS_PHONEUI_CALL_MANAGEMENT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_PHONEUI_CALL_MANAGEMENT))
#define PHONEUI_CALL_MANAGEMENT_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_PHONEUI_CALL_MANAGEMENT, PhoneuiCallManagement))

struct _PhoneuiCallManagement;
typedef struct _PhoneuiCallManagement PhoneuiCallManagement;
typedef struct _PhoneuiCallManagementIface PhoneuiCallManagementIface;

struct _PhoneuiCallManagementIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_display_incoming) (
    PhoneuiCallManagement *object,
    GDBusMethodInvocation *invocation,
    gint call_id,
    gint status,
    const gchar *number);

  gboolean (*handle_display_outgoing) (
    PhoneuiCallManagement *object,
    GDBusMethodInvocation *invocation,
    gint call_id,
    gint status,
    const gchar *number);

  gboolean (*handle_hide_incoming) (
    PhoneuiCallManagement *object,
    GDBusMethodInvocation *invocation,
    gint call_id);

  gboolean (*handle_hide_outgoing) (
    PhoneuiCallManagement *object,
    GDBusMethodInvocation *invocation,
    gint call_id);

};

GType phoneui_call_management_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *phoneui_call_management_interface_info (void);


/* D-Bus method call completion functions: */
void phoneui_call_management_complete_display_incoming (
    PhoneuiCallManagement *object,
    GDBusMethodInvocation *invocation);

void phoneui_call_management_complete_hide_incoming (
    PhoneuiCallManagement *object,
    GDBusMethodInvocation *invocation);

void phoneui_call_management_complete_display_outgoing (
    PhoneuiCallManagement *object,
    GDBusMethodInvocation *invocation);

void phoneui_call_management_complete_hide_outgoing (
    PhoneuiCallManagement *object,
    GDBusMethodInvocation *invocation);



/* D-Bus method calls: */
void phoneui_call_management_call_display_incoming (
    PhoneuiCallManagement *proxy,
    gint call_id,
    gint status,
    const gchar *number,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean phoneui_call_management_call_display_incoming_finish (
    PhoneuiCallManagement *proxy,
    GAsyncResult *res,
    GError **error);

gboolean phoneui_call_management_call_display_incoming_sync (
    PhoneuiCallManagement *proxy,
    gint call_id,
    gint status,
    const gchar *number,
    GCancellable *cancellable,
    GError **error);

void phoneui_call_management_call_hide_incoming (
    PhoneuiCallManagement *proxy,
    gint call_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean phoneui_call_management_call_hide_incoming_finish (
    PhoneuiCallManagement *proxy,
    GAsyncResult *res,
    GError **error);

gboolean phoneui_call_management_call_hide_incoming_sync (
    PhoneuiCallManagement *proxy,
    gint call_id,
    GCancellable *cancellable,
    GError **error);

void phoneui_call_management_call_display_outgoing (
    PhoneuiCallManagement *proxy,
    gint call_id,
    gint status,
    const gchar *number,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean phoneui_call_management_call_display_outgoing_finish (
    PhoneuiCallManagement *proxy,
    GAsyncResult *res,
    GError **error);

gboolean phoneui_call_management_call_display_outgoing_sync (
    PhoneuiCallManagement *proxy,
    gint call_id,
    gint status,
    const gchar *number,
    GCancellable *cancellable,
    GError **error);

void phoneui_call_management_call_hide_outgoing (
    PhoneuiCallManagement *proxy,
    gint call_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean phoneui_call_management_call_hide_outgoing_finish (
    PhoneuiCallManagement *proxy,
    GAsyncResult *res,
    GError **error);

gboolean phoneui_call_management_call_hide_outgoing_sync (
    PhoneuiCallManagement *proxy,
    gint call_id,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_PHONEUI_CALL_MANAGEMENT_PROXY (phoneui_call_management_proxy_get_type ())
#define PHONEUI_CALL_MANAGEMENT_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_PHONEUI_CALL_MANAGEMENT_PROXY, PhoneuiCallManagementProxy))
#define PHONEUI_CALL_MANAGEMENT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_PHONEUI_CALL_MANAGEMENT_PROXY, PhoneuiCallManagementProxyClass))
#define PHONEUI_CALL_MANAGEMENT_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_PHONEUI_CALL_MANAGEMENT_PROXY, PhoneuiCallManagementProxyClass))
#define IS_PHONEUI_CALL_MANAGEMENT_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_PHONEUI_CALL_MANAGEMENT_PROXY))
#define IS_PHONEUI_CALL_MANAGEMENT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_PHONEUI_CALL_MANAGEMENT_PROXY))

typedef struct _PhoneuiCallManagementProxy PhoneuiCallManagementProxy;
typedef struct _PhoneuiCallManagementProxyClass PhoneuiCallManagementProxyClass;
typedef struct _PhoneuiCallManagementProxyPrivate PhoneuiCallManagementProxyPrivate;

struct _PhoneuiCallManagementProxy
{
  GDBusProxy parent_instance;
  PhoneuiCallManagementProxyPrivate *priv;
};

struct _PhoneuiCallManagementProxyClass
{
  GDBusProxyClass parent_class;
};

GType phoneui_call_management_proxy_get_type (void) G_GNUC_CONST;

void phoneui_call_management_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
PhoneuiCallManagement *phoneui_call_management_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
PhoneuiCallManagement *phoneui_call_management_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void phoneui_call_management_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
PhoneuiCallManagement *phoneui_call_management_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
PhoneuiCallManagement *phoneui_call_management_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_PHONEUI_CALL_MANAGEMENT_SKELETON (phoneui_call_management_skeleton_get_type ())
#define PHONEUI_CALL_MANAGEMENT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_PHONEUI_CALL_MANAGEMENT_SKELETON, PhoneuiCallManagementSkeleton))
#define PHONEUI_CALL_MANAGEMENT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_PHONEUI_CALL_MANAGEMENT_SKELETON, PhoneuiCallManagementSkeletonClass))
#define PHONEUI_CALL_MANAGEMENT_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_PHONEUI_CALL_MANAGEMENT_SKELETON, PhoneuiCallManagementSkeletonClass))
#define IS_PHONEUI_CALL_MANAGEMENT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_PHONEUI_CALL_MANAGEMENT_SKELETON))
#define IS_PHONEUI_CALL_MANAGEMENT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_PHONEUI_CALL_MANAGEMENT_SKELETON))

typedef struct _PhoneuiCallManagementSkeleton PhoneuiCallManagementSkeleton;
typedef struct _PhoneuiCallManagementSkeletonClass PhoneuiCallManagementSkeletonClass;
typedef struct _PhoneuiCallManagementSkeletonPrivate PhoneuiCallManagementSkeletonPrivate;

struct _PhoneuiCallManagementSkeleton
{
  GDBusInterfaceSkeleton parent_instance;
  PhoneuiCallManagementSkeletonPrivate *priv;
};

struct _PhoneuiCallManagementSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType phoneui_call_management_skeleton_get_type (void) G_GNUC_CONST;

PhoneuiCallManagement *phoneui_call_management_skeleton_new (void);


G_END_DECLS

#endif /* __SHR_PHONEUICALLMANAGEMENT_H__ */
