/* File:       shr-phonefsousage.c
 *
 * GType name: PhonefsoUsage
 * D-Bus name: org.shr.phonefso.Usage
 *
 * Generated by GDBus Binding Tool 0.1. DO NOT EDIT.
 */

/**
 * SECTION:shr-phonefsousage
 * @title: PhonefsoUsage
 * @short_description: Wraps the org.shr.phonefso.Usage D-Bus interface
 * @include: gio/gio.h
 *
 * The abstract #PhonefsoUsage interface type wraps the <literal>org.shr.phonefso.Usage</literal> D-Bus interface. Two concrete implementations exists: #PhonefsoUsageProxy (for client-side usage) and #PhonefsoUsageStub (for service-side usage).
 *
 * This code was generated from the following D-Bus introspection XML:
 * <programlisting><![CDATA[
 * <interface name="org.shr.phonefso.Usage">
 *   <method name="SetOfflineMode">
 *     <annotation name="org.freedesktop.DBus.GLib.Async" value="true">
 *     </annotation>
 *     <arg type="b" name="state" direction="in">
 *     </arg>
 *   </method>
 *   <method name="GetOfflineMode">
 *     <annotation name="org.freedesktop.DBus.GLib.Async" value="true">
 *     </annotation>
 *     <arg type="b" name="state" direction="out">
 *     </arg>
 *   </method>
 *   <method name="SetDefaultBrightness">
 *     <annotation name="org.freedesktop.DBus.GLib.Async" value="true">
 *     </annotation>
 *     <arg type="i" name="brightness" direction="in">
 *     </arg>
 *   </method>
 *   <method name="GetDefaultBrightness">
 *     <annotation name="org.freedesktop.DBus.GLib.Async" value="true">
 *     </annotation>
 *     <arg type="i" name="brightness" direction="out">
 *     </arg>
 *   </method>
 *   <method name="SetPdpCredentials">
 *     <annotation name="org.freedesktop.DBus.GLib.Async" value="true">
 *     </annotation>
 *     <arg type="s" name="apn" direction="in">
 *     </arg>
 *     <arg type="s" name="user" direction="in">
 *     </arg>
 *     <arg type="s" name="password" direction="in">
 *     </arg>
 *   </method>
 *   <method name="SetPin">
 *     <annotation name="org.freedesktop.DBus.GLib.Async" value="true">
 *     </annotation>
 *     <arg type="s" name="pin" direction="in">
 *     </arg>
 *   </method>
 * </interface>
 * ]]></programlisting>
 *
 */

#include <shr-phonefsousage.h>
#include <shr-types.h>
#include <shr-bindingsprivate.h>
#include <shr-marshallers.h>

static guint phonefso_usage_register_object (GDBusInterface *object,
                    GDBusConnection *connection,
                    const gchar *object_path,
                    GError **error);
static void phonefso_usage_flush (GDBusInterface *object);
static GVariant *phonefso_usage_get_properties (GDBusInterface *object);
static GDBusInterfaceInfo *phonefso_usage_g_dbus_interface_interface_info (GDBusInterface *object);
static GDBusObject *phonefso_usage_g_dbus_interface_get_object (GDBusInterface *interface);
static void phonefso_usage_g_dbus_interface_set_object (GDBusInterface *interface, GDBusObject *object);
static GDBusInterfaceFlags phonefso_usage_g_dbus_interface_get_flags (GDBusInterface *interface);
static void phonefso_usage_g_dbus_interface_set_flags (GDBusInterface *interface, GDBusInterfaceFlags flags);

typedef PhonefsoUsageIface PhonefsoUsageInterface;
#define phonefso_usage_get_type phonefso_usage_get_gtype
G_DEFINE_INTERFACE (PhonefsoUsage, phonefso_usage, G_TYPE_OBJECT);
#undef phonefso_usage_get_type


enum
{
  _0_SIGNAL,
  __SET_OFFLINE_MODE_METHOD,
  __GET_OFFLINE_MODE_METHOD,
  __SET_DEFAULT_BRIGHTNESS_METHOD,
  __GET_DEFAULT_BRIGHTNESS_METHOD,
  __SET_PDP_CREDENTIALS_METHOD,
  __SET_PIN_METHOD,
  __LAST_SIGNAL
};

static guint signals[__LAST_SIGNAL] = {0};


enum
{
  PROP_0,
};

/* ------------------------------------------------------------------------- */

/* Various lookup tables */

static GHashTable *_method_name_to_id = NULL;
static GHashTable *_signal_name_to_id = NULL;
static GHashTable *_property_name_to_id = NULL;
static GHashTable *_property_gname_to_name = NULL;
static GHashTable *_property_name_to_gname = NULL;


static guint
lookup_method_id_from_method_name (const gchar *method_name)
{
  return GPOINTER_TO_UINT (g_hash_table_lookup (_method_name_to_id, method_name));
}

static guint
lookup_signal_id_from_signal_name (const gchar *signal_name)
{
  return GPOINTER_TO_UINT (g_hash_table_lookup (_signal_name_to_id, signal_name));
}

static guint
lookup_property_id_from_property_name (const gchar *property_name)
{
  return GPOINTER_TO_UINT (g_hash_table_lookup (_property_name_to_id, property_name));
}

static const gchar *
lookup_property_name_from_property_gname (const gchar *property_gname)
{
  return g_hash_table_lookup (_property_gname_to_name, property_gname);
}

static const gchar *
lookup_property_gname_from_property_name (const gchar *property_name)
{
  return g_hash_table_lookup (_property_name_to_gname, property_name);
}

/* ------------------------------------------------------------------------- */
static void dbus_iface_init (GDBusInterfaceIface *iface)
{
  iface->get_info = phonefso_usage_g_dbus_interface_interface_info;
  iface->get_properties = phonefso_usage_get_properties;
  iface->flush = phonefso_usage_flush;
  iface->register_object = phonefso_usage_register_object;
  iface->set_object = phonefso_usage_g_dbus_interface_set_object;
  iface->get_object = phonefso_usage_g_dbus_interface_get_object;
  iface->set_flags = phonefso_usage_g_dbus_interface_set_flags;
  iface->get_flags = phonefso_usage_g_dbus_interface_get_flags;
}

static void
phonefso_usage_default_init (PhonefsoUsageIface *iface)
{

  /* Build lookup structures */
  _method_name_to_id = g_hash_table_new (g_str_hash, g_str_equal);
  _signal_name_to_id = g_hash_table_new (g_str_hash, g_str_equal);
  _property_name_to_id = g_hash_table_new (g_str_hash, g_str_equal);
  _property_gname_to_name = g_hash_table_new (g_str_hash, g_str_equal);
  _property_name_to_gname = g_hash_table_new (g_str_hash, g_str_equal);
  g_hash_table_insert (_method_name_to_id, "SetOfflineMode", GUINT_TO_POINTER (__SET_OFFLINE_MODE_METHOD));
  g_hash_table_insert (_method_name_to_id, "GetOfflineMode", GUINT_TO_POINTER (__GET_OFFLINE_MODE_METHOD));
  g_hash_table_insert (_method_name_to_id, "SetDefaultBrightness", GUINT_TO_POINTER (__SET_DEFAULT_BRIGHTNESS_METHOD));
  g_hash_table_insert (_method_name_to_id, "GetDefaultBrightness", GUINT_TO_POINTER (__GET_DEFAULT_BRIGHTNESS_METHOD));
  g_hash_table_insert (_method_name_to_id, "SetPdpCredentials", GUINT_TO_POINTER (__SET_PDP_CREDENTIALS_METHOD));
  g_hash_table_insert (_method_name_to_id, "SetPin", GUINT_TO_POINTER (__SET_PIN_METHOD));

  /* GObject signals definitions for D-Bus signals: */

  /* GObject signals definitions for D-Bus methods: */
  /**
   * PhonefsoUsage::handle-set-offline-mode:
   * @object: The exported object emitting the signal.
   * @invocation: A #GDBusMethodInvocation object that can be used to return a value or error.
   * @state: Parameter.
   *
   * On exported objects, this signal is emitted when a remote process (identified by @invocation) invokes the <literal>org.shr.phonefso.Usage.SetOfflineMode()</literal> D-Bus method on @object. Use phonefso_usage_complete_set_offline_mode() to return a value or g_dbus_method_invocation_return_error() to return an error.
   *
   * The signal is emitted in the
   * <link linkend="g-main-context-push-thread-default">thread-default main loop</link>
   * of the thread that @object was registered in.
   *
   * On proxies, this signal is never emitted.
   *
   * Returns: %TRUE if you want to handle the method call (will stop further handlers from being called), %FALSE otherwise.
   */
  signals[__SET_OFFLINE_MODE_METHOD] =
    g_signal_new ("handle-set-offline-mode",
                  G_TYPE_FROM_INTERFACE (iface),
                  G_SIGNAL_RUN_LAST,
                  G_STRUCT_OFFSET (PhonefsoUsageIface, handle_set_offline_mode),
                  g_signal_accumulator_true_handled,
                  NULL,
                  _shr_gdbus_cclosure_marshaller_BOOLEAN__OBJECT_BOOLEAN,
                  G_TYPE_BOOLEAN,
                  2,
                  G_TYPE_DBUS_METHOD_INVOCATION,
                  G_TYPE_BOOLEAN);
  /**
   * PhonefsoUsage::handle-get-offline-mode:
   * @object: The exported object emitting the signal.
   * @invocation: A #GDBusMethodInvocation object that can be used to return a value or error.
   *
   * On exported objects, this signal is emitted when a remote process (identified by @invocation) invokes the <literal>org.shr.phonefso.Usage.GetOfflineMode()</literal> D-Bus method on @object. Use phonefso_usage_complete_get_offline_mode() to return a value or g_dbus_method_invocation_return_error() to return an error.
   *
   * The signal is emitted in the
   * <link linkend="g-main-context-push-thread-default">thread-default main loop</link>
   * of the thread that @object was registered in.
   *
   * On proxies, this signal is never emitted.
   *
   * Returns: %TRUE if you want to handle the method call (will stop further handlers from being called), %FALSE otherwise.
   */
  signals[__GET_OFFLINE_MODE_METHOD] =
    g_signal_new ("handle-get-offline-mode",
                  G_TYPE_FROM_INTERFACE (iface),
                  G_SIGNAL_RUN_LAST,
                  G_STRUCT_OFFSET (PhonefsoUsageIface, handle_get_offline_mode),
                  g_signal_accumulator_true_handled,
                  NULL,
                  _shr_gdbus_cclosure_marshaller_BOOLEAN__OBJECT,
                  G_TYPE_BOOLEAN,
                  1,
                  G_TYPE_DBUS_METHOD_INVOCATION);
  /**
   * PhonefsoUsage::handle-set-default-brightness:
   * @object: The exported object emitting the signal.
   * @invocation: A #GDBusMethodInvocation object that can be used to return a value or error.
   * @brightness: Parameter.
   *
   * On exported objects, this signal is emitted when a remote process (identified by @invocation) invokes the <literal>org.shr.phonefso.Usage.SetDefaultBrightness()</literal> D-Bus method on @object. Use phonefso_usage_complete_set_default_brightness() to return a value or g_dbus_method_invocation_return_error() to return an error.
   *
   * The signal is emitted in the
   * <link linkend="g-main-context-push-thread-default">thread-default main loop</link>
   * of the thread that @object was registered in.
   *
   * On proxies, this signal is never emitted.
   *
   * Returns: %TRUE if you want to handle the method call (will stop further handlers from being called), %FALSE otherwise.
   */
  signals[__SET_DEFAULT_BRIGHTNESS_METHOD] =
    g_signal_new ("handle-set-default-brightness",
                  G_TYPE_FROM_INTERFACE (iface),
                  G_SIGNAL_RUN_LAST,
                  G_STRUCT_OFFSET (PhonefsoUsageIface, handle_set_default_brightness),
                  g_signal_accumulator_true_handled,
                  NULL,
                  _shr_gdbus_cclosure_marshaller_BOOLEAN__OBJECT_INT,
                  G_TYPE_BOOLEAN,
                  2,
                  G_TYPE_DBUS_METHOD_INVOCATION,
                  G_TYPE_INT);
  /**
   * PhonefsoUsage::handle-get-default-brightness:
   * @object: The exported object emitting the signal.
   * @invocation: A #GDBusMethodInvocation object that can be used to return a value or error.
   *
   * On exported objects, this signal is emitted when a remote process (identified by @invocation) invokes the <literal>org.shr.phonefso.Usage.GetDefaultBrightness()</literal> D-Bus method on @object. Use phonefso_usage_complete_get_default_brightness() to return a value or g_dbus_method_invocation_return_error() to return an error.
   *
   * The signal is emitted in the
   * <link linkend="g-main-context-push-thread-default">thread-default main loop</link>
   * of the thread that @object was registered in.
   *
   * On proxies, this signal is never emitted.
   *
   * Returns: %TRUE if you want to handle the method call (will stop further handlers from being called), %FALSE otherwise.
   */
  signals[__GET_DEFAULT_BRIGHTNESS_METHOD] =
    g_signal_new ("handle-get-default-brightness",
                  G_TYPE_FROM_INTERFACE (iface),
                  G_SIGNAL_RUN_LAST,
                  G_STRUCT_OFFSET (PhonefsoUsageIface, handle_get_default_brightness),
                  g_signal_accumulator_true_handled,
                  NULL,
                  _shr_gdbus_cclosure_marshaller_BOOLEAN__OBJECT,
                  G_TYPE_BOOLEAN,
                  1,
                  G_TYPE_DBUS_METHOD_INVOCATION);
  /**
   * PhonefsoUsage::handle-set-pdp-credentials:
   * @object: The exported object emitting the signal.
   * @invocation: A #GDBusMethodInvocation object that can be used to return a value or error.
   * @apn: Parameter.
   * @user: Parameter.
   * @password: Parameter.
   *
   * On exported objects, this signal is emitted when a remote process (identified by @invocation) invokes the <literal>org.shr.phonefso.Usage.SetPdpCredentials()</literal> D-Bus method on @object. Use phonefso_usage_complete_set_pdp_credentials() to return a value or g_dbus_method_invocation_return_error() to return an error.
   *
   * The signal is emitted in the
   * <link linkend="g-main-context-push-thread-default">thread-default main loop</link>
   * of the thread that @object was registered in.
   *
   * On proxies, this signal is never emitted.
   *
   * Returns: %TRUE if you want to handle the method call (will stop further handlers from being called), %FALSE otherwise.
   */
  signals[__SET_PDP_CREDENTIALS_METHOD] =
    g_signal_new ("handle-set-pdp-credentials",
                  G_TYPE_FROM_INTERFACE (iface),
                  G_SIGNAL_RUN_LAST,
                  G_STRUCT_OFFSET (PhonefsoUsageIface, handle_set_pdp_credentials),
                  g_signal_accumulator_true_handled,
                  NULL,
                  _shr_gdbus_cclosure_marshaller_BOOLEAN__OBJECT_STRING_STRING_STRING,
                  G_TYPE_BOOLEAN,
                  4,
                  G_TYPE_DBUS_METHOD_INVOCATION,
                  G_TYPE_STRING,
                  G_TYPE_STRING,
                  G_TYPE_STRING);
  /**
   * PhonefsoUsage::handle-set-pin:
   * @object: The exported object emitting the signal.
   * @invocation: A #GDBusMethodInvocation object that can be used to return a value or error.
   * @pin: Parameter.
   *
   * On exported objects, this signal is emitted when a remote process (identified by @invocation) invokes the <literal>org.shr.phonefso.Usage.SetPin()</literal> D-Bus method on @object. Use phonefso_usage_complete_set_pin() to return a value or g_dbus_method_invocation_return_error() to return an error.
   *
   * The signal is emitted in the
   * <link linkend="g-main-context-push-thread-default">thread-default main loop</link>
   * of the thread that @object was registered in.
   *
   * On proxies, this signal is never emitted.
   *
   * Returns: %TRUE if you want to handle the method call (will stop further handlers from being called), %FALSE otherwise.
   */
  signals[__SET_PIN_METHOD] =
    g_signal_new ("handle-set-pin",
                  G_TYPE_FROM_INTERFACE (iface),
                  G_SIGNAL_RUN_LAST,
                  G_STRUCT_OFFSET (PhonefsoUsageIface, handle_set_pin),
                  g_signal_accumulator_true_handled,
                  NULL,
                  _shr_gdbus_cclosure_marshaller_BOOLEAN__OBJECT_STRING,
                  G_TYPE_BOOLEAN,
                  2,
                  G_TYPE_DBUS_METHOD_INVOCATION,
                  G_TYPE_STRING);

  /* GObject property definitions for D-Bus properties: */
}


/* C Bindings for properties */

/**
 * phonefso_usage_call_set_offline_mode:
 * @proxy: A #PhonefsoUsage.
 * @state: Method parameter.
 * @cancellable: A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL if you don't care about the result of the method invocation.
 * @user_data: Data to pass to @callback.
 *
 * Invokes the <literal>org.shr.phonefso.Usage.SetOfflineMode()</literal>
 * D-Bus method on the remote object represented by @proxy.
 *
 * This is an asynchronous method. When the operation is finished,
 * callback will be invoked in the
 * <link linkend="g-main-context-push-thread-default">thread-default main loop</link>
 * of the thread you are calling this method from. You can then call
 * phonefso_usage_call_set_offline_mode_finish() to get the result of the operation.
 * See phonefso_usage_call_set_offline_mode_sync() for the synchronous version of this method.
 */
void phonefso_usage_call_set_offline_mode (
        PhonefsoUsage *proxy,
        gboolean state,
        GCancellable *cancellable,
        GAsyncReadyCallback callback,
        gpointer user_data)
{
  GVariant *_params;
  _params = g_variant_new ("(b)",
                           state);
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
                     "SetOfflineMode",
                     _params,
                     G_DBUS_CALL_FLAGS_NONE,
                     -1,
                     cancellable,
                     callback,
                     user_data);
}

/**
 * phonefso_usage_call_set_offline_mode_finish:
 * @proxy: A #PhonefsoUsage.
 * @res: A #GAsyncResult obtained from the #GAsyncReadyCallback passed to phonefso_usage_call_set_offline_mode().
 * @error: Return location for error or %NULL.
 *
 * Finishes invoking the <literal>org.shr.phonefso.Usage.SetOfflineMode()</literal>
 * D-Bus method on the remote object represented by @proxy.
 *
 * Returns: %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean phonefso_usage_call_set_offline_mode_finish (
        PhonefsoUsage *proxy,
        GAsyncResult *res,
        GError **error)
{
  gboolean _ret = FALSE;
  GVariant *_result;
  _result = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_result == NULL)
    goto _out;
  g_variant_unref (_result);
  _ret = TRUE;
_out:
  return _ret;
}

/**
 * phonefso_usage_call_set_offline_mode_sync:
 * @proxy: A #PhonefsoUsage.
 * @state: Method parameter.
 * @cancellable: A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <literal>org.shr.phonefso.Usage.SetOfflineMode()</literal>
 * D-Bus method on the remote object represented by @proxy.
 * The calling thread is blocked until a reply is received. See
 * phonefso_usage_call_set_offline_mode() for the asynchronous version of this method.
 *
 * Returns: %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean phonefso_usage_call_set_offline_mode_sync (
        PhonefsoUsage *proxy,
        gboolean state,
        GCancellable *cancellable,
        GError **error)
{
  gboolean _ret = FALSE;
  GVariant *_params;
  GVariant *_result;
  _params = g_variant_new ("(b)",
                           state);
  _result = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
                                   "SetOfflineMode",
                                   _params,
                                   G_DBUS_CALL_FLAGS_NONE,
                                   -1,
                                   cancellable,
                                   error);
  if (_result == NULL)
    goto _out;
  g_variant_unref (_result);
  _ret = TRUE;
_out:
  return _ret;
}


/**
 * phonefso_usage_call_get_offline_mode:
 * @proxy: A #PhonefsoUsage.
 * @cancellable: A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL if you don't care about the result of the method invocation.
 * @user_data: Data to pass to @callback.
 *
 * Invokes the <literal>org.shr.phonefso.Usage.GetOfflineMode()</literal>
 * D-Bus method on the remote object represented by @proxy.
 *
 * This is an asynchronous method. When the operation is finished,
 * callback will be invoked in the
 * <link linkend="g-main-context-push-thread-default">thread-default main loop</link>
 * of the thread you are calling this method from. You can then call
 * phonefso_usage_call_get_offline_mode_finish() to get the result of the operation.
 * See phonefso_usage_call_get_offline_mode_sync() for the synchronous version of this method.
 */
void phonefso_usage_call_get_offline_mode (
        PhonefsoUsage *proxy,
        GCancellable *cancellable,
        GAsyncReadyCallback callback,
        gpointer user_data)
{
  GVariant *_params;
  _params = NULL;
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
                     "GetOfflineMode",
                     _params,
                     G_DBUS_CALL_FLAGS_NONE,
                     -1,
                     cancellable,
                     callback,
                     user_data);
}

/**
 * phonefso_usage_call_get_offline_mode_finish:
 * @proxy: A #PhonefsoUsage.
 * @out_state: Return location for out parameter or %NULL.
 * @res: A #GAsyncResult obtained from the #GAsyncReadyCallback passed to phonefso_usage_call_get_offline_mode().
 * @error: Return location for error or %NULL.
 *
 * Finishes invoking the <literal>org.shr.phonefso.Usage.GetOfflineMode()</literal>
 * D-Bus method on the remote object represented by @proxy.
 *
 * Returns: %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean phonefso_usage_call_get_offline_mode_finish (
        PhonefsoUsage *proxy,
        gboolean *out_state,
        GAsyncResult *res,
        GError **error)
{
  gboolean _ret = FALSE;
  GVariant *_result;
  _result = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_result == NULL)
    goto _out;
  {
    g_variant_get (_result,
                   "(b)",
                   out_state);
  }
  g_variant_unref (_result);
  _ret = TRUE;
_out:
  return _ret;
}

/**
 * phonefso_usage_call_get_offline_mode_sync:
 * @proxy: A #PhonefsoUsage.
 * @out_state: Return location for out parameter or %NULL.
 * @cancellable: A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <literal>org.shr.phonefso.Usage.GetOfflineMode()</literal>
 * D-Bus method on the remote object represented by @proxy.
 * The calling thread is blocked until a reply is received. See
 * phonefso_usage_call_get_offline_mode() for the asynchronous version of this method.
 *
 * Returns: %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean phonefso_usage_call_get_offline_mode_sync (
        PhonefsoUsage *proxy,
        gboolean *out_state,
        GCancellable *cancellable,
        GError **error)
{
  gboolean _ret = FALSE;
  GVariant *_params;
  GVariant *_result;
  _params = NULL;
  _result = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
                                   "GetOfflineMode",
                                   _params,
                                   G_DBUS_CALL_FLAGS_NONE,
                                   -1,
                                   cancellable,
                                   error);
  if (_result == NULL)
    goto _out;
  {
    g_variant_get (_result,
                   "(b)",
                   out_state);
  }
  g_variant_unref (_result);
  _ret = TRUE;
_out:
  return _ret;
}


/**
 * phonefso_usage_call_set_default_brightness:
 * @proxy: A #PhonefsoUsage.
 * @brightness: Method parameter.
 * @cancellable: A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL if you don't care about the result of the method invocation.
 * @user_data: Data to pass to @callback.
 *
 * Invokes the <literal>org.shr.phonefso.Usage.SetDefaultBrightness()</literal>
 * D-Bus method on the remote object represented by @proxy.
 *
 * This is an asynchronous method. When the operation is finished,
 * callback will be invoked in the
 * <link linkend="g-main-context-push-thread-default">thread-default main loop</link>
 * of the thread you are calling this method from. You can then call
 * phonefso_usage_call_set_default_brightness_finish() to get the result of the operation.
 * See phonefso_usage_call_set_default_brightness_sync() for the synchronous version of this method.
 */
void phonefso_usage_call_set_default_brightness (
        PhonefsoUsage *proxy,
        gint brightness,
        GCancellable *cancellable,
        GAsyncReadyCallback callback,
        gpointer user_data)
{
  GVariant *_params;
  _params = g_variant_new ("(i)",
                           brightness);
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
                     "SetDefaultBrightness",
                     _params,
                     G_DBUS_CALL_FLAGS_NONE,
                     -1,
                     cancellable,
                     callback,
                     user_data);
}

/**
 * phonefso_usage_call_set_default_brightness_finish:
 * @proxy: A #PhonefsoUsage.
 * @res: A #GAsyncResult obtained from the #GAsyncReadyCallback passed to phonefso_usage_call_set_default_brightness().
 * @error: Return location for error or %NULL.
 *
 * Finishes invoking the <literal>org.shr.phonefso.Usage.SetDefaultBrightness()</literal>
 * D-Bus method on the remote object represented by @proxy.
 *
 * Returns: %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean phonefso_usage_call_set_default_brightness_finish (
        PhonefsoUsage *proxy,
        GAsyncResult *res,
        GError **error)
{
  gboolean _ret = FALSE;
  GVariant *_result;
  _result = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_result == NULL)
    goto _out;
  g_variant_unref (_result);
  _ret = TRUE;
_out:
  return _ret;
}

/**
 * phonefso_usage_call_set_default_brightness_sync:
 * @proxy: A #PhonefsoUsage.
 * @brightness: Method parameter.
 * @cancellable: A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <literal>org.shr.phonefso.Usage.SetDefaultBrightness()</literal>
 * D-Bus method on the remote object represented by @proxy.
 * The calling thread is blocked until a reply is received. See
 * phonefso_usage_call_set_default_brightness() for the asynchronous version of this method.
 *
 * Returns: %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean phonefso_usage_call_set_default_brightness_sync (
        PhonefsoUsage *proxy,
        gint brightness,
        GCancellable *cancellable,
        GError **error)
{
  gboolean _ret = FALSE;
  GVariant *_params;
  GVariant *_result;
  _params = g_variant_new ("(i)",
                           brightness);
  _result = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
                                   "SetDefaultBrightness",
                                   _params,
                                   G_DBUS_CALL_FLAGS_NONE,
                                   -1,
                                   cancellable,
                                   error);
  if (_result == NULL)
    goto _out;
  g_variant_unref (_result);
  _ret = TRUE;
_out:
  return _ret;
}


/**
 * phonefso_usage_call_get_default_brightness:
 * @proxy: A #PhonefsoUsage.
 * @cancellable: A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL if you don't care about the result of the method invocation.
 * @user_data: Data to pass to @callback.
 *
 * Invokes the <literal>org.shr.phonefso.Usage.GetDefaultBrightness()</literal>
 * D-Bus method on the remote object represented by @proxy.
 *
 * This is an asynchronous method. When the operation is finished,
 * callback will be invoked in the
 * <link linkend="g-main-context-push-thread-default">thread-default main loop</link>
 * of the thread you are calling this method from. You can then call
 * phonefso_usage_call_get_default_brightness_finish() to get the result of the operation.
 * See phonefso_usage_call_get_default_brightness_sync() for the synchronous version of this method.
 */
void phonefso_usage_call_get_default_brightness (
        PhonefsoUsage *proxy,
        GCancellable *cancellable,
        GAsyncReadyCallback callback,
        gpointer user_data)
{
  GVariant *_params;
  _params = NULL;
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
                     "GetDefaultBrightness",
                     _params,
                     G_DBUS_CALL_FLAGS_NONE,
                     -1,
                     cancellable,
                     callback,
                     user_data);
}

/**
 * phonefso_usage_call_get_default_brightness_finish:
 * @proxy: A #PhonefsoUsage.
 * @out_brightness: Return location for out parameter or %NULL.
 * @res: A #GAsyncResult obtained from the #GAsyncReadyCallback passed to phonefso_usage_call_get_default_brightness().
 * @error: Return location for error or %NULL.
 *
 * Finishes invoking the <literal>org.shr.phonefso.Usage.GetDefaultBrightness()</literal>
 * D-Bus method on the remote object represented by @proxy.
 *
 * Returns: %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean phonefso_usage_call_get_default_brightness_finish (
        PhonefsoUsage *proxy,
        gint *out_brightness,
        GAsyncResult *res,
        GError **error)
{
  gboolean _ret = FALSE;
  GVariant *_result;
  _result = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_result == NULL)
    goto _out;
  {
    g_variant_get (_result,
                   "(i)",
                   out_brightness);
  }
  g_variant_unref (_result);
  _ret = TRUE;
_out:
  return _ret;
}

/**
 * phonefso_usage_call_get_default_brightness_sync:
 * @proxy: A #PhonefsoUsage.
 * @out_brightness: Return location for out parameter or %NULL.
 * @cancellable: A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <literal>org.shr.phonefso.Usage.GetDefaultBrightness()</literal>
 * D-Bus method on the remote object represented by @proxy.
 * The calling thread is blocked until a reply is received. See
 * phonefso_usage_call_get_default_brightness() for the asynchronous version of this method.
 *
 * Returns: %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean phonefso_usage_call_get_default_brightness_sync (
        PhonefsoUsage *proxy,
        gint *out_brightness,
        GCancellable *cancellable,
        GError **error)
{
  gboolean _ret = FALSE;
  GVariant *_params;
  GVariant *_result;
  _params = NULL;
  _result = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
                                   "GetDefaultBrightness",
                                   _params,
                                   G_DBUS_CALL_FLAGS_NONE,
                                   -1,
                                   cancellable,
                                   error);
  if (_result == NULL)
    goto _out;
  {
    g_variant_get (_result,
                   "(i)",
                   out_brightness);
  }
  g_variant_unref (_result);
  _ret = TRUE;
_out:
  return _ret;
}


/**
 * phonefso_usage_call_set_pdp_credentials:
 * @proxy: A #PhonefsoUsage.
 * @apn: Method parameter.
 * @user: Method parameter.
 * @password: Method parameter.
 * @cancellable: A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL if you don't care about the result of the method invocation.
 * @user_data: Data to pass to @callback.
 *
 * Invokes the <literal>org.shr.phonefso.Usage.SetPdpCredentials()</literal>
 * D-Bus method on the remote object represented by @proxy.
 *
 * This is an asynchronous method. When the operation is finished,
 * callback will be invoked in the
 * <link linkend="g-main-context-push-thread-default">thread-default main loop</link>
 * of the thread you are calling this method from. You can then call
 * phonefso_usage_call_set_pdp_credentials_finish() to get the result of the operation.
 * See phonefso_usage_call_set_pdp_credentials_sync() for the synchronous version of this method.
 */
void phonefso_usage_call_set_pdp_credentials (
        PhonefsoUsage *proxy,
        const gchar *apn,
        const gchar *user,
        const gchar *password,
        GCancellable *cancellable,
        GAsyncReadyCallback callback,
        gpointer user_data)
{
  GVariant *_params;
  _params = g_variant_new ("(sss)",
                           apn,
                           user,
                           password);
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
                     "SetPdpCredentials",
                     _params,
                     G_DBUS_CALL_FLAGS_NONE,
                     -1,
                     cancellable,
                     callback,
                     user_data);
}

/**
 * phonefso_usage_call_set_pdp_credentials_finish:
 * @proxy: A #PhonefsoUsage.
 * @res: A #GAsyncResult obtained from the #GAsyncReadyCallback passed to phonefso_usage_call_set_pdp_credentials().
 * @error: Return location for error or %NULL.
 *
 * Finishes invoking the <literal>org.shr.phonefso.Usage.SetPdpCredentials()</literal>
 * D-Bus method on the remote object represented by @proxy.
 *
 * Returns: %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean phonefso_usage_call_set_pdp_credentials_finish (
        PhonefsoUsage *proxy,
        GAsyncResult *res,
        GError **error)
{
  gboolean _ret = FALSE;
  GVariant *_result;
  _result = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_result == NULL)
    goto _out;
  g_variant_unref (_result);
  _ret = TRUE;
_out:
  return _ret;
}

/**
 * phonefso_usage_call_set_pdp_credentials_sync:
 * @proxy: A #PhonefsoUsage.
 * @apn: Method parameter.
 * @user: Method parameter.
 * @password: Method parameter.
 * @cancellable: A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <literal>org.shr.phonefso.Usage.SetPdpCredentials()</literal>
 * D-Bus method on the remote object represented by @proxy.
 * The calling thread is blocked until a reply is received. See
 * phonefso_usage_call_set_pdp_credentials() for the asynchronous version of this method.
 *
 * Returns: %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean phonefso_usage_call_set_pdp_credentials_sync (
        PhonefsoUsage *proxy,
        const gchar *apn,
        const gchar *user,
        const gchar *password,
        GCancellable *cancellable,
        GError **error)
{
  gboolean _ret = FALSE;
  GVariant *_params;
  GVariant *_result;
  _params = g_variant_new ("(sss)",
                           apn,
                           user,
                           password);
  _result = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
                                   "SetPdpCredentials",
                                   _params,
                                   G_DBUS_CALL_FLAGS_NONE,
                                   -1,
                                   cancellable,
                                   error);
  if (_result == NULL)
    goto _out;
  g_variant_unref (_result);
  _ret = TRUE;
_out:
  return _ret;
}


/**
 * phonefso_usage_call_set_pin:
 * @proxy: A #PhonefsoUsage.
 * @pin: Method parameter.
 * @cancellable: A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL if you don't care about the result of the method invocation.
 * @user_data: Data to pass to @callback.
 *
 * Invokes the <literal>org.shr.phonefso.Usage.SetPin()</literal>
 * D-Bus method on the remote object represented by @proxy.
 *
 * This is an asynchronous method. When the operation is finished,
 * callback will be invoked in the
 * <link linkend="g-main-context-push-thread-default">thread-default main loop</link>
 * of the thread you are calling this method from. You can then call
 * phonefso_usage_call_set_pin_finish() to get the result of the operation.
 * See phonefso_usage_call_set_pin_sync() for the synchronous version of this method.
 */
void phonefso_usage_call_set_pin (
        PhonefsoUsage *proxy,
        const gchar *pin,
        GCancellable *cancellable,
        GAsyncReadyCallback callback,
        gpointer user_data)
{
  GVariant *_params;
  _params = g_variant_new ("(s)",
                           pin);
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
                     "SetPin",
                     _params,
                     G_DBUS_CALL_FLAGS_NONE,
                     -1,
                     cancellable,
                     callback,
                     user_data);
}

/**
 * phonefso_usage_call_set_pin_finish:
 * @proxy: A #PhonefsoUsage.
 * @res: A #GAsyncResult obtained from the #GAsyncReadyCallback passed to phonefso_usage_call_set_pin().
 * @error: Return location for error or %NULL.
 *
 * Finishes invoking the <literal>org.shr.phonefso.Usage.SetPin()</literal>
 * D-Bus method on the remote object represented by @proxy.
 *
 * Returns: %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean phonefso_usage_call_set_pin_finish (
        PhonefsoUsage *proxy,
        GAsyncResult *res,
        GError **error)
{
  gboolean _ret = FALSE;
  GVariant *_result;
  _result = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_result == NULL)
    goto _out;
  g_variant_unref (_result);
  _ret = TRUE;
_out:
  return _ret;
}

/**
 * phonefso_usage_call_set_pin_sync:
 * @proxy: A #PhonefsoUsage.
 * @pin: Method parameter.
 * @cancellable: A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <literal>org.shr.phonefso.Usage.SetPin()</literal>
 * D-Bus method on the remote object represented by @proxy.
 * The calling thread is blocked until a reply is received. See
 * phonefso_usage_call_set_pin() for the asynchronous version of this method.
 *
 * Returns: %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean phonefso_usage_call_set_pin_sync (
        PhonefsoUsage *proxy,
        const gchar *pin,
        GCancellable *cancellable,
        GError **error)
{
  gboolean _ret = FALSE;
  GVariant *_params;
  GVariant *_result;
  _params = g_variant_new ("(s)",
                           pin);
  _result = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
                                   "SetPin",
                                   _params,
                                   G_DBUS_CALL_FLAGS_NONE,
                                   -1,
                                   cancellable,
                                   error);
  if (_result == NULL)
    goto _out;
  g_variant_unref (_result);
  _ret = TRUE;
_out:
  return _ret;
}


/**
 * phonefso_usage_complete_set_offline_mode:
 * @object: A #PhonefsoUsage.
 * @invocation: A #GDBusMethodInvocation.
 *
 * Completes handling the <literal>org.shr.phonefso.Usage.SetOfflineMode()</literal>
 * D-Bus method invocation by returning a value.
 *
 * If you want to return an error, use g_dbus_method_invocation_return_error()
 * or similar instead.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void phonefso_usage_complete_set_offline_mode (
        PhonefsoUsage *object,
        GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation, NULL);
}


/**
 * phonefso_usage_complete_get_offline_mode:
 * @object: A #PhonefsoUsage.
 * @invocation: A #GDBusMethodInvocation.
 * @state: Value to return.
 *
 * Completes handling the <literal>org.shr.phonefso.Usage.GetOfflineMode()</literal>
 * D-Bus method invocation by returning a value.
 *
 * If you want to return an error, use g_dbus_method_invocation_return_error()
 * or similar instead.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void phonefso_usage_complete_get_offline_mode (
        PhonefsoUsage *object,
        GDBusMethodInvocation *invocation,
        gboolean state)
{
  GVariant *_params;
  _params = g_variant_new ("(b)",
                           state);
  g_dbus_method_invocation_return_value (invocation, _params);
}


/**
 * phonefso_usage_complete_set_default_brightness:
 * @object: A #PhonefsoUsage.
 * @invocation: A #GDBusMethodInvocation.
 *
 * Completes handling the <literal>org.shr.phonefso.Usage.SetDefaultBrightness()</literal>
 * D-Bus method invocation by returning a value.
 *
 * If you want to return an error, use g_dbus_method_invocation_return_error()
 * or similar instead.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void phonefso_usage_complete_set_default_brightness (
        PhonefsoUsage *object,
        GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation, NULL);
}


/**
 * phonefso_usage_complete_get_default_brightness:
 * @object: A #PhonefsoUsage.
 * @invocation: A #GDBusMethodInvocation.
 * @brightness: Value to return.
 *
 * Completes handling the <literal>org.shr.phonefso.Usage.GetDefaultBrightness()</literal>
 * D-Bus method invocation by returning a value.
 *
 * If you want to return an error, use g_dbus_method_invocation_return_error()
 * or similar instead.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void phonefso_usage_complete_get_default_brightness (
        PhonefsoUsage *object,
        GDBusMethodInvocation *invocation,
        gint brightness)
{
  GVariant *_params;
  _params = g_variant_new ("(i)",
                           brightness);
  g_dbus_method_invocation_return_value (invocation, _params);
}


/**
 * phonefso_usage_complete_set_pdp_credentials:
 * @object: A #PhonefsoUsage.
 * @invocation: A #GDBusMethodInvocation.
 *
 * Completes handling the <literal>org.shr.phonefso.Usage.SetPdpCredentials()</literal>
 * D-Bus method invocation by returning a value.
 *
 * If you want to return an error, use g_dbus_method_invocation_return_error()
 * or similar instead.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void phonefso_usage_complete_set_pdp_credentials (
        PhonefsoUsage *object,
        GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation, NULL);
}


/**
 * phonefso_usage_complete_set_pin:
 * @object: A #PhonefsoUsage.
 * @invocation: A #GDBusMethodInvocation.
 *
 * Completes handling the <literal>org.shr.phonefso.Usage.SetPin()</literal>
 * D-Bus method invocation by returning a value.
 *
 * If you want to return an error, use g_dbus_method_invocation_return_error()
 * or similar instead.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void phonefso_usage_complete_set_pin (
        PhonefsoUsage *object,
        GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation, NULL);
}


static const GDBusArgInfo phonefso_usage_method_in_SetOfflineMode_state =
{
  -1,
  "state",
  "b",
  (GDBusAnnotationInfo **) NULL
};
static const GDBusArgInfo * const phonefso_usage_method_in_SetOfflineMode_arg_pointers[] =
{
  &phonefso_usage_method_in_SetOfflineMode_state,
  NULL
};

static const GDBusAnnotationInfo SetOfflineMode_method_annotations_annotation_0 = {
  -1,
  "org.freedesktop.DBus.GLib.Async",
  "true",
};

static const GDBusAnnotationInfo *SetOfflineMode_method_annotations[] = {
  &SetOfflineMode_method_annotations_annotation_0,
  NULL
};

static const GDBusMethodInfo phonefso_usage_method_SetOfflineMode =
{
  -1,
  "SetOfflineMode",
  (GDBusArgInfo **) &phonefso_usage_method_in_SetOfflineMode_arg_pointers,
  (GDBusArgInfo **) NULL,
  (GDBusAnnotationInfo **) SetOfflineMode_method_annotations,
};

static const GDBusArgInfo phonefso_usage_method_out_GetOfflineMode_state =
{
  -1,
  "state",
  "b",
  (GDBusAnnotationInfo **) NULL
};
static const GDBusArgInfo * const phonefso_usage_method_out_GetOfflineMode_arg_pointers[] =
{
  &phonefso_usage_method_out_GetOfflineMode_state,
  NULL
};

static const GDBusAnnotationInfo GetOfflineMode_method_annotations_annotation_0 = {
  -1,
  "org.freedesktop.DBus.GLib.Async",
  "true",
};

static const GDBusAnnotationInfo *GetOfflineMode_method_annotations[] = {
  &GetOfflineMode_method_annotations_annotation_0,
  NULL
};

static const GDBusMethodInfo phonefso_usage_method_GetOfflineMode =
{
  -1,
  "GetOfflineMode",
  (GDBusArgInfo **) NULL,
  (GDBusArgInfo **) &phonefso_usage_method_out_GetOfflineMode_arg_pointers,
  (GDBusAnnotationInfo **) GetOfflineMode_method_annotations,
};

static const GDBusArgInfo phonefso_usage_method_in_SetDefaultBrightness_brightness =
{
  -1,
  "brightness",
  "i",
  (GDBusAnnotationInfo **) NULL
};
static const GDBusArgInfo * const phonefso_usage_method_in_SetDefaultBrightness_arg_pointers[] =
{
  &phonefso_usage_method_in_SetDefaultBrightness_brightness,
  NULL
};

static const GDBusAnnotationInfo SetDefaultBrightness_method_annotations_annotation_0 = {
  -1,
  "org.freedesktop.DBus.GLib.Async",
  "true",
};

static const GDBusAnnotationInfo *SetDefaultBrightness_method_annotations[] = {
  &SetDefaultBrightness_method_annotations_annotation_0,
  NULL
};

static const GDBusMethodInfo phonefso_usage_method_SetDefaultBrightness =
{
  -1,
  "SetDefaultBrightness",
  (GDBusArgInfo **) &phonefso_usage_method_in_SetDefaultBrightness_arg_pointers,
  (GDBusArgInfo **) NULL,
  (GDBusAnnotationInfo **) SetDefaultBrightness_method_annotations,
};

static const GDBusArgInfo phonefso_usage_method_out_GetDefaultBrightness_brightness =
{
  -1,
  "brightness",
  "i",
  (GDBusAnnotationInfo **) NULL
};
static const GDBusArgInfo * const phonefso_usage_method_out_GetDefaultBrightness_arg_pointers[] =
{
  &phonefso_usage_method_out_GetDefaultBrightness_brightness,
  NULL
};

static const GDBusAnnotationInfo GetDefaultBrightness_method_annotations_annotation_0 = {
  -1,
  "org.freedesktop.DBus.GLib.Async",
  "true",
};

static const GDBusAnnotationInfo *GetDefaultBrightness_method_annotations[] = {
  &GetDefaultBrightness_method_annotations_annotation_0,
  NULL
};

static const GDBusMethodInfo phonefso_usage_method_GetDefaultBrightness =
{
  -1,
  "GetDefaultBrightness",
  (GDBusArgInfo **) NULL,
  (GDBusArgInfo **) &phonefso_usage_method_out_GetDefaultBrightness_arg_pointers,
  (GDBusAnnotationInfo **) GetDefaultBrightness_method_annotations,
};

static const GDBusArgInfo phonefso_usage_method_in_SetPdpCredentials_apn =
{
  -1,
  "apn",
  "s",
  (GDBusAnnotationInfo **) NULL
};
static const GDBusArgInfo phonefso_usage_method_in_SetPdpCredentials_user =
{
  -1,
  "user",
  "s",
  (GDBusAnnotationInfo **) NULL
};
static const GDBusArgInfo phonefso_usage_method_in_SetPdpCredentials_password =
{
  -1,
  "password",
  "s",
  (GDBusAnnotationInfo **) NULL
};
static const GDBusArgInfo * const phonefso_usage_method_in_SetPdpCredentials_arg_pointers[] =
{
  &phonefso_usage_method_in_SetPdpCredentials_apn,
  &phonefso_usage_method_in_SetPdpCredentials_user,
  &phonefso_usage_method_in_SetPdpCredentials_password,
  NULL
};

static const GDBusAnnotationInfo SetPdpCredentials_method_annotations_annotation_0 = {
  -1,
  "org.freedesktop.DBus.GLib.Async",
  "true",
};

static const GDBusAnnotationInfo *SetPdpCredentials_method_annotations[] = {
  &SetPdpCredentials_method_annotations_annotation_0,
  NULL
};

static const GDBusMethodInfo phonefso_usage_method_SetPdpCredentials =
{
  -1,
  "SetPdpCredentials",
  (GDBusArgInfo **) &phonefso_usage_method_in_SetPdpCredentials_arg_pointers,
  (GDBusArgInfo **) NULL,
  (GDBusAnnotationInfo **) SetPdpCredentials_method_annotations,
};

static const GDBusArgInfo phonefso_usage_method_in_SetPin_pin =
{
  -1,
  "pin",
  "s",
  (GDBusAnnotationInfo **) NULL
};
static const GDBusArgInfo * const phonefso_usage_method_in_SetPin_arg_pointers[] =
{
  &phonefso_usage_method_in_SetPin_pin,
  NULL
};

static const GDBusAnnotationInfo SetPin_method_annotations_annotation_0 = {
  -1,
  "org.freedesktop.DBus.GLib.Async",
  "true",
};

static const GDBusAnnotationInfo *SetPin_method_annotations[] = {
  &SetPin_method_annotations_annotation_0,
  NULL
};

static const GDBusMethodInfo phonefso_usage_method_SetPin =
{
  -1,
  "SetPin",
  (GDBusArgInfo **) &phonefso_usage_method_in_SetPin_arg_pointers,
  (GDBusArgInfo **) NULL,
  (GDBusAnnotationInfo **) SetPin_method_annotations,
};

static const GDBusMethodInfo * const phonefso_usage_method_info_pointers[] =
{
  &phonefso_usage_method_SetOfflineMode,
  &phonefso_usage_method_GetOfflineMode,
  &phonefso_usage_method_SetDefaultBrightness,
  &phonefso_usage_method_GetDefaultBrightness,
  &phonefso_usage_method_SetPdpCredentials,
  &phonefso_usage_method_SetPin,
  NULL
};

static const GDBusInterfaceInfo _phonefso_usage_interface_info =
{
  -1,
  "org.shr.phonefso.Usage",
  (GDBusMethodInfo **) &phonefso_usage_method_info_pointers,
  (GDBusSignalInfo **) NULL,
  (GDBusPropertyInfo **) NULL,
  (GDBusAnnotationInfo **) NULL
};

static void
handle_method_call_real (GDBusConnection       *connection,
                         const gchar           *sender,
                         const gchar           *object_path,
                         const gchar           *interface_name,
                         const gchar           *method_name,
                         GVariant              *parameters,
                         GDBusMethodInvocation *invocation,
                         gpointer               user_data)
{
  guint method_id;
  method_id = lookup_method_id_from_method_name (method_name);
  switch (method_id)
    {
    case __SET_OFFLINE_MODE_METHOD:
      {
        PhonefsoUsage *object = PHONEFSO_USAGE (user_data);
        gboolean handled;
        gboolean arg_state;
        g_variant_get (parameters,
                       "(b)",
                       &arg_state);
        g_signal_emit (object,
                       signals[method_id],
                       0, invocation, arg_state, &handled);
        if (!handled)
          goto not_implemented;
      }
      break;

    case __GET_OFFLINE_MODE_METHOD:
      {
        PhonefsoUsage *object = PHONEFSO_USAGE (user_data);
        gboolean handled;
        g_signal_emit (object,
                       signals[method_id],
                       0, invocation, &handled);
        if (!handled)
          goto not_implemented;
      }
      break;

    case __SET_DEFAULT_BRIGHTNESS_METHOD:
      {
        PhonefsoUsage *object = PHONEFSO_USAGE (user_data);
        gboolean handled;
        gint arg_brightness;
        g_variant_get (parameters,
                       "(i)",
                       &arg_brightness);
        g_signal_emit (object,
                       signals[method_id],
                       0, invocation, arg_brightness, &handled);
        if (!handled)
          goto not_implemented;
      }
      break;

    case __GET_DEFAULT_BRIGHTNESS_METHOD:
      {
        PhonefsoUsage *object = PHONEFSO_USAGE (user_data);
        gboolean handled;
        g_signal_emit (object,
                       signals[method_id],
                       0, invocation, &handled);
        if (!handled)
          goto not_implemented;
      }
      break;

    case __SET_PDP_CREDENTIALS_METHOD:
      {
        PhonefsoUsage *object = PHONEFSO_USAGE (user_data);
        gboolean handled;
        const gchar *arg_apn;
        const gchar *arg_user;
        const gchar *arg_password;
        g_variant_get (parameters,
                       "(&s&s&s)",
                       &arg_apn,
                       &arg_user,
                       &arg_password);
        g_signal_emit (object,
                       signals[method_id],
                       0, invocation, arg_apn, arg_user, arg_password, &handled);
        if (!handled)
          goto not_implemented;
      }
      break;

    case __SET_PIN_METHOD:
      {
        PhonefsoUsage *object = PHONEFSO_USAGE (user_data);
        gboolean handled;
        const gchar *arg_pin;
        g_variant_get (parameters,
                       "(&s)",
                       &arg_pin);
        g_signal_emit (object,
                       signals[method_id],
                       0, invocation, arg_pin, &handled);
        if (!handled)
          goto not_implemented;
      }
      break;

    default:
not_implemented:
      g_dbus_method_invocation_return_error (invocation,
                                             G_DBUS_ERROR,
                                             G_DBUS_ERROR_NOT_SUPPORTED,
                                             "Method `%s' is not implemented",
                                             method_name);
      break;
    }
};

typedef struct
{
  GDBusMethodInvocation *invocation;
  gpointer               user_data;
} HandleMethodInThreadData;

static gboolean
handle_method_call_in_thread_func (GIOSchedulerJob *job,
                                   GCancellable    *cancellable,
                                   gpointer         user_data)
{
  HandleMethodInThreadData *data = user_data;

  handle_method_call_real (g_dbus_method_invocation_get_connection (data->invocation),
                           g_dbus_method_invocation_get_sender (data->invocation),
                           g_dbus_method_invocation_get_object_path (data->invocation),
                           g_dbus_method_invocation_get_interface_name (data->invocation),
                           g_dbus_method_invocation_get_method_name (data->invocation),
                           g_dbus_method_invocation_get_parameters (data->invocation),
                           data->invocation,
                           data->user_data);
  return FALSE; /* job is complete */
}

static void
handle_method_call (GDBusConnection       *connection,
                    const gchar           *sender,
                    const gchar           *object_path,
                    const gchar           *interface_name,
                    const gchar           *method_name,
                    GVariant              *parameters,
                    GDBusMethodInvocation *invocation,
                    gpointer               user_data)
{
  GDBusInterface *interface = G_DBUS_INTERFACE (user_data);
  GDBusInterfaceFlags flags;

  flags = g_dbus_interface_get_flags (interface);
  if (flags & G_DBUS_INTERFACE_FLAGS_RUN_IN_THREAD)
    {
      HandleMethodInThreadData *data;
      data = g_new0 (HandleMethodInThreadData, 1);
      data->invocation = invocation;
      data->user_data = user_data;
      g_io_scheduler_push_job (handle_method_call_in_thread_func,
                               data,
                               g_free, /* since we don't need refs on objects */
                               G_PRIORITY_DEFAULT,
                               NULL); /* GCancellable* */
    }
  else
    {
      handle_method_call_real (connection,
                               sender,
                               object_path,
                               interface_name,
                               method_name,
                               parameters,
                               invocation,
                               user_data);
    }
}

static GVariant *
get_property (GDBusConnection  *connection,
              const gchar      *sender,
              const gchar      *object_path,
              const gchar      *interface_name,
              const gchar      *property_name,
              GError          **error,
              gpointer          user_data)
{
  GVariant *ret;
  guint prop_id;
  prop_id = lookup_property_id_from_property_name (property_name);
  ret = NULL;
  switch (prop_id)
    {
    default:
      g_assert_not_reached ();
      break;
    }

  if (ret == NULL)
    {
      GVariant *untrusted_empty;
      GDBusPropertyInfo *property_info;
      const GVariantType *type;
      property_info = g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_phonefso_usage_interface_info, property_name);
      type = G_VARIANT_TYPE (property_info->signature);
      untrusted_empty = g_variant_new_from_data (type, NULL, 0, FALSE, NULL, NULL);
      ret = g_variant_get_normal_form (untrusted_empty);
      g_variant_unref (untrusted_empty);
    }

  return ret;
};

static gboolean
set_property (GDBusConnection  *connection,
              const gchar      *sender,
              const gchar      *object_path,
              const gchar      *interface_name,
              const gchar      *property_name,
              GVariant         *value,
              GError          **error,
              gpointer          user_data)
{
  gboolean ret;
  guint prop_id;
  prop_id = lookup_property_id_from_property_name (property_name);
  ret = TRUE;
  switch (prop_id)
    {
    default:
      g_set_error (error,
                   G_DBUS_ERROR,
                   G_DBUS_ERROR_NOT_SUPPORTED,
                   "This implementation does not support property `%s'",
                   property_name);
      ret = FALSE;
      break;
    }

  return ret;
};

static const GDBusInterfaceVTable phonefso_usage_interface_vtable =
{
  handle_method_call,
  get_property,
  set_property,
};

/* ---------------------------------------------------------------------- */

typedef struct {
  gpointer data;
  gsize size;
} _VariantBlob;

static void
_variant_blob_free (_VariantBlob *blob)
{
  g_free (blob->data);
  g_free (blob);
}

static _VariantBlob *
_variant_blob_new (GVariant *value)
{
  _VariantBlob *blob;
  blob = g_new0 (_VariantBlob, 1);
  blob->size = g_variant_get_size (value);
  blob->data = g_malloc (blob->size);
  g_variant_store (value, blob->data);
  return blob;
}

static gboolean
_variant_blob_equal (_VariantBlob *a,
                    _VariantBlob *b)
{
  return (a->size == b->size) && (memcmp (a->data, b->data, a->size) == 0);
}
/* ---------------------------------------------------------------------- */

static gboolean
emit_notifications_in_idle (gpointer user_data)
{
  GObject *object = G_OBJECT (user_data);
  GDBusConnection *connection;
  const gchar *path;
  GHashTable *notification_queue;
  GHashTableIter iter;
  const gchar *property_name;
  GVariant *value;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  GHashTable *pvc;
  gboolean has_changes;

  notification_queue = g_object_get_data (object, "gdbus-codegen-notification-queue");
  path = g_object_get_data (object, "gdbus-codegen-path");
  connection = g_object_get_data (object, "gdbus-codegen-connection");
  pvc = g_object_get_data (object, "gdbus-codegen-pvc");
  g_assert (notification_queue != NULL && path != NULL && connection != NULL && pvc != NULL);

  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  g_hash_table_iter_init (&iter, notification_queue);
  has_changes = FALSE;
  while (g_hash_table_iter_next (&iter, (gpointer) &property_name, (gpointer) &value))
    {
      _VariantBlob *cached_blob;
      _VariantBlob *blob;
      cached_blob = g_hash_table_lookup (pvc, property_name);
      blob = _variant_blob_new (value);
      if (cached_blob == NULL || !_variant_blob_equal (cached_blob, blob))
        {
          g_hash_table_insert (pvc, (gpointer) property_name, blob);
          g_variant_builder_add (&builder, "{sv}", property_name, value);
          has_changes = TRUE;
        }
      else
        {
          _variant_blob_free (blob);
        }
    }

  if (has_changes)
    {
      g_dbus_connection_emit_signal (connection,
                                     NULL,
                                     path,
                                     "org.freedesktop.DBus.Properties",
                                     "PropertiesChanged",
                                     g_variant_new ("(sa{sv}as)",
                                                    "org.shr.phonefso.Usage",
                                                    &builder,
                                                    &invalidated_builder),
                                     NULL);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }

  g_hash_table_remove_all (notification_queue);
  g_object_set_data (object, "gdbus-codegen-notification-idle-source", NULL);
  return FALSE;
}

static void
queue_notification (GObject     *object,
                    const gchar *property_name,
                    GVariant    *value)
{
  GHashTable *notification_queue;
  GSource *idle_source;
  notification_queue = g_object_get_data (object, "gdbus-codegen-notification-queue");
  if (notification_queue == NULL)
    {
      notification_queue = g_hash_table_new_full (g_str_hash, g_str_equal, NULL, (GDestroyNotify) g_variant_unref);
      g_object_set_data_full (object, "gdbus-codegen-notification-queue", notification_queue, (GDestroyNotify) g_hash_table_unref);
    }
  g_hash_table_insert (notification_queue, (gpointer) property_name, (gpointer) value); /* adopts value */
  idle_source = g_object_get_data (object, "gdbus-codegen-notification-idle-source");
  if (idle_source == NULL)
    {
      idle_source = g_idle_source_new ();
      g_source_set_priority (idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (idle_source,
                             emit_notifications_in_idle,
                             g_object_ref (object),
                             (GDestroyNotify) g_object_unref);
      g_source_attach (idle_source, g_main_context_get_thread_default ());
      g_source_unref (idle_source);
      g_object_set_data (object, "gdbus-codegen-notification-idle-source", idle_source);
    }
}

static void
phonefso_usage_flush (GDBusInterface *_object)
{
  PhonefsoUsage *object = PHONEFSO_USAGE (_object);
  GSource *idle_source;
  idle_source = g_object_get_data (G_OBJECT (object), "gdbus-codegen-notification-idle-source");
  if (idle_source != NULL)
    {
      emit_notifications_in_idle (object);
      g_source_destroy (idle_source);
    }
}

static void
on_notify (GObject    *object,
           GParamSpec *pspec,
           gpointer    user_data)
{
  GDBusConnection *connection;
  const gchar *path;
  GVariant *value;
  const gchar *property_name;

  path = g_object_get_data (object, "gdbus-codegen-path");
  connection = g_object_get_data (object, "gdbus-codegen-connection");
  if (connection == NULL || path == NULL)
    goto out;
  property_name = lookup_property_name_from_property_gname (pspec->name);
  if (property_name == NULL)
    goto out;

  value = get_property (connection, NULL, path, "org.shr.phonefso.Usage", property_name, NULL, object);
  if (value != NULL)
    {
      if (g_variant_is_floating (value))
        g_variant_ref_sink (value);
      queue_notification (object, property_name, value);
    }
out:
  ;
}

static void
on_object_unregistered (GObject *object)
{
  GSource *idle_source;
  idle_source = g_object_get_data (G_OBJECT (object), "gdbus-codegen-notification-idle-source");
  if (idle_source != NULL)
    g_source_destroy (idle_source);
  g_object_set_data (G_OBJECT (object), "gdbus-codegen-notification-idle-source", NULL);
  g_object_set_data (G_OBJECT (object), "gdbus-codegen-path", NULL);
  g_object_set_data (G_OBJECT (object), "gdbus-codegen-connection", NULL);
  g_signal_handlers_disconnect_by_func (object, on_notify, NULL);
}

static guint
phonefso_usage_register_object (GDBusInterface *_object,
           GDBusConnection *connection,
           const gchar *object_path,
           GError **error)
{
  PhonefsoUsage *object = PHONEFSO_USAGE (_object);
  GHashTable *pvc;
  guint n;

  pvc = g_hash_table_new_full (g_str_hash, g_str_equal, NULL, (GDestroyNotify) _variant_blob_free);
  if (_phonefso_usage_interface_info.properties != NULL)
    {
      for (n = 0; _phonefso_usage_interface_info.properties[n] != NULL; n++)
        {
          GDBusPropertyInfo *prop_info = _phonefso_usage_interface_info.properties[n];
          if (prop_info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
            {
              GVariant *value;
              value = get_property (connection, NULL, object_path, "org.shr.phonefso.Usage", prop_info->name, NULL, object);
              if (value != NULL)
                {
                  if (g_variant_is_floating (value))
                    g_variant_ref_sink (value);
                  g_hash_table_insert (pvc, prop_info->name, _variant_blob_new (value));
                  g_variant_unref (value);
                }
            }
        }
    }

  g_object_set_data_full (G_OBJECT (object), "gdbus-codegen-path", (gpointer) g_strdup (object_path), g_free);
  g_object_set_data (G_OBJECT (object), "gdbus-codegen-connection", (gpointer) connection);
  g_object_set_data_full (G_OBJECT (object), "gdbus-codegen-pvc", (gpointer) pvc, (GDestroyNotify) g_hash_table_unref);
  g_signal_connect (object, "notify", G_CALLBACK (on_notify), NULL);
  return g_dbus_connection_register_object (connection,
          object_path,
          (GDBusInterfaceInfo *) &_phonefso_usage_interface_info,
          &phonefso_usage_interface_vtable,
          object,
          (GDestroyNotify) on_object_unregistered,
          error);
}

/**
 * phonefso_usage_interface_info:
 *
 * Gets interface description for the <literal>org.shr.phonefso.Usage</literal> D-Bus interface.
 *
 * Returns: A #GDBusInterfaceInfo. Do not free, the object is statically allocated.
 */
GDBusInterfaceInfo *
phonefso_usage_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_phonefso_usage_interface_info;
}

static GDBusInterfaceInfo *
phonefso_usage_g_dbus_interface_interface_info (GDBusInterface *object)
{
  return phonefso_usage_interface_info ();
}

static GVariant *
phonefso_usage_get_properties (GDBusInterface *object)
{
  GDBusConnection *connection;
  const gchar *object_path;
  GVariantBuilder builder;
  guint n;

  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));

  if (_phonefso_usage_interface_info.properties == NULL)
    goto out;

  connection = g_object_get_data (G_OBJECT (object), "gdbus-codegen-connection");
  object_path = g_object_get_data (G_OBJECT (object), "gdbus-codegen-path");

  for (n = 0; _phonefso_usage_interface_info.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *prop_info = _phonefso_usage_interface_info.properties[n];
      if (prop_info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = get_property (connection, NULL, object_path, "org.shr.phonefso.Usage", prop_info->name, NULL, object);
          if (value != NULL)
            {
              if (g_variant_is_floating (value))
                g_variant_ref_sink (value);
              g_variant_builder_add (&builder, "{sv}", prop_info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}


/* ---------------------------------------------------------------------- */

static void proxy_iface_init (PhonefsoUsageIface *iface);

G_DEFINE_TYPE_WITH_CODE (PhonefsoUsageProxy, phonefso_usage_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_PHONEFSO_USAGE, proxy_iface_init));

static void
phonefso_usage_proxy_init (PhonefsoUsageProxy *proxy)
{
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy),
                                   (GDBusInterfaceInfo *) &_phonefso_usage_interface_info);
}

static void
g_signal (GDBusProxy  *proxy,
          const gchar *sender_name,
          const gchar *signal_name,
          GVariant    *parameters)
{
  guint signal_id;
  signal_id = lookup_signal_id_from_signal_name (signal_name);
  switch (signal_id)
    {
    }
}

static void
phonefso_usage_proxy_get_property (GObject      *object,
                       guint         prop_id,
                       GValue       *value,
                       GParamSpec   *pspec)
{
  G_GNUC_UNUSED GVariant *cached;
  switch (prop_id)
    {

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, prop_id, pspec);
      break;
    }
}

static void
property_set_cb (GDBusProxy   *proxy,
                 GAsyncResult *res,
                 gpointer      user_data)
{
  const gchar *property_name = user_data;
  GError *error;
  GVariant *result;

  error = NULL;
  result = g_dbus_proxy_call_finish (proxy, res, &error);
  if (result == NULL)
    {
      g_warning ("Error setting property `%s': %s", property_name, error->message);
      g_error_free (error);
    }
  else
    {
      g_variant_unref (result);
    }
}

static void
phonefso_usage_proxy_set_property (GObject      *object,
                       guint         prop_id,
                       const GValue *value,
                       GParamSpec   *pspec)
{
  GVariant *new_value;
  const gchar *property_name;
  new_value = NULL;
  property_name = NULL;
  switch (prop_id)
    {

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, prop_id, pspec);
      break;
    }

  if (new_value != NULL)
    {
      g_variant_ref_sink (new_value);
      g_dbus_proxy_call (G_DBUS_PROXY (object),
                         "org.freedesktop.DBus.Properties.Set",
                         g_variant_new ("(ssv)",
                                        "org.shr.phonefso.Usage",
                                        property_name,
                                        new_value),
                         G_DBUS_CALL_FLAGS_NONE,
                         -1,
                         NULL,
                         (GAsyncReadyCallback) property_set_cb,
                         (gpointer) property_name);
      g_variant_unref (new_value);
    }

}

static void
g_properties_changed (GDBusProxy         *proxy,
                      GVariant           *changed_properties,
                      const gchar* const *invalidated_properties)
{
  guint n;
  const gchar *key;
  GVariantIter *iter;
  const gchar *gname;

  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      gname = lookup_property_gname_from_property_name (key);
      if (gname != NULL)
        g_object_notify (G_OBJECT (proxy), gname);
    }

  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      gname = lookup_property_gname_from_property_name (invalidated_properties[n]);
      if (gname != NULL)
        g_object_notify (G_OBJECT (proxy), gname);
    }

}

static void
phonefso_usage_proxy_class_init (PhonefsoUsageProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->get_property = phonefso_usage_proxy_get_property;
  gobject_class->set_property = phonefso_usage_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = g_signal;
  proxy_class->g_properties_changed = g_properties_changed;

}

static void
proxy_iface_init (PhonefsoUsageIface *iface)
{
}


/**
 * phonefso_usage_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags used when constructing the proxy.
 * @name: A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: A #GCancellable or %NULL.
 * @callback: Callback function to invoke when the proxy is ready.
 * @user_data: User data to pass to @callback.
 *
 * Like g_dbus_proxy_new() but returns a #PhonefsoUsageProxy.
 *
 * This is a failable asynchronous constructor - when the proxy is ready, callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this function from. You can then call phonefso_usage_proxy_new_finish() to get the result. See phonefso_usage_proxy_new_sync() for the synchronous version.
 */
void phonefso_usage_proxy_new (GDBusConnection     *connection,
                   GDBusProxyFlags      flags,
                   const gchar         *name,
                   const gchar         *object_path,
                   GCancellable        *cancellable,
                   GAsyncReadyCallback  callback,
                   gpointer             user_data)
{
  g_async_initable_new_async (TYPE_PHONEFSO_USAGE_PROXY,
                              G_PRIORITY_DEFAULT,
                              cancellable,
                              callback,
                              user_data,
                              "g-flags", flags,
                              "g-name", name,
                              "g-connection", connection,
                              "g-object-path", object_path,
                              "g-interface-name", "org.shr.phonefso.Usage",
                              NULL);
}

/**
 * phonefso_usage_proxy_new_finish:
 * @res: A #GAsyncResult obtained from the #GAsyncReadyCallback function passed to phonefso_usage_proxy_new().
 * @error: Return location for error or %NULL.
 *
 * Finishes creating a #PhonefsoUsageProxy.
 *
 * Returns: A #PhonefsoUsageProxy or %NULL if @error is set. Free with g_object_unref().
 */
PhonefsoUsage *phonefso_usage_proxy_new_finish (GAsyncResult  *res,
                        GError       **error)
{
  GObject *object;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  g_assert (source_object != NULL);
  object = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object),
                                        res,
                                        error);
  g_object_unref (source_object);
  if (object != NULL)
    return PHONEFSO_USAGE (object);
  else
    return NULL;
}

/**
 * phonefso_usage_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags used when constructing the proxy.
 * @name: A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Like g_dbus_proxy_new_sync() but returns a #PhonefsoUsageProxy.
 *
 * This is a synchronous failable constructor - the calling thread is blocked until the object is ready. See phonefso_usage_proxy_new() for the asynchronous version.
 *
 * Returns: A #PhonefsoUsageProxy or %NULL if error is set. Free with g_object_unref().
 */
PhonefsoUsage *phonefso_usage_proxy_new_sync (GDBusConnection     *connection,
                       GDBusProxyFlags      flags,
                       const gchar         *name,
                       const gchar         *object_path,
                       GCancellable        *cancellable,
                       GError             **error)
{
  GInitable *initable;
  initable = g_initable_new (TYPE_PHONEFSO_USAGE_PROXY,
                             cancellable,
                             error,
                             "g-flags", flags,
                             "g-name", name,
                             "g-connection", connection,
                             "g-object-path", object_path,
                             "g-interface-name", "org.shr.phonefso.Usage",
                             NULL);
  if (initable != NULL)
    return PHONEFSO_USAGE (initable);
  else
    return NULL;
}


/**
 * phonefso_usage_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags used when constructing the proxy.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: A #GCancellable or %NULL.
 * @callback: Callback function to invoke when the proxy is ready.
 * @user_data: User data to pass to @callback.
 *
 * Like g_dbus_proxy_new_for_bus() but returns a #PhonefsoUsageProxy.
 *
 * This is a failable asynchronous constructor - when the proxy is ready, callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this function from. You can then call phonefso_usage_proxy_new_for_bus_finish() to get the result. See phonefso_usage_proxy_new_for_bus_sync() for the synchronous version.
 */
void phonefso_usage_proxy_new_for_bus (GBusType             bus_type,
                           GDBusProxyFlags      flags,
                           const gchar         *name,
                           const gchar         *object_path,
                           GCancellable        *cancellable,
                           GAsyncReadyCallback  callback,
                           gpointer             user_data)
{
  g_async_initable_new_async (TYPE_PHONEFSO_USAGE_PROXY,
                              G_PRIORITY_DEFAULT,
                              cancellable,
                              callback,
                              user_data,
                              "g-flags", flags,
                              "g-name", name,
                              "g-bus-type", bus_type,
                              "g-object-path", object_path,
                              "g-interface-name", "org.shr.phonefso.Usage",
                              NULL);
}

/**
 * phonefso_usage_proxy_new_for_bus_finish:
 * @res: A #GAsyncResult obtained from the #GAsyncReadyCallback function passed to phonefso_usage_proxy_new_for_bus().
 * @error: Return location for error or %NULL.
 *
 * Finishes creating a #PhonefsoUsageProxy.
 *
 * Returns: A #PhonefsoUsageProxy or %NULL if @error is set. Free with g_object_unref().
 */
PhonefsoUsage *phonefso_usage_proxy_new_for_bus_finish (GAsyncResult  *res,
                                GError       **error)
{
  GObject *object;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  g_assert (source_object != NULL);
  object = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object),
                                        res,
                                        error);
  g_object_unref (source_object);
  if (object != NULL)
    return PHONEFSO_USAGE (object);
  else
    return NULL;
}

/**
 * phonefso_usage_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags used when constructing the proxy.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Like g_dbus_proxy_new_for_bus_sync() but returns a #PhonefsoUsageProxy.
 *
 * This is a synchronous failable constructor - the calling thread is blocked until the object is ready. See phonefso_usage_proxy_new_for_bus() for the asynchronous version.
 *
 * Returns: A #PhonefsoUsageProxy or %NULL if error is set. Free with g_object_unref().
 */
PhonefsoUsage *phonefso_usage_proxy_new_for_bus_sync (GBusType             bus_type,
                               GDBusProxyFlags      flags,
                               const gchar         *name,
                               const gchar         *object_path,
                               GCancellable        *cancellable,
                               GError             **error)
{
  GInitable *initable;
  initable = g_initable_new (TYPE_PHONEFSO_USAGE_PROXY,
                             cancellable,
                             error,
                             "g-flags", flags,
                             "g-name", name,
                             "g-bus-type", bus_type,
                             "g-object-path", object_path,
                             "g-interface-name", "org.shr.phonefso.Usage",
                             NULL);
  if (initable != NULL)
    return PHONEFSO_USAGE (initable);
  else
    return NULL;
}


/* ---------------------------------------------------------------------- */

struct _PhonefsoUsageStubPrivate
{
  GDBusObject *enclosing_object;
  GDBusInterfaceFlags flags;
};

static void stub_iface_init (PhonefsoUsageIface *iface);

G_DEFINE_TYPE_WITH_CODE (PhonefsoUsageStub, phonefso_usage_stub, G_TYPE_OBJECT,
                         G_IMPLEMENT_INTERFACE (G_TYPE_DBUS_INTERFACE, dbus_iface_init)
                         G_IMPLEMENT_INTERFACE (TYPE_PHONEFSO_USAGE, stub_iface_init));

static void
phonefso_usage_stub_finalize (GObject *object)
{
  G_GNUC_UNUSED PhonefsoUsageStub *stub = (PhonefsoUsageStub *) object;

  if (G_OBJECT_CLASS (phonefso_usage_stub_parent_class)->finalize != NULL)
    G_OBJECT_CLASS (phonefso_usage_stub_parent_class)->finalize (object);
}

static void
phonefso_usage_stub_get_property (GObject      *object,
                      guint         prop_id,
                      GValue       *value,
                      GParamSpec   *pspec)
{
  G_GNUC_UNUSED PhonefsoUsageStub *stub = (PhonefsoUsageStub *) object;
  switch (prop_id)
    {

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, prop_id, pspec);
      break;
    }
}

static void
phonefso_usage_stub_set_property (GObject      *object,
                      guint         prop_id,
                      const GValue *value,
                      GParamSpec   *pspec)
{
  G_GNUC_UNUSED PhonefsoUsageStub *stub = (PhonefsoUsageStub *) object;
  switch (prop_id)
    {

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, prop_id, pspec);
      break;
    }
}

static void
phonefso_usage_stub_init (PhonefsoUsageStub *stub)
{
  stub->priv = G_TYPE_INSTANCE_GET_PRIVATE (stub, TYPE_PHONEFSO_USAGE_STUB, PhonefsoUsageStubPrivate);
}

static void
phonefso_usage_stub_class_init (PhonefsoUsageStubClass *klass)
{
  GObjectClass *gobject_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = phonefso_usage_stub_finalize;
  gobject_class->get_property = phonefso_usage_stub_get_property;
  gobject_class->set_property = phonefso_usage_stub_set_property;
  g_type_class_add_private (klass, sizeof (PhonefsoUsageStubPrivate));
}

static void
stub_iface_init (PhonefsoUsageIface *iface)
{
}

/**
 * phonefso_usage_stub_new:
 *
 * Creates a new stub object that can be exported via g_dbus_interface_register_object().
 *
 * Returns: A #PhonefsoUsageStub instance. Free with g_object_unref().
 */
PhonefsoUsage *
phonefso_usage_stub_new (void)
{
  return PHONEFSO_USAGE (g_object_new (TYPE_PHONEFSO_USAGE_STUB, NULL));
}

static GDBusObject *
phonefso_usage_g_dbus_interface_get_object (GDBusInterface *interface)
{
  PhonefsoUsageStub *stub = G_TYPE_CHECK_INSTANCE_CAST (interface, TYPE_PHONEFSO_USAGE_STUB, PhonefsoUsageStub);
  if (stub->priv->enclosing_object != NULL)
    return g_object_ref (stub->priv->enclosing_object);
  else
    return NULL;
}

static void
phonefso_usage_g_dbus_interface_set_object (GDBusInterface *interface,
                                GDBusObject    *object)
{
  PhonefsoUsageStub *stub = G_TYPE_CHECK_INSTANCE_CAST (interface, TYPE_PHONEFSO_USAGE_STUB, PhonefsoUsageStub);
  stub->priv->enclosing_object = object;
}

static GDBusInterfaceFlags
phonefso_usage_g_dbus_interface_get_flags (GDBusInterface *interface)
{
  PhonefsoUsageStub *stub = G_TYPE_CHECK_INSTANCE_CAST (interface, TYPE_PHONEFSO_USAGE_STUB, PhonefsoUsageStub);
  return stub->priv->flags;
}

static void
phonefso_usage_g_dbus_interface_set_flags (GDBusInterface      *interface,
                               GDBusInterfaceFlags  flags)
{
  PhonefsoUsageStub *stub = G_TYPE_CHECK_INSTANCE_CAST (interface, TYPE_PHONEFSO_USAGE_STUB, PhonefsoUsageStub);
  stub->priv->flags = flags;
}

