/* File:       shr-bindings.h
 *
 * Generated by GDBus Binding Tool 0.1. DO NOT EDIT.
 */

#ifndef __SHR_BINDINGS_H__
#define __SHR_BINDINGS_H__

#include <gio/gio.h>

#include <shr-phonefsousage.h>
#include <shr-phoneuicallmanagement.h>
#include <shr-phoneuicontacts.h>
#include <shr-phoneuidialer.h>
#include <shr-phoneuiidlescreen.h>
#include <shr-phoneuimessages.h>
#include <shr-phoneuinotification.h>
#include <shr-phoneuiphonelog.h>
#include <shr-phoneuisettings.h>
#include <shr-proxymanager.h>
#include <shr-types.h>

#endif /* __SHR_BINDINGS_H__ */
