/* File:       shr-bindingsprivate.h
 *
 * Generated by GDBus Binding Tool 0.1. DO NOT EDIT.
 */

#ifndef __SHR_BINDINGSPRIVATE_H__
#define __SHR_BINDINGSPRIVATE_H__

#include <gio/gio.h>
#include <shr-types.h>


#endif /* __SHR_BINDINGSPRIVATE_H__ */
