/*
 * Generated by gdbus-codegen 2.29.3. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "shr-phonefsousage.h"

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        ret = (g_value_get_double (a) == g_value_get_double (b));
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.shr.phonefso.Usage
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:PhonefsoUsage
 * @title: PhonefsoUsage
 * @short_description: Generated C code for the org.shr.phonefso.Usage D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-shr-phonefso-Usage.top_of_page">org.shr.phonefso.Usage</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.shr.phonefso.Usage ---- */

static const _ExtendedGDBusArgInfo _phonefso_usage_method_info_set_offline_mode_IN_ARG_state =
{
  {
    -1,
    "state",
    "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _phonefso_usage_method_info_set_offline_mode_IN_ARG_pointers[] =
{
  &_phonefso_usage_method_info_set_offline_mode_IN_ARG_state,
  NULL
};

static const GDBusAnnotationInfo _phonefso_usage_method_set_offline_mode_annotation_info_0 =
{
  -1,
  "org.freedesktop.DBus.GLib.Async",
  "true",
  NULL
};

static const GDBusAnnotationInfo * const _phonefso_usage_method_set_offline_mode_annotation_info_pointers[] =
{
  &_phonefso_usage_method_set_offline_mode_annotation_info_0,
  NULL
};

static const _ExtendedGDBusMethodInfo _phonefso_usage_method_info_set_offline_mode =
{
  {
    -1,
    "SetOfflineMode",
    (GDBusArgInfo **) &_phonefso_usage_method_info_set_offline_mode_IN_ARG_pointers,
    NULL,
    (GDBusAnnotationInfo **) &_phonefso_usage_method_set_offline_mode_annotation_info_pointers
  },
  "handle-set-offline-mode"
};

static const _ExtendedGDBusArgInfo _phonefso_usage_method_info_get_offline_mode_OUT_ARG_state =
{
  {
    -1,
    "state",
    "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _phonefso_usage_method_info_get_offline_mode_OUT_ARG_pointers[] =
{
  &_phonefso_usage_method_info_get_offline_mode_OUT_ARG_state,
  NULL
};

static const GDBusAnnotationInfo _phonefso_usage_method_get_offline_mode_annotation_info_0 =
{
  -1,
  "org.freedesktop.DBus.GLib.Async",
  "true",
  NULL
};

static const GDBusAnnotationInfo * const _phonefso_usage_method_get_offline_mode_annotation_info_pointers[] =
{
  &_phonefso_usage_method_get_offline_mode_annotation_info_0,
  NULL
};

static const _ExtendedGDBusMethodInfo _phonefso_usage_method_info_get_offline_mode =
{
  {
    -1,
    "GetOfflineMode",
    NULL,
    (GDBusArgInfo **) &_phonefso_usage_method_info_get_offline_mode_OUT_ARG_pointers,
    (GDBusAnnotationInfo **) &_phonefso_usage_method_get_offline_mode_annotation_info_pointers
  },
  "handle-get-offline-mode"
};

static const _ExtendedGDBusArgInfo _phonefso_usage_method_info_set_default_brightness_IN_ARG_brightness =
{
  {
    -1,
    "brightness",
    "i",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _phonefso_usage_method_info_set_default_brightness_IN_ARG_pointers[] =
{
  &_phonefso_usage_method_info_set_default_brightness_IN_ARG_brightness,
  NULL
};

static const GDBusAnnotationInfo _phonefso_usage_method_set_default_brightness_annotation_info_0 =
{
  -1,
  "org.freedesktop.DBus.GLib.Async",
  "true",
  NULL
};

static const GDBusAnnotationInfo * const _phonefso_usage_method_set_default_brightness_annotation_info_pointers[] =
{
  &_phonefso_usage_method_set_default_brightness_annotation_info_0,
  NULL
};

static const _ExtendedGDBusMethodInfo _phonefso_usage_method_info_set_default_brightness =
{
  {
    -1,
    "SetDefaultBrightness",
    (GDBusArgInfo **) &_phonefso_usage_method_info_set_default_brightness_IN_ARG_pointers,
    NULL,
    (GDBusAnnotationInfo **) &_phonefso_usage_method_set_default_brightness_annotation_info_pointers
  },
  "handle-set-default-brightness"
};

static const _ExtendedGDBusArgInfo _phonefso_usage_method_info_get_default_brightness_OUT_ARG_brightness =
{
  {
    -1,
    "brightness",
    "i",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _phonefso_usage_method_info_get_default_brightness_OUT_ARG_pointers[] =
{
  &_phonefso_usage_method_info_get_default_brightness_OUT_ARG_brightness,
  NULL
};

static const GDBusAnnotationInfo _phonefso_usage_method_get_default_brightness_annotation_info_0 =
{
  -1,
  "org.freedesktop.DBus.GLib.Async",
  "true",
  NULL
};

static const GDBusAnnotationInfo * const _phonefso_usage_method_get_default_brightness_annotation_info_pointers[] =
{
  &_phonefso_usage_method_get_default_brightness_annotation_info_0,
  NULL
};

static const _ExtendedGDBusMethodInfo _phonefso_usage_method_info_get_default_brightness =
{
  {
    -1,
    "GetDefaultBrightness",
    NULL,
    (GDBusArgInfo **) &_phonefso_usage_method_info_get_default_brightness_OUT_ARG_pointers,
    (GDBusAnnotationInfo **) &_phonefso_usage_method_get_default_brightness_annotation_info_pointers
  },
  "handle-get-default-brightness"
};

static const _ExtendedGDBusArgInfo _phonefso_usage_method_info_set_pdp_credentials_IN_ARG_apn =
{
  {
    -1,
    "apn",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _phonefso_usage_method_info_set_pdp_credentials_IN_ARG_user =
{
  {
    -1,
    "user",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _phonefso_usage_method_info_set_pdp_credentials_IN_ARG_password =
{
  {
    -1,
    "password",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _phonefso_usage_method_info_set_pdp_credentials_IN_ARG_pointers[] =
{
  &_phonefso_usage_method_info_set_pdp_credentials_IN_ARG_apn,
  &_phonefso_usage_method_info_set_pdp_credentials_IN_ARG_user,
  &_phonefso_usage_method_info_set_pdp_credentials_IN_ARG_password,
  NULL
};

static const GDBusAnnotationInfo _phonefso_usage_method_set_pdp_credentials_annotation_info_0 =
{
  -1,
  "org.freedesktop.DBus.GLib.Async",
  "true",
  NULL
};

static const GDBusAnnotationInfo * const _phonefso_usage_method_set_pdp_credentials_annotation_info_pointers[] =
{
  &_phonefso_usage_method_set_pdp_credentials_annotation_info_0,
  NULL
};

static const _ExtendedGDBusMethodInfo _phonefso_usage_method_info_set_pdp_credentials =
{
  {
    -1,
    "SetPdpCredentials",
    (GDBusArgInfo **) &_phonefso_usage_method_info_set_pdp_credentials_IN_ARG_pointers,
    NULL,
    (GDBusAnnotationInfo **) &_phonefso_usage_method_set_pdp_credentials_annotation_info_pointers
  },
  "handle-set-pdp-credentials"
};

static const _ExtendedGDBusArgInfo _phonefso_usage_method_info_set_pin_IN_ARG_pin =
{
  {
    -1,
    "pin",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _phonefso_usage_method_info_set_pin_IN_ARG_pointers[] =
{
  &_phonefso_usage_method_info_set_pin_IN_ARG_pin,
  NULL
};

static const GDBusAnnotationInfo _phonefso_usage_method_set_pin_annotation_info_0 =
{
  -1,
  "org.freedesktop.DBus.GLib.Async",
  "true",
  NULL
};

static const GDBusAnnotationInfo * const _phonefso_usage_method_set_pin_annotation_info_pointers[] =
{
  &_phonefso_usage_method_set_pin_annotation_info_0,
  NULL
};

static const _ExtendedGDBusMethodInfo _phonefso_usage_method_info_set_pin =
{
  {
    -1,
    "SetPin",
    (GDBusArgInfo **) &_phonefso_usage_method_info_set_pin_IN_ARG_pointers,
    NULL,
    (GDBusAnnotationInfo **) &_phonefso_usage_method_set_pin_annotation_info_pointers
  },
  "handle-set-pin"
};

static const _ExtendedGDBusMethodInfo * const _phonefso_usage_method_info_pointers[] =
{
  &_phonefso_usage_method_info_set_offline_mode,
  &_phonefso_usage_method_info_get_offline_mode,
  &_phonefso_usage_method_info_set_default_brightness,
  &_phonefso_usage_method_info_get_default_brightness,
  &_phonefso_usage_method_info_set_pdp_credentials,
  &_phonefso_usage_method_info_set_pin,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _phonefso_usage_interface_info =
{
  {
    -1,
    "org.shr.phonefso.Usage",
    (GDBusMethodInfo **) &_phonefso_usage_method_info_pointers,
    NULL,
    NULL,
    NULL
  },
  "phonefso-usage",
};


/**
 * phonefso_usage_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-shr-phonefso-Usage.top_of_page">org.shr.phonefso.Usage</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
phonefso_usage_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_phonefso_usage_interface_info;
}



/**
 * PhonefsoUsage:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-shr-phonefso-Usage.top_of_page">org.shr.phonefso.Usage</link>.
 */

/**
 * PhonefsoUsageIface:
 * @parent_iface: The parent interface.
 * @handle_get_default_brightness: Handler for the #PhonefsoUsage::handle-get-default-brightness signal.
 * @handle_get_offline_mode: Handler for the #PhonefsoUsage::handle-get-offline-mode signal.
 * @handle_set_default_brightness: Handler for the #PhonefsoUsage::handle-set-default-brightness signal.
 * @handle_set_offline_mode: Handler for the #PhonefsoUsage::handle-set-offline-mode signal.
 * @handle_set_pdp_credentials: Handler for the #PhonefsoUsage::handle-set-pdp-credentials signal.
 * @handle_set_pin: Handler for the #PhonefsoUsage::handle-set-pin signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-shr-phonefso-Usage.top_of_page">org.shr.phonefso.Usage</link>.
 */

static void
phonefso_usage_default_init (PhonefsoUsageIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * PhonefsoUsage::handle-set-offline-mode:
   * @object: A #PhonefsoUsage.
   * @invocation: A #GDBusMethodInvocation.
   * @state: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-shr-phonefso-Usage.SetOfflineMode">SetOfflineMode()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call phonefso_usage_complete_set_offline_mode() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-offline-mode",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (PhonefsoUsageIface, handle_set_offline_mode),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_BOOLEAN);

  /**
   * PhonefsoUsage::handle-get-offline-mode:
   * @object: A #PhonefsoUsage.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-shr-phonefso-Usage.GetOfflineMode">GetOfflineMode()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call phonefso_usage_complete_get_offline_mode() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-offline-mode",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (PhonefsoUsageIface, handle_get_offline_mode),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * PhonefsoUsage::handle-set-default-brightness:
   * @object: A #PhonefsoUsage.
   * @invocation: A #GDBusMethodInvocation.
   * @brightness: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-shr-phonefso-Usage.SetDefaultBrightness">SetDefaultBrightness()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call phonefso_usage_complete_set_default_brightness() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-default-brightness",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (PhonefsoUsageIface, handle_set_default_brightness),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_INT);

  /**
   * PhonefsoUsage::handle-get-default-brightness:
   * @object: A #PhonefsoUsage.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-shr-phonefso-Usage.GetDefaultBrightness">GetDefaultBrightness()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call phonefso_usage_complete_get_default_brightness() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-default-brightness",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (PhonefsoUsageIface, handle_get_default_brightness),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * PhonefsoUsage::handle-set-pdp-credentials:
   * @object: A #PhonefsoUsage.
   * @invocation: A #GDBusMethodInvocation.
   * @apn: Argument passed by remote caller.
   * @user: Argument passed by remote caller.
   * @password: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-shr-phonefso-Usage.SetPdpCredentials">SetPdpCredentials()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call phonefso_usage_complete_set_pdp_credentials() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-pdp-credentials",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (PhonefsoUsageIface, handle_set_pdp_credentials),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    4,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRING);

  /**
   * PhonefsoUsage::handle-set-pin:
   * @object: A #PhonefsoUsage.
   * @invocation: A #GDBusMethodInvocation.
   * @pin: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-shr-phonefso-Usage.SetPin">SetPin()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call phonefso_usage_complete_set_pin() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-pin",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (PhonefsoUsageIface, handle_set_pin),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

}

typedef PhonefsoUsageIface PhonefsoUsageInterface;
G_DEFINE_INTERFACE (PhonefsoUsage, phonefso_usage, G_TYPE_OBJECT);

/**
 * phonefso_usage_call_set_offline_mode:
 * @proxy: A #PhonefsoUsageProxy.
 * @state: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-shr-phonefso-Usage.SetOfflineMode">SetOfflineMode()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call phonefso_usage_call_set_offline_mode_finish() to get the result of the operation.
 *
 * See phonefso_usage_call_set_offline_mode_sync() for the synchronous, blocking version of this method.
 */
void
phonefso_usage_call_set_offline_mode (
    PhonefsoUsage *proxy,
    gboolean state,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "SetOfflineMode",
    g_variant_new ("(b)",
                   state),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * phonefso_usage_call_set_offline_mode_finish:
 * @proxy: A #PhonefsoUsageProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to phonefso_usage_call_set_offline_mode().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with phonefso_usage_call_set_offline_mode().
 *
 * Returns: %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
phonefso_usage_call_set_offline_mode_finish (
    PhonefsoUsage *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * phonefso_usage_call_set_offline_mode_sync:
 * @proxy: A #PhonefsoUsageProxy.
 * @state: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-shr-phonefso-Usage.SetOfflineMode">SetOfflineMode()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See phonefso_usage_call_set_offline_mode() for the asynchronous version of this method.
 *
 * Returns: %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
phonefso_usage_call_set_offline_mode_sync (
    PhonefsoUsage *proxy,
    gboolean state,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "SetOfflineMode",
    g_variant_new ("(b)",
                   state),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * phonefso_usage_call_get_offline_mode:
 * @proxy: A #PhonefsoUsageProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-shr-phonefso-Usage.GetOfflineMode">GetOfflineMode()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call phonefso_usage_call_get_offline_mode_finish() to get the result of the operation.
 *
 * See phonefso_usage_call_get_offline_mode_sync() for the synchronous, blocking version of this method.
 */
void
phonefso_usage_call_get_offline_mode (
    PhonefsoUsage *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetOfflineMode",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * phonefso_usage_call_get_offline_mode_finish:
 * @proxy: A #PhonefsoUsageProxy.
 * @out_state: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to phonefso_usage_call_get_offline_mode().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with phonefso_usage_call_get_offline_mode().
 *
 * Returns: %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
phonefso_usage_call_get_offline_mode_finish (
    PhonefsoUsage *proxy,
    gboolean *out_state,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_state);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * phonefso_usage_call_get_offline_mode_sync:
 * @proxy: A #PhonefsoUsageProxy.
 * @out_state: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-shr-phonefso-Usage.GetOfflineMode">GetOfflineMode()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See phonefso_usage_call_get_offline_mode() for the asynchronous version of this method.
 *
 * Returns: %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
phonefso_usage_call_get_offline_mode_sync (
    PhonefsoUsage *proxy,
    gboolean *out_state,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetOfflineMode",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_state);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * phonefso_usage_call_set_default_brightness:
 * @proxy: A #PhonefsoUsageProxy.
 * @brightness: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-shr-phonefso-Usage.SetDefaultBrightness">SetDefaultBrightness()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call phonefso_usage_call_set_default_brightness_finish() to get the result of the operation.
 *
 * See phonefso_usage_call_set_default_brightness_sync() for the synchronous, blocking version of this method.
 */
void
phonefso_usage_call_set_default_brightness (
    PhonefsoUsage *proxy,
    gint brightness,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "SetDefaultBrightness",
    g_variant_new ("(i)",
                   brightness),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * phonefso_usage_call_set_default_brightness_finish:
 * @proxy: A #PhonefsoUsageProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to phonefso_usage_call_set_default_brightness().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with phonefso_usage_call_set_default_brightness().
 *
 * Returns: %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
phonefso_usage_call_set_default_brightness_finish (
    PhonefsoUsage *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * phonefso_usage_call_set_default_brightness_sync:
 * @proxy: A #PhonefsoUsageProxy.
 * @brightness: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-shr-phonefso-Usage.SetDefaultBrightness">SetDefaultBrightness()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See phonefso_usage_call_set_default_brightness() for the asynchronous version of this method.
 *
 * Returns: %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
phonefso_usage_call_set_default_brightness_sync (
    PhonefsoUsage *proxy,
    gint brightness,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "SetDefaultBrightness",
    g_variant_new ("(i)",
                   brightness),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * phonefso_usage_call_get_default_brightness:
 * @proxy: A #PhonefsoUsageProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-shr-phonefso-Usage.GetDefaultBrightness">GetDefaultBrightness()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call phonefso_usage_call_get_default_brightness_finish() to get the result of the operation.
 *
 * See phonefso_usage_call_get_default_brightness_sync() for the synchronous, blocking version of this method.
 */
void
phonefso_usage_call_get_default_brightness (
    PhonefsoUsage *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetDefaultBrightness",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * phonefso_usage_call_get_default_brightness_finish:
 * @proxy: A #PhonefsoUsageProxy.
 * @out_brightness: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to phonefso_usage_call_get_default_brightness().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with phonefso_usage_call_get_default_brightness().
 *
 * Returns: %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
phonefso_usage_call_get_default_brightness_finish (
    PhonefsoUsage *proxy,
    gint *out_brightness,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(i)",
                 out_brightness);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * phonefso_usage_call_get_default_brightness_sync:
 * @proxy: A #PhonefsoUsageProxy.
 * @out_brightness: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-shr-phonefso-Usage.GetDefaultBrightness">GetDefaultBrightness()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See phonefso_usage_call_get_default_brightness() for the asynchronous version of this method.
 *
 * Returns: %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
phonefso_usage_call_get_default_brightness_sync (
    PhonefsoUsage *proxy,
    gint *out_brightness,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetDefaultBrightness",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(i)",
                 out_brightness);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * phonefso_usage_call_set_pdp_credentials:
 * @proxy: A #PhonefsoUsageProxy.
 * @apn: Argument to pass with the method invocation.
 * @user: Argument to pass with the method invocation.
 * @password: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-shr-phonefso-Usage.SetPdpCredentials">SetPdpCredentials()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call phonefso_usage_call_set_pdp_credentials_finish() to get the result of the operation.
 *
 * See phonefso_usage_call_set_pdp_credentials_sync() for the synchronous, blocking version of this method.
 */
void
phonefso_usage_call_set_pdp_credentials (
    PhonefsoUsage *proxy,
    const gchar *apn,
    const gchar *user,
    const gchar *password,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "SetPdpCredentials",
    g_variant_new ("(sss)",
                   apn,
                   user,
                   password),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * phonefso_usage_call_set_pdp_credentials_finish:
 * @proxy: A #PhonefsoUsageProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to phonefso_usage_call_set_pdp_credentials().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with phonefso_usage_call_set_pdp_credentials().
 *
 * Returns: %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
phonefso_usage_call_set_pdp_credentials_finish (
    PhonefsoUsage *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * phonefso_usage_call_set_pdp_credentials_sync:
 * @proxy: A #PhonefsoUsageProxy.
 * @apn: Argument to pass with the method invocation.
 * @user: Argument to pass with the method invocation.
 * @password: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-shr-phonefso-Usage.SetPdpCredentials">SetPdpCredentials()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See phonefso_usage_call_set_pdp_credentials() for the asynchronous version of this method.
 *
 * Returns: %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
phonefso_usage_call_set_pdp_credentials_sync (
    PhonefsoUsage *proxy,
    const gchar *apn,
    const gchar *user,
    const gchar *password,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "SetPdpCredentials",
    g_variant_new ("(sss)",
                   apn,
                   user,
                   password),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * phonefso_usage_call_set_pin:
 * @proxy: A #PhonefsoUsageProxy.
 * @pin: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-shr-phonefso-Usage.SetPin">SetPin()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call phonefso_usage_call_set_pin_finish() to get the result of the operation.
 *
 * See phonefso_usage_call_set_pin_sync() for the synchronous, blocking version of this method.
 */
void
phonefso_usage_call_set_pin (
    PhonefsoUsage *proxy,
    const gchar *pin,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "SetPin",
    g_variant_new ("(s)",
                   pin),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * phonefso_usage_call_set_pin_finish:
 * @proxy: A #PhonefsoUsageProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to phonefso_usage_call_set_pin().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with phonefso_usage_call_set_pin().
 *
 * Returns: %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
phonefso_usage_call_set_pin_finish (
    PhonefsoUsage *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * phonefso_usage_call_set_pin_sync:
 * @proxy: A #PhonefsoUsageProxy.
 * @pin: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-shr-phonefso-Usage.SetPin">SetPin()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See phonefso_usage_call_set_pin() for the asynchronous version of this method.
 *
 * Returns: %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
phonefso_usage_call_set_pin_sync (
    PhonefsoUsage *proxy,
    const gchar *pin,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "SetPin",
    g_variant_new ("(s)",
                   pin),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * phonefso_usage_complete_set_offline_mode:
 * @object: A #PhonefsoUsage.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-shr-phonefso-Usage.SetOfflineMode">SetOfflineMode()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
phonefso_usage_complete_set_offline_mode (
    PhonefsoUsage *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * phonefso_usage_complete_get_offline_mode:
 * @object: A #PhonefsoUsage.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @state: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-shr-phonefso-Usage.GetOfflineMode">GetOfflineMode()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
phonefso_usage_complete_get_offline_mode (
    PhonefsoUsage *object,
    GDBusMethodInvocation *invocation,
    gboolean state)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   state));
}

/**
 * phonefso_usage_complete_set_default_brightness:
 * @object: A #PhonefsoUsage.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-shr-phonefso-Usage.SetDefaultBrightness">SetDefaultBrightness()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
phonefso_usage_complete_set_default_brightness (
    PhonefsoUsage *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * phonefso_usage_complete_get_default_brightness:
 * @object: A #PhonefsoUsage.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @brightness: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-shr-phonefso-Usage.GetDefaultBrightness">GetDefaultBrightness()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
phonefso_usage_complete_get_default_brightness (
    PhonefsoUsage *object,
    GDBusMethodInvocation *invocation,
    gint brightness)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(i)",
                   brightness));
}

/**
 * phonefso_usage_complete_set_pdp_credentials:
 * @object: A #PhonefsoUsage.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-shr-phonefso-Usage.SetPdpCredentials">SetPdpCredentials()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
phonefso_usage_complete_set_pdp_credentials (
    PhonefsoUsage *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * phonefso_usage_complete_set_pin:
 * @object: A #PhonefsoUsage.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-shr-phonefso-Usage.SetPin">SetPin()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
phonefso_usage_complete_set_pin (
    PhonefsoUsage *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * PhonefsoUsageProxy:
 *
 * The #PhonefsoUsageProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * PhonefsoUsageProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #PhonefsoUsageProxy.
 */

static void
phonefso_usage_proxy_iface_init (PhonefsoUsageIface *iface)
{
}

#define phonefso_usage_proxy_get_type phonefso_usage_proxy_get_type
G_DEFINE_TYPE_WITH_CODE (PhonefsoUsageProxy, phonefso_usage_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_PHONEFSO_USAGE, phonefso_usage_proxy_iface_init));
#undef phonefso_usage_proxy_get_type

static void
phonefso_usage_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
}

static void
phonefso_usage_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
}

static void
phonefso_usage_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_phonefso_usage_interface_info, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TYPE_PHONEFSO_USAGE);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_PHONEFSO_USAGE);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
phonefso_usage_proxy_g_properties_changed (GDBusProxy *proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_phonefso_usage_interface_info, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_phonefso_usage_interface_info, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
phonefso_usage_proxy_init (PhonefsoUsageProxy *proxy)
{
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), phonefso_usage_interface_info ());
}

static void
phonefso_usage_proxy_class_init (PhonefsoUsageProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->get_property = phonefso_usage_proxy_get_property;
  gobject_class->set_property = phonefso_usage_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = phonefso_usage_proxy_g_signal;
  proxy_class->g_properties_changed = phonefso_usage_proxy_g_properties_changed;

}

/**
 * phonefso_usage_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-shr-phonefso-Usage.top_of_page">org.shr.phonefso.Usage</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call phonefso_usage_proxy_new_finish() to get the result of the operation.
 *
 * See phonefso_usage_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
phonefso_usage_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_PHONEFSO_USAGE_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.shr.phonefso.Usage", NULL);
}

/**
 * phonefso_usage_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to phonefso_usage_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with phonefso_usage_proxy_new().
 *
 * Returns: (transfer full) (type PhonefsoUsageProxy): The constructed proxy object or %NULL if @error is set.
 */
PhonefsoUsage *
phonefso_usage_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return PHONEFSO_USAGE (ret);
  else
    return NULL;
}

/**
 * phonefso_usage_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-shr-phonefso-Usage.top_of_page">org.shr.phonefso.Usage</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See phonefso_usage_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type PhonefsoUsageProxy): The constructed proxy object or %NULL if @error is set.
 */
PhonefsoUsage *
phonefso_usage_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_PHONEFSO_USAGE_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.shr.phonefso.Usage", NULL);
  if (ret != NULL)
    return PHONEFSO_USAGE (ret);
  else
    return NULL;
}


/**
 * phonefso_usage_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like phonefso_usage_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call phonefso_usage_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See phonefso_usage_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
phonefso_usage_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_PHONEFSO_USAGE_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.shr.phonefso.Usage", NULL);
}

/**
 * phonefso_usage_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to phonefso_usage_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with phonefso_usage_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type PhonefsoUsageProxy): The constructed proxy object or %NULL if @error is set.
 */
PhonefsoUsage *
phonefso_usage_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return PHONEFSO_USAGE (ret);
  else
    return NULL;
}

/**
 * phonefso_usage_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like phonefso_usage_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See phonefso_usage_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type PhonefsoUsageProxy): The constructed proxy object or %NULL if @error is set.
 */
PhonefsoUsage *
phonefso_usage_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_PHONEFSO_USAGE_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.shr.phonefso.Usage", NULL);
  if (ret != NULL)
    return PHONEFSO_USAGE (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * PhonefsoUsageSkeleton:
 *
 * The #PhonefsoUsageSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * PhonefsoUsageSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #PhonefsoUsageSkeleton.
 */

struct _PhonefsoUsageSkeletonPrivate
{
  GValueArray *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
};

static void
_phonefso_usage_skeleton_handle_method_call (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  PhonefsoUsageSkeleton *skeleton = PHONEFSO_USAGE_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  GValue return_value = {0};
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 2);
  g_value_init (&paramv[0], TYPE_PHONEFSO_USAGE);
  g_value_set_object (&paramv[0], skeleton);
  g_value_init (&paramv[1], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[1], invocation);
  g_variant_iter_init (&iter, parameters);
  n = 2;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - 2];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_PHONEFSO_USAGE);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + 2; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_phonefso_usage_skeleton_handle_get_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  PhonefsoUsageSkeleton *skeleton = PHONEFSO_USAGE_SKELETON (user_data);
  GValue value = {0};
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_phonefso_usage_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_phonefso_usage_skeleton_handle_set_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  PhonefsoUsageSkeleton *skeleton = PHONEFSO_USAGE_SKELETON (user_data);
  GValue value = {0};
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_phonefso_usage_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _phonefso_usage_skeleton_vtable =
{
  _phonefso_usage_skeleton_handle_method_call,
  _phonefso_usage_skeleton_handle_get_property,
  _phonefso_usage_skeleton_handle_set_property
};

static GDBusInterfaceInfo *
phonefso_usage_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton)
{
  return phonefso_usage_interface_info ();
}

static GDBusInterfaceVTable *
phonefso_usage_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton)
{
  return (GDBusInterfaceVTable *) &_phonefso_usage_skeleton_vtable;
}

static GVariant *
phonefso_usage_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  PhonefsoUsageSkeleton *skeleton = PHONEFSO_USAGE_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_phonefso_usage_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _phonefso_usage_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _phonefso_usage_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _phonefso_usage_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.shr.phonefso.Usage", info->name, NULL, skeleton);
          if (value != NULL)
            {
              if (g_variant_is_floating (value))
                g_variant_ref_sink (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
phonefso_usage_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void
phonefso_usage_skeleton_iface_init (PhonefsoUsageIface *iface)
{
}

#define phonefso_usage_skeleton_get_type phonefso_usage_skeleton_get_type
G_DEFINE_TYPE_WITH_CODE (PhonefsoUsageSkeleton, phonefso_usage_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TYPE_PHONEFSO_USAGE, phonefso_usage_skeleton_iface_init));
#undef phonefso_usage_skeleton_get_type

static void
phonefso_usage_skeleton_finalize (GObject *object)
{
  PhonefsoUsageSkeleton *skeleton = PHONEFSO_USAGE_SKELETON (object);
  g_list_foreach (skeleton->priv->changed_properties, (GFunc) _changed_property_free, NULL);
  g_list_free (skeleton->priv->changed_properties);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  if (skeleton->priv->context != NULL)
    g_main_context_unref (skeleton->priv->context);
  G_OBJECT_CLASS (phonefso_usage_skeleton_parent_class)->finalize (object);
}

static void
phonefso_usage_skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  PhonefsoUsageSkeleton *skeleton = PHONEFSO_USAGE_SKELETON (object);
  g_assert (prop_id - 1 >= 0 && prop_id - 1 < 0);
  g_value_copy (&skeleton->priv->properties->values[prop_id - 1], value);
}

static void
phonefso_usage_skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
}

static void
phonefso_usage_skeleton_init (PhonefsoUsageSkeleton *skeleton)
{
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TYPE_PHONEFSO_USAGE_SKELETON, PhonefsoUsageSkeletonPrivate);
  skeleton->priv->context = g_main_context_get_thread_default ();
  if (skeleton->priv->context != NULL)
    g_main_context_ref (skeleton->priv->context);
}

static void
phonefso_usage_skeleton_class_init (PhonefsoUsageSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  g_type_class_add_private (klass, sizeof (PhonefsoUsageSkeletonPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = phonefso_usage_skeleton_finalize;
  gobject_class->get_property = phonefso_usage_skeleton_get_property;
  gobject_class->set_property = phonefso_usage_skeleton_set_property;


  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = phonefso_usage_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = phonefso_usage_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = phonefso_usage_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = phonefso_usage_skeleton_dbus_interface_get_vtable;
}

/**
 * phonefso_usage_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-shr-phonefso-Usage.top_of_page">org.shr.phonefso.Usage</link>.
 *
 * Returns: (transfer full) (type PhonefsoUsageSkeleton): The skeleton object.
 */
PhonefsoUsage *
phonefso_usage_skeleton_new (void)
{
  return PHONEFSO_USAGE (g_object_new (TYPE_PHONEFSO_USAGE_SKELETON, NULL));
}

