/* File:       shr-phoneuiphonelog.h
 *
 * GType name: PhoneuiPhoneLog
 * D-Bus name: org.shr.phoneui.PhoneLog
 *
 * Generated by GDBus Binding Tool 0.1. DO NOT EDIT.
 */

#ifndef __SHR_PHONEUI_PHONE_LOG_H__
#define __SHR_PHONEUI_PHONE_LOG_H__

#include <gio/gio.h>
#include <gdbusinterface.h>
#include <gdbusobjectproxy.h>
#include <gdbusproxymanager.h>
#include <gdbusobject.h>
#include <gdbusobjectmanager.h>
#include <gdbuscodegen-enumtypes.h>
#include <string.h>
#include <shr-types.h>

G_BEGIN_DECLS

#define TYPE_PHONEUI_PHONE_LOG         (phoneui_phone_log_get_gtype ())
#define PHONEUI_PHONE_LOG(o)           (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_PHONEUI_PHONE_LOG, PhoneuiPhoneLog))
#define IS_PHONEUI_PHONE_LOG(o)        (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_PHONEUI_PHONE_LOG))
#define PHONEUI_PHONE_LOG_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE((o), TYPE_PHONEUI_PHONE_LOG, PhoneuiPhoneLogIface))

/**
 * PhoneuiPhoneLog:
 *
 * Opaque type representing a proxy or an exported object.
 */
typedef struct _PhoneuiPhoneLog PhoneuiPhoneLog; /* Dummy typedef */
/**
 * PhoneuiPhoneLogIface:
 * @parent_iface: The parent interface.
 * @handle_display_list: Handler for the #PhoneuiPhoneLog::handle-display-list signal.
 *
 * Virtual table.
 */
typedef struct _PhoneuiPhoneLogIface PhoneuiPhoneLogIface;

GType phoneui_phone_log_get_gtype (void) G_GNUC_CONST;
GDBusInterfaceInfo *phoneui_phone_log_interface_info (void);

/**
 * GET_PHONEUI_PHONE_LOG:
 * @object_proxy: A #GDBusObjectProxy.
 *
 * Convenience macro to get a #PhoneuiPhoneLog interface proxy from @object_proxy.
 *
 * Returns: A #GDBusProxy object implementing the #PhoneuiPhoneLog interface or %NULL if @object_proxy
 * does not implement the <literal>org.shr.phoneui.PhoneLog</literal> D-Bus interface.
 * The returned reference must be released with g_object_unref().
 */
#define GET_PHONEUI_PHONE_LOG(object_proxy) (g_dbus_object_proxy_lookup_with_typecheck (object_proxy, "org.shr.phoneui.PhoneLog", TYPE_PHONEUI_PHONE_LOG))

/**
 * PEEK_PHONEUI_PHONE_LOG:
 * @object_proxy: A #GDBusObjectProxy.
 *
 * Like GET_PHONEUI_PHONE_LOG() but doesn't increase the reference count on the returned object.
 *
 * <note><para>This macro is not safe to use outside the thread where the #GDBusProxyManager for @object_proxy was constructed in.</para></note>
 *
 * Returns: A #GDBusProxy object implementing the #PhoneuiPhoneLog interface or %NULL if @object_proxy
 * does not implement the <literal>org.shr.phoneui.PhoneLog</literal> D-Bus interface.
 * Do not free the returned object, it is owned by @object_proxy..
 */
#define PEEK_PHONEUI_PHONE_LOG(object_proxy) (g_dbus_object_proxy_peek_with_typecheck (object_proxy, "org.shr.phoneui.PhoneLog", TYPE_PHONEUI_PHONE_LOG))


/* ---------------------------------------------------------------------- */

typedef struct _PhoneuiPhoneLogProxy PhoneuiPhoneLogProxy;
typedef struct _PhoneuiPhoneLogProxyClass PhoneuiPhoneLogProxyClass;

/**
 * PhoneuiPhoneLogProxyPrivate:
 *
 * The #PhoneuiPhoneLogProxyPrivate structure contains only private data.
 */
typedef struct _PhoneuiPhoneLogProxyPrivate PhoneuiPhoneLogProxyPrivate;

/**
 * PhoneuiPhoneLogProxy:
 *
 * The #PhoneuiPhoneLogProxy structure contains only private data and
 * should only be accessed using the provided API.
 */
struct _PhoneuiPhoneLogProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  PhoneuiPhoneLogProxyPrivate *priv;
};

/**
 * PhoneuiPhoneLogProxyClass:
 *
 * Class structure for #PhoneuiPhoneLogProxy.
 */
struct _PhoneuiPhoneLogProxyClass
{
  /*< private >*/
  GDBusProxyClass parent_class;
};

#define TYPE_PHONEUI_PHONE_LOG_PROXY (phoneui_phone_log_proxy_get_type ())
GType phoneui_phone_log_proxy_get_type (void) G_GNUC_CONST;

void phoneui_phone_log_proxy_new (GDBusConnection     *connection,
                   GDBusProxyFlags      flags,
                   const gchar         *name,
                   const gchar         *object_path,
                   GCancellable        *cancellable,
                   GAsyncReadyCallback  callback,
                   gpointer             user_data);
PhoneuiPhoneLog *phoneui_phone_log_proxy_new_finish (GAsyncResult  *res,
                        GError       **error);
PhoneuiPhoneLog *phoneui_phone_log_proxy_new_sync (GDBusConnection     *connection,
                       GDBusProxyFlags      flags,
                       const gchar         *name,
                       const gchar         *object_path,
                       GCancellable        *cancellable,
                       GError             **error);

void phoneui_phone_log_proxy_new_for_bus (GBusType             bus_type,
                           GDBusProxyFlags      flags,
                           const gchar         *name,
                           const gchar         *object_path,
                           GCancellable        *cancellable,
                           GAsyncReadyCallback  callback,
                           gpointer             user_data);
PhoneuiPhoneLog *phoneui_phone_log_proxy_new_for_bus_finish (GAsyncResult  *res,
                                 GError       **error);
PhoneuiPhoneLog *phoneui_phone_log_proxy_new_for_bus_sync (GBusType             bus_type,
                               GDBusProxyFlags      flags,
                               const gchar         *name,
                               const gchar         *object_path,
                               GCancellable        *cancellable,
                               GError             **error);

/* ---------------------------------------------------------------------- */

typedef struct _PhoneuiPhoneLogStub PhoneuiPhoneLogStub;
typedef struct _PhoneuiPhoneLogStubClass PhoneuiPhoneLogStubClass;

/**
 * PhoneuiPhoneLogStubPrivate:
 *
 * The #PhoneuiPhoneLogStubPrivate structure contains only private data.
 */
typedef struct _PhoneuiPhoneLogStubPrivate PhoneuiPhoneLogStubPrivate;

/**
 * PhoneuiPhoneLogStub:
 *
 * The #PhoneuiPhoneLogStub structure contains only private data and
 * should only be accessed using the provided API.
 */
struct _PhoneuiPhoneLogStub
{
  /*< private >*/
  GObject parent_instance;
  PhoneuiPhoneLogStubPrivate *priv;
};

/**
 * PhoneuiPhoneLogStubClass:
 *
 * Class structure for #PhoneuiPhoneLogStub.
 */
struct _PhoneuiPhoneLogStubClass
{
  /*< private >*/
  GObjectClass parent_class;
};

#define TYPE_PHONEUI_PHONE_LOG_STUB (phoneui_phone_log_stub_get_type ())
GType phoneui_phone_log_stub_get_type (void) G_GNUC_CONST;

PhoneuiPhoneLog *phoneui_phone_log_stub_new (void);


struct _PhoneuiPhoneLogIface
{
  GTypeInterface parent_iface;

  /* Signal handlers for handling D-Bus method calls: */
  gboolean (*handle_display_list) (
        PhoneuiPhoneLog *object,
        GDBusMethodInvocation *invocation,
        GVariant *filter);
};

/* C Bindings for properties */


/* D-Bus Methods */
void phoneui_phone_log_call_display_list (
        PhoneuiPhoneLog *proxy,
        GVariant *filter,
        GCancellable *cancellable,
        GAsyncReadyCallback callback,
        gpointer user_data);

gboolean phoneui_phone_log_call_display_list_finish (
        PhoneuiPhoneLog *proxy,
        GAsyncResult *res,
        GError **error);

gboolean phoneui_phone_log_call_display_list_sync (
        PhoneuiPhoneLog *proxy,
        GVariant *filter,
        GCancellable *cancellable,
        GError **error);



/* D-Bus Methods Completion Helpers */
void phoneui_phone_log_complete_display_list (
        PhoneuiPhoneLog *object,
        GDBusMethodInvocation *invocation);



/* D-Bus Signal Emission Helpers */

G_END_DECLS

#endif /* __SHR_PHONEUI_PHONE_LOG_H__ */
